### ISSUE TITLE
Issue Integrating PyCaret with KNIME Analytics

### ISSUE THREAD

**Issue by prabhpreetsidhu** [pycaret/pycaret#1011]
Hi,

I am trying to use Pycaret within KNIME Analytics for regresison modelling. I created a virtual enviroment for that and downloaded the required libraries but am getting the below DLL issue when using it KNIME's python IDE. Any help on this would be highly appreciated. Code attached below - 

ERROR Python Source        0:1        Execute failed: DLL load failed: The specified module could not be found.
Traceback (most recent call last):
File "<string>", line 1, in <module>
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\pycaret\regression.py", line 10, in <module>
    import pycaret.internal.tabular
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\pycaret\internal\tabular.py", line 9, in <module>
    from pycaret.internal.meta_estimators import (
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\pycaret\internal\meta_estimators.py", line 4, in <module>
    from pycaret.internal.utils import get_all_object_vars_and_properties, is_fit_var
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\pycaret\internal\utils.py", line 11, in <module>
    import ipywidgets as ipw
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\ipywidgets\__init__.py", line 25, in <module>
    from .widgets import *
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\ipywidgets\widgets\__init__.py", line 4, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\ipywidgets\widgets\widget.py", line 18, in <module>
    from ipykernel.comm import Comm
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\zmq\__init__.py", line 55, in <module>
    from zmq import backend
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.

**Comment by Yard1** [comment]
This is not a PyCaret error.

**Comment by prabhpreetsidhu** [comment]
Thanks for your response. I am getting the same error when trying to model on PowerBI also. Would you be able to direct me towards the issue here. 

DataSource.Error: ADO.NET: Python script error.
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 12, in <module>
    from pycaret.regression import *
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\pycaret\regression.py", line 10, in <module>
    import pycaret.internal.tabular
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\pycaret\internal\tabular.py", line 9, in <module>
    from pycaret.internal.meta_estimators import (
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\pycaret\internal\meta_estimators.py", line 4, in <module>
    from pycaret.internal.utils import get_all_object_vars_and_properties, is_fit_var
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\pycaret\internal\utils.py", line 11, in <module>
    import ipywidgets as ipw
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\ipywidgets\__init__.py", line 25, in <module>
    from .widgets import *
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\ipywidgets\widgets\__init__.py", line 4, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\ipywidgets\widgets\widget.py", line 18, in <module>
    from ipykernel.comm import Comm
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\zmq\__init__.py", line 55, in <module>
    from zmq import backend
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\prabh\Anaconda3\envs\py3_knime\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.
