### ISSUE TITLE
NameError: name '_all_models_internal' is not defined

### ISSUE THREAD

**Issue by sagarnildass** [pycaret/pycaret#1052]
I am using gunicorn for running a flask app which is using pycaret in the backend. I am saving all the internal components like the leaderboard, model etc in a redis server (so that the states can be shared between workers). Now when I am using upto 2 workers like this: 

```
gunicorn --bind 0.0.0.0:9080 wsgi:application --timeout 500 --workers 2
```
Everything is working fine all the way up to finalize_model.

But when I am increasing the above number of workers to 3, during the create_model process, I am getting an error:

```
Traceback (most recent call last):
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/site-packages/dash/dash.py", line 1076, in dispatch
    response.set_data(func(*args, outputs_list=outputs_list))
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/site-packages/dash/dash.py", line 1007, in add_context
    output_value = func(*args, **kwargs)  # %% callback invoked %%
  File "/home/sagarnildass/python_notebooks/startup/darkarosh_without_db_gunicorn_multiple_workers/app/cyberdeck.py", line 2380, in train_model
    param_grid
  File "/home/sagarnildass/python_notebooks/startup/darkarosh_without_db_gunicorn_multiple_workers/app/machine_learning/pycaret_ml_main.py", line 78, in run_final_algo
    algo_index, param_grid)
  File "/home/sagarnildass/python_notebooks/startup/darkarosh_without_db_gunicorn_multiple_workers/app/machine_learning/pycaret_ml_tabular_training.py", line 368, in select_algo
    model = classification.create_model(algo_selected, verbose=False)
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/site-packages/pycaret/classification.py", line 897, in create_model
    **kwargs,
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 2868, in create_model_supervised
    available_estimators = set(_all_models_internal.keys())
NameError: name '_all_models_internal' is not defined
```

Please help.

**Comment by Yard1** [comment]
How are you importing PyCaret in the code?

**Comment by sagarnildass** [comment]
I am importing it as

```
from pycaret.classification import *"
```

Like I said, when the number of workers is <=2, I am not having any problem, the whole code is running fine. Only with >=3 workers, I am facing this problem.

**Comment by Yard1** [comment]
I am not sure whether this is an issue with PyCaret or gunicorn. We have not ran tests with or aimed for compatibility with it.

**Comment by sagarnildass** [comment]
Figured it out. This error is thrown when the intermediate stage is not saved in something like redis as the new worker doesn't know about the existent states.

**Comment by tvaditya** [comment]
How did you save the state?

**Comment by Yard1** [comment]
Do you have any reproducible code? @batmanscode

**Comment by batmanscode** [comment]
Sorry for the delay @Yard1. Here's the code

Run this with `uvicorn pycaret_test:app --reload` and optionally you can set `--host 0.0.0.0 --port 8080` if you need to

*requirements.txt*
```
pycaret
uvicorn[standard]
fastapi
python-multipart
```

*pycaret_test.py*
```
import shutil
from datetime import date
from fastapi import FastAPI, File, Query, UploadFile, HTTPException, Form
from fastapi.responses import FileResponse, PlainTextResponse


#### cluster labels ####


def assign_cluster_labels(
    saved_model, save_output=True, file_name=None, output_format="json"
):
    """
    Loads a saved model, assigns cluster labels to the input data and saves the dataframe as a csv or json file.

    Example
    -------
    >>> clusters = assign_cluster_labels('cluster_model')

    saved_model: str
      Path to saved model. Exclude the `.pkl` extension here.

    save_output: boolean, defaul=True
      Saves output

    file_name: str, default=None
      File name for the output. By default, it'll use the same name as 'saved_model`. Ignored if save_output=False.

    output_format: str, default='json'
      Choose the output format to save the resulting dataframe as either a csv or json file. Ignored if save_output=False.

      returns: dataframe with cluster labels assigned to input data
    """

    # load saved model
    from pycaret.clustering import load_model

    saved_kmeans = load_model(saved_model)

    # assign labels
    from pycaret.clustering import assign_model

    kmeans_df = assign_model(saved_kmeans)

    if save_output:

        # from datetime import date

        if file_name is None:
            file_name = saved_model

        if output_format == "json":
            return kmeans_df.to_json(f"{file_name}.json")
        if output_format == "csv":
            return kmeans_df.to_csv(f"{file_name}.csv", index=False)

    else:
        return kmeans_df


#### API wrapper ####
def save_to_disk(uploaded_file):
    """
    Saves the uploaded file to disk since for whatever reason FileUlpload doesn't work consitently.
    """
    with open(uploaded_file.filename, "wb") as buffer:
        shutil.copyfileobj(uploaded_file.file, buffer)


app = FastAPI(
    title="Example code for NameError issue",
    description="```NameError: name '_all_models_internal' is not defined``` is what I get",
)


def save_to_disk(uploaded_file):
    """
    Saves the uploaded file to disk since for whatever reason FileUlpload only works properly in temp storage in `clustering`.
    """
    with open(uploaded_file.filename, "wb") as buffer:
        shutil.copyfileobj(uploaded_file.file, buffer)


@app.get("/", response_class=PlainTextResponse)
async def running():
    note = """
The API is running

Note: add "/docs" to the url to get the swagger ui docs, press try and upload the test file (trained model)
  """
    return note


@app.post("/assign-label/")
def assign_labels(
    saved_model: UploadFile = File(...),
    file_name: str = Form(None),
    output_format: str = Form("json"),
):

    save_to_disk(saved_model)

    assign_cluster_labels(
        saved_model=saved_model.filename.replace(
            ".pkl", ""
        ),  # remove the ".pkl" from the filepath since pycaret automatically adds a ".pkl" to the filename
        save_output=True,
        file_name=file_name,
        output_format=output_format,
    )

    if file_name is None:
        file_name = saved_model.filename.replace(".pkl", "")

    if output_format == "json":
        cluster_labels = f"{file_name}.json"
    if output_format == "csv":
        cluster_labels = f"{file_name}.csv"

    return FileResponse(cluster_labels)
```

**Comment by sagarnildass** [comment]
@batmanscode : Can you try running the app without the --reload option? I vaguely remember this parameter giving me funky errors.

**Comment by batmanscode** [comment]
> @batmanscode : Can you try running the app without the --reload option? I vaguely remember this parameter giving me funky errors.

Oh interesting. That's a good idea, will try that. Thanks!

**Comment by batmanscode** [comment]
@sagarnildass got the same error :( thanks for the suggestion

**Comment by batmanscode** [comment]
@Yard1 should I create a new issue for this?
