### ISSUE TITLE
Numba Assertion Error When plot_model(iforest,plot='umap')

### ISSUE THREAD

**Issue by bernard778** [pycaret/pycaret#1122]
I am running the Anomaly Detection 101 tutorial (www.pycaret.org/tutorials/html/ANO101.html)
Windows 10 19042.867
Python 3.7.10 (default, Feb 26 2021, 13:06:18) [MSC v.1916 64 bit (AMD64)]
Pycaret 2.3.0
Numba 0.53.0

At section 9.2 Uniform Manifold Approximation and Projection, I receive the following numba assertion error:

`AssertionError: Storing i64 to ptr of i32 ('dim'). FE type int32`

I performed a conda update numba to ensure that I was on the most recent version. Do you have any suggestions?
Full trace is as follows:

```
>>> plot_model(iforest,plot='umap')
IntProgress(value=0, description='Processing: ', max=5)
Traceback (most recent call last):
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\errors.py", line 744, in new_error_context
    yield
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\lowering.py", line 328, in lower_inst
    self.storevar(val, inst.target.name)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\lowering.py", line 1278, in storevar
    raise AssertionError(msg)
AssertionError: Storing i64 to ptr of i32 ('dim'). FE type int32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\berna\Miniconda3\lib\site-packages\pycaret\anomaly.py", line 615, in plot_model
    model, plot=plot, feature_name=feature, label=label, scale=scale, save=save
  File "C:\Users\berna\Miniconda3\lib\site-packages\pycaret\internal\tabular.py", line 7163, in plot_model
    ret = locals()[plot]()
  File "C:\Users\berna\Miniconda3\lib\site-packages\pycaret\internal\tabular.py", line 5972, in umap
    import umap
  File "C:\Users\berna\Miniconda3\lib\site-packages\umap\__init__.py", line 1, in <module>
    from .umap_ import UMAP
  File "C:\Users\berna\Miniconda3\lib\site-packages\umap\umap_.py", line 54, in <module>
    from umap.layouts import (
  File "C:\Users\berna\Miniconda3\lib\site-packages\umap\layouts.py", line 36, in <module>
    "dim": numba.types.int32,
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\decorators.py", line 221, in wrapper
    disp.compile(sig)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\dispatcher.py", line 909, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\dispatcher.py", line 79, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\dispatcher.py", line 93, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\dispatcher.py", line 111, in _compile_core
    pipeline_class=self.pipeline_class)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\compiler.py", line 606, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\compiler.py", line 353, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\compiler.py", line 415, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\compiler.py", line 395, in _compile_core
    raise e
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\compiler.py", line 386, in _compile_core
    pm.run(self.state)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\compiler_machinery.py", line 339, in run
    raise patched_exception
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\typed_passes.py", line 463, in run_pass
    NativeLowering().run_pass(state)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\typed_passes.py", line 384, in run_pass
    lower.lower()
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "C:\Users\berna\Miniconda3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\berna\Miniconda3\lib\site-packages\numba\core\errors.py", line 751, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
←[1m←[1mStoring i64 to ptr of i32 ('dim'). FE type int32
←[1m
File "..\..\Miniconda3\lib\site-packages\umap\layouts.py", line 52:←[0m
←[1mdef rdist(x, y):
    <source elided>
    result = 0.0
←[1m    dim = x.shape[0]
←[0m    ←[1m^←[0m←[0m
←[0m
←[0m←[1mDuring: lowering "dim = static_getitem(value=$8load_attr.2, index=0, index_var=$const10.3, fn=<built-in function getitem>)" at C:\Users\berna\Miniconda3\lib\site-packages\umap\layouts.py (52)←[0m
```

**Comment by pycaret** [comment]
@bernard778 Can you check if you still get this issue with pycaret==2.3.1. If yes, can you upload the logs file here for us to look into?

Most likely it will be an issue with `umap-learn`. 

Thanks
