### ISSUE TITLE
Power BI issue with Pycaret

### ISSUE THREAD

**Issue by Anastassiiaa** [pycaret/pycaret#128]
Hi!
I've tried once to execute python script with dataset from you Medium article, it was Ok.
But right now I'm facing an issue:
DataSource.Error: ADO.NET: Python script error.
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 14, in <module>
    dataset = get_clusters(data = dataset)
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\pycaret\clustering.py", line 3228, in get_clusters
    from pycaret import preprocess
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\pycaret\preprocess.py", line 8, in <module>
    import ipywidgets as wg 
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\ipywidgets\__init__.py", line 25, in <module>
    from .widgets import *
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\ipywidgets\widgets\__init__.py", line 4, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\ipywidgets\widgets\widget.py", line 18, in <module>
    from ipykernel.comm import Comm
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.

Details:
    DataSourceKind=Python
    DataSourcePath=Python
    Message=Python script error.
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 14, in <module>
    dataset = get_clusters(data = dataset)
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\pycaret\clustering.py", line 3228, in get_clusters
    from pycaret import preprocess
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\pycaret\preprocess.py", line 8, in <module>
    import ipywidgets as wg 
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\ipywidgets\__init__.py", line 25, in <module>
    from .widgets import *
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\ipywidgets\widgets\__init__.py", line 4, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization
  File "C:\Users\uaSemeniAn1\AppData\Local\Continuum\Anaconda3\envs\myenv\lib\site-packages\ipywidgets\widgets\widget.py...
    ErrorCode=-2147467259
    ExceptionType=Microsoft.PowerBI.Scripting.Python.Exceptions.PythonScriptRuntimeException

Please help to resolve this issue.
Thank you!

**Comment by pycaret** [comment]
@Anastassiiaa Can you please confirm your OS details, Power BI version (64 or 32 bit) etc?

**Comment by Anastassiiaa** [comment]
64 bit version

**Comment by faibercalderon** [comment]
I have the same problem!

**Comment by faibercalderon** [comment]
When I charge the csv file, My powerBI change de data type automatically but if I see, the data have 
a dot as a decimal separator, but in order for power bi to recognize it, I must replace the dot with commas before changing the data type.

worked perfectly for me.

tell me how it goes

**Comment by alof0l** [comment]
I have the same problem, installed pycaret though anaconda in a 3.6 and 3.7 python env. Neither worked. I also resinstalled PowerBi x64 and did applied the .csv recommendation.

**Comment by Anastassiiaa** [comment]
Hello! Nope, it doesn't work:
= Csv.Document(Web.Contents("https://raw.githubusercontent.com/pycaret/pycaret/master/datasets/jewellery.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None])
 
On the first step, csv is loaded with delimiter ",".

**Comment by vandermoerDOTcom** [comment]
@Anastassiiaa
@faibercalderon 
@alof0l 

I run in to the same issues.

For error ErrorCode=-2147467259 with Clustering in Power BI you have to go to power query  Transform tab and select Promoted Headers and not Changed Type  apply the python code  click on Table  click Close & Apply and it will work properly.

Anomaly Detection in Power BI get the data from the web and go to power query and select Transform tab. At the applied steps you see a cross before Changed Type. Click on the cross so you can see the right data and select Promoted Headers. Run the python code and click on Table. Remove Changed Type by clicking on the cross. Select columns Col1 till Col10 and click on Replace Values and replace the . with , and change the columns with Data Type to Decimal Number. Go to the home tab and click Close & Apply.

Have a nice day :)

@pycaret

Just tried the first two items with power bi, Clustering and Anomaly Detection and it is awesome stuff that makes me smile. The others items I will try soon and if I run into any issues ill let you know.

Kind Regards

**Comment by alof0l** [comment]
@Anastassiiaa Finally it worked for me! 

Anaconda and Python were not configured in my System Path. 

To do that, I could suggest one of the following:

1. Uninstall / install anaconda. Make sure you do 2 things: execute the installer with "admini privileges" right click for it AND check "Add Anaconda to my environment path variable", even if it says it is not recommended (you could change that later)

OR 

2. From Anaconda prompt, execute 
`where conda`
`where python`
copy links into your environment path variables. 

Restart your computer. Delete the power query "run python script" create the step again.

**Comment by pycaret** [comment]
@Anastassiiaa Can you confirm if the issues has been resolved?

**Comment by lucazav** [comment]
The short answer is that the solution is launching the Power BI Desktop executable from the Anaconda Prompt after activating the environment in which you want to run the Python script.

The long one is described in this [blog post](https://medium.com/microsoftazure/fixing-ado-net-error-trying-to-run-python-script-in-power-bi-83e4b98cba8d).
