### ISSUE TITLE
[BUG] Install lightgbm GPU

### ISSUE THREAD

**Issue by StatsAI** [pycaret/pycaret#1292]
**Describe the bug**

Bug when trying to install GPU version of LightGBM. I followed these instructions

# create a conda environment
conda create --name yourenvname python=3.6

# install the full version of pycaret
pip install pycaret[full]

# uninstall lightgbm CPU
pip uninstall lightgbm -y

# install lightgbm GPU
pip install lightgbm --install-option=--gpu --install-option="--opencl-include-dir=/usr/local/cuda/include/" --install-option="--opencl-library=/usr/local/cuda/lib64/libOpenCL.so"

**To Reproduce**

```python
(test_env) C:\Users\deepl>pip install lightgbm --install-option=--gpu --install-option="--opencl-include-dir=/usr/local/cuda/include/" --install-option="--opencl-library=/usr/local/cuda/lib64/libOpenCL.so"
C:\Users\deepl\anaconda3\envs\test_env\lib\site-packages\pip\_internal\commands\install.py:232: UserWarning: Disabling all use of wheels due to the use of --build-option / --global-option / --install-option.
  cmdoptions.check_install_build_global(options)
Collecting lightgbm
  Using cached lightgbm-3.2.1.tar.gz (1.5 MB)
Requirement already satisfied: wheel in c:\users\deepl\anaconda3\envs\test_env\lib\site-packages (from lightgbm) (0.36.2)
Requirement already satisfied: numpy in c:\users\deepl\anaconda3\envs\test_env\lib\site-packages (from lightgbm) (1.19.5)
Requirement already satisfied: scipy in c:\users\deepl\anaconda3\envs\test_env\lib\site-packages (from lightgbm) (1.5.4)
Requirement already satisfied: scikit-learn!=0.22.0 in c:\users\deepl\anaconda3\envs\test_env\lib\site-packages (from lightgbm) (0.23.2)
Requirement already satisfied: joblib>=0.11 in c:\users\deepl\anaconda3\envs\test_env\lib\site-packages (from scikit-learn!=0.22.0->lightgbm) (1.0.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\deepl\anaconda3\envs\test_env\lib\site-packages (from scikit-learn!=0.22.0->lightgbm) (2.1.0)
Skipping wheel build for lightgbm, due to binaries being disabled for it.
Installing collected packages: lightgbm
    Running setup.py install for lightgbm ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\deepl\anaconda3\envs\test_env\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\deepl\\AppData\\Local\\Temp\\pip-install-4vyc9sx4\\lightgbm_52fa475b4cc744bb9d8b3f28b20d1790\\setup.py'"'"'; __file__='"'"'C:\\Users\\deepl\\AppData\\Local\\Temp\\pip-install-4vyc9sx4\\lightgbm_52fa475b4cc744bb9d8b3f28b20d1790\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\deepl\AppData\Local\Temp\pip-record-gki28aah\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\deepl\anaconda3\envs\test_env\Include\lightgbm' --gpu --opencl-include-dir=/usr/local/cuda/include/ --opencl-library=/usr/local/cuda/lib64/libOpenCL.so
         cwd: C:\Users\deepl\AppData\Local\Temp\pip-install-4vyc9sx4\lightgbm_52fa475b4cc744bb9d8b3f28b20d1790\
    Complete output (23 lines):
    running install
    INFO:LightGBM:Starting to compile the library.
    INFO:LightGBM:Starting to compile with Visual Studio 16 2019 (x64).
    INFO:LightGBM:Starting to compile with Visual Studio 15 2017 (x64).
    INFO:LightGBM:Starting to compile with Visual Studio 14 2015 (x64).
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\deepl\AppData\Local\Temp\pip-install-4vyc9sx4\lightgbm_52fa475b4cc744bb9d8b3f28b20d1790\setup.py", line 379, in <module>
        'Topic :: Scientific/Engineering :: Artificial Intelligence'])
      File "C:\Users\deepl\anaconda3\envs\test_env\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "C:\Users\deepl\anaconda3\envs\test_env\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\deepl\anaconda3\envs\test_env\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\deepl\anaconda3\envs\test_env\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\deepl\AppData\Local\Temp\pip-install-4vyc9sx4\lightgbm_52fa475b4cc744bb9d8b3f28b20d1790\setup.py", line 253, in run
        nomp=self.nomp, bit32=self.bit32, integrated_opencl=self.integrated_opencl)
      File "C:\Users\deepl\AppData\Local\Temp\pip-install-4vyc9sx4\lightgbm_52fa475b4cc744bb9d8b3f28b20d1790\setup.py", line 194, in compile_cpp
        LOG_NOTICE)))
    Exception: Please install Visual Studio or MS Build and all required dependencies first
    The full version of error log was saved into C:\Users\deepl\LightGBM_compilation.log
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\deepl\anaconda3\envs\test_env\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\deepl\\AppData\\Local\\Temp\\pip-install-4vyc9sx4\\lightgbm_52fa475b4cc744bb9d8b3f28b20d1790\\setup.py'"'"'; __file__='"'"'C:\\Users\\deepl\\AppData\\Local\\Temp\\pip-install-4vyc9sx4\\lightgbm_52fa475b4cc744bb9d8b3f28b20d1790\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\deepl\AppData\Local\Temp\pip-record-gki28aah\install-record.txt' --single-version-externally-managed --compile --install-headers 'C:\Users\deepl\anaconda3\envs\test_env\Include\lightgbm' --gpu --opencl-include-dir=/usr/local/cuda/include/ --opencl-library=/usr/local/cuda/lib64/libOpenCL.so Check the logs for full command output.

**Expected behavior**
<!--
A clear and concise description of what you expected to happen.
-->

**Additional context**
<!--
Add any other context about the problem here.
-->

**Versions**
<details>

<!--
Please run the following code snippet and paste the output here:
 
import pycaret
pycaret.__version__
-->

</details>

<!-- Thanks for contributing! -->

**Comment by StatsAI** [comment]
Visual Studio Build Tools 2019 was already installed.
I installed Visual Studio Community 2019 and still get the same error when trying to install

**Comment by StatsAI** [comment]
It appears this is a LightGBM dependency issue. Apparently, you need a lot more dependencies to install it on Windows 10. 

https://github.com/microsoft/LightGBM/blob/master/docs/GPU-Windows.rst
https://stackoverflow.com/questions/57412261/how-can-i-solve-problem-with-installing-lightgbm-gpu-on-windows-10

**Comment by Yard1** [comment]
Yeah, unfortunately we can't really do anything about that. I'll close it as it's not related to PyCaret.
