### ISSUE TITLE
Queue empty error arsing

### ISSUE THREAD

**Issue by SuhanC** [pycaret/pycaret#1376]
Hello, 

I'm using pycaret for couple of month, 
and I'm facing this error for the first time.

I'm using automl() for classification, and I'm comparing top 3 models following your tutorials.
It's about empty queues in your parallel.py script.

I'm including my errors in this issue.

Thank you!

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 88 concurrent workers.
[Parallel(n_jobs=-1)]: Done  28 out of  50 | elapsed:    6.9s remaining:    5.4s
  0%|          | 0/406 [04:12<?, ?it/s]
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/parallel.py", line 820, in dispatch_one_batch
    tasks = self._ready_batches.get(block=False)
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/queue.py", line 161, in get
    raise Empty
queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 560, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer)
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 607, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/metrics/_scorer.py", line 88, in __call__
    *args, **kwargs)
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/metrics/_scorer.py", line 206, in _score
    y_pred = method_caller(estimator, "predict", X)
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/metrics/_scorer.py", line 53, in _cached_call
    return getattr(estimator, method)(*args, **kwargs)
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/pycaret/internal/pipeline.py", line 114, in predict
    result = super().predict(X, **predict_params)
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/utils/metaestimators.py", line 119, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/pipeline.py", line 408, in predict
    return self.steps[-1][-1].predict(Xt, **predict_params)
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/_forest.py", line 629, in predict
    proba = self.predict_proba(X)
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/ensemble/_forest.py", line 686, in predict_proba
    for e in self.estimators_)
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/home/suhan/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/parallel.py", line 831, in dispatch_one_batch
    islice = list(itertools.islice(iterator, big_batch_size))
ValueError: Stop argument for islice() must be None or an integer: 0 <= x <= sys.maxsize.
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-23-c519eb900233> in <module>
----> 1 saveML_automl_topmerge_two(All_shorten_005,0.05,'Shorten')
      2 saveML_automl_topmerge_two(All_shorten_1,1,'Shorten')
      3 

<ipython-input-22-eae1ebdf285b> in saveML_automl_topmerge_two(df, P, contribution, cptac_merged_phen)
     26 
     27             compare_models(n_select = 3,fold=5,verbose=False,exclude = ['knn','ada']) #,include=['lda','lr','qda'],,
---> 28             best = tune_model(automl(optimize = 'AUC',use_holdout=False))
     29 
     30             df_ML_result = predict_model(best,verbose=False)

~/anaconda3/envs/ml/lib/python3.6/site-packages/pycaret/classification.py in tune_model(estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_library, search_algorithm, early_stopping, early_stopping_max_iters, choose_better, fit_kwargs, groups, return_tuner, verbose, tuner_verbose, **kwargs)
   1100         verbose=verbose,
   1101         tuner_verbose=tuner_verbose,
-> 1102         **kwargs,
   1103     )
   1104 

~/anaconda3/envs/ml/lib/python3.6/site-packages/pycaret/internal/tabular.py in tune_model_supervised(estimator, fold, round, n_iter, custom_grid, optimize, custom_scorer, search_library, search_algorithm, early_stopping, early_stopping_max_iters, choose_better, fit_kwargs, groups, return_tuner, verbose, tuner_verbose, display, **kwargs)
   4478                 pycaret.internal.patches.sklearn._mp_ParameterGrid_getitem,
   4479             ):
-> 4480                 model_grid.fit(X_train, y_train, groups=groups, **fit_kwargs)
   4481         else:
   4482             model_grid.fit(X_train, y_train, groups=groups, **fit_kwargs)

~/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

~/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/model_selection/_search.py in fit(self, X, y, groups, **fit_params)
    734                 return results
    735 
--> 736             self._run_search(evaluate_candidates)
    737 
    738         # For multi-metric evaluation, store the best_index_, best_params_ and

~/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/model_selection/_search.py in _run_search(self, evaluate_candidates)
   1529         evaluate_candidates(ParameterSampler(
   1530             self.param_distributions, self.n_iter,
-> 1531             random_state=self.random_state))

~/anaconda3/envs/ml/lib/python3.6/site-packages/sklearn/model_selection/_search.py in evaluate_candidates(candidate_params)
    713                                for parameters, (train, test)
    714                                in product(candidate_params,
--> 715                                           cv.split(X, y, groups)))
    716 
    717                 if len(out) < 1:

~/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/parallel.py in __call__(self, iterable)
   1052 
   1053             with self._backend.retrieval_context():
-> 1054                 self.retrieve()
   1055             # Make sure that we get a last message telling us we are done
   1056             elapsed_time = time.time() - self._start_time

~/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/parallel.py in retrieve(self)
    931             try:
    932                 if getattr(self._backend, 'supports_timeout', False):
--> 933                     self._output.extend(job.get(timeout=self.timeout))
    934                 else:
    935                     self._output.extend(job.get())

~/anaconda3/envs/ml/lib/python3.6/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    540         AsyncResults.get from multiprocessing."""
    541         try:
--> 542             return future.result(timeout=timeout)
    543         except CfTimeoutError as e:
    544             raise TimeoutError from e

~/anaconda3/envs/ml/lib/python3.6/concurrent/futures/_base.py in result(self, timeout)
    423                 raise CancelledError()
    424             elif self._state == FINISHED:
--> 425                 return self.__get_result()
    426 
    427             self._condition.wait(timeout)

~/anaconda3/envs/ml/lib/python3.6/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

ValueError: Stop argument for islice() must be None or an integer: 0 <= x <= sys.maxsize.

**Comment by Yard1** [comment]
Can you try running it with `n_jobs=1` in `setup`?

**Comment by SuhanC** [comment]
Thank you! Solved.
