### ISSUE TITLE
Load_Model On AWS Platform by defining S3 bucket and path

### ISSUE THREAD

**Issue by yelizkilinc** [pycaret/pycaret#1801]
**Describe the bug**
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found

Evenif I have the file under related s3 path, I can not upload_model. It is giving above error.

Traceback (most recent call last):
  File "/opt/ml/processing/input/code/test_model.py", line 56, in <module>
    model = load_model('FinalModel', platform = 'aws', authentication = {'bucket' : bucket_name, 'path':directory_name}, verbose=True)
  File "/usr/local/lib/python3.8/dist-packages/pycaret/regression.py", line 1988, in load_model
    return pycaret.internal.tabular.load_model(
  File "/usr/local/lib/python3.8/dist-packages/pycaret/internal/tabular.py", line 9297, in load_model
    return pycaret.internal.persistence.load_model(
  File "/usr/local/lib/python3.8/dist-packages/pycaret/internal/persistence.py", line 422, in load_model
    s3.Bucket(bucketname).download_file(filename, filename)
  File "/usr/local/lib/python3.8/dist-packages/boto3/s3/inject.py", line 245, in bucket_download_file
    return self.meta.client.download_file(
  File "/usr/local/lib/python3.8/dist-packages/boto3/s3/inject.py", line 171, in download_file
    return transfer.download_file(
  File "/usr/local/lib/python3.8/dist-packages/boto3/s3/transfer.py", line 315, in download_file
    future.result()
  File "/usr/local/lib/python3.8/dist-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/local/lib/python3.8/dist-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/usr/local/lib/python3.8/dist-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/s3transfer/download.py", line 340, in _submit
    response = client.head_object(
  File "/usr/local/lib/python3.8/dist-packages/botocore/client.py", line 388, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/dist-packages/botocore/client.py", line 708, in _make_api_call
    raise error_class(parsed_response, operation_name)

**To Reproduce**
I deployed the model under S3 bucket and I can see my model in the related path. But I can not load_model and use it.

```python
model = load_model("FinalModel", platform = 'aws', authentication = {'bucket' : bucketname, 'path':directoryname}, verbose=True)

```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by moezali1** [comment]
@wkuopt Can you please look into this one? I remember you worked on AWS PR in past as well.
