### ISSUE TITLE
[BUG] When using assign_model from clustering via FastAPI - NameError: name '_all_models_internal' is not defined

### ISSUE THREAD

**Issue by batmanscode** [pycaret/pycaret#1803]
**Describe the bug**
I get this error when using it as an API via FastAPI in the function that calls `assign_labels` from `clustering` after loading a saved model

Error: `NameError: name '_all_models_internal' is not defined`

**To Reproduce**
Save `pycaret_test.py`, install the requirements and `uvicorn pycaret_test:app --reload` in the terminal and optionally you can set `--host 0.0.0.0 --port 8080` if you need to

Once you run the uvicorn command:
* A link should open in localhost
* Add "/docs" to the end of the URL
* Click **assign-label**
* Press the **"Try it out"** button
* Upload a Pycaret clustering model (`.pkl`) to the `saved_model` parameter
* Press **"Execute**""

You will get `Error: response status is 500` in the docs and you will see the `NameError` back in the terminal

*requirements.txt*
```
pycaret
uvicorn[standard]
fastapi
python-multipart
```

*pycaret_test.py*
```python
import shutil
from datetime import date
from fastapi import FastAPI, File, Query, UploadFile, HTTPException, Form
from fastapi.responses import FileResponse, PlainTextResponse


#### cluster labels ####


def assign_cluster_labels(
    saved_model, save_output=True, file_name=None, output_format="json"
):
    """
    Loads a saved model, assigns cluster labels to the input data and saves the dataframe as a csv or json file.

    Example
    -------
    >>> clusters = assign_cluster_labels('cluster_model')

    saved_model: str
      Path to saved model. Exclude the `.pkl` extension here.

    save_output: boolean, defaul=True
      Saves output

    file_name: str, default=None
      File name for the output. By default, it'll use the same name as 'saved_model`. Ignored if save_output=False.

    output_format: str, default='json'
      Choose the output format to save the resulting dataframe as either a csv or json file. Ignored if save_output=False.

      returns: dataframe with cluster labels assigned to input data
    """

    # load saved model
    from pycaret.clustering import load_model

    saved_kmeans = load_model(saved_model)

    # assign labels
    from pycaret.clustering import assign_model

    kmeans_df = assign_model(saved_kmeans)

    if save_output:

        # from datetime import date

        if file_name is None:
            file_name = saved_model

        if output_format == "json":
            return kmeans_df.to_json(f"{file_name}.json")
        if output_format == "csv":
            return kmeans_df.to_csv(f"{file_name}.csv", index=False)

    else:
        return kmeans_df


#### API wrapper ####
def save_to_disk(uploaded_file):
    """
    Saves the uploaded file to disk since for whatever reason FileUlpload doesn't work consitently.
    """
    with open(uploaded_file.filename, "wb") as buffer:
        shutil.copyfileobj(uploaded_file.file, buffer)


app = FastAPI(
    title="Example code for NameError issue",
    description="```NameError: name '_all_models_internal' is not defined``` is what I get",
)


def save_to_disk(uploaded_file):
    """
    Saves the uploaded file to disk since for whatever reason FileUlpload doesn't work consistently. 
    """
    with open(uploaded_file.filename, "wb") as buffer:
        shutil.copyfileobj(uploaded_file.file, buffer)


@app.get("/", response_class=PlainTextResponse)
async def running():
    note = """
The API is running

Note: add "/docs" to the url to get the swagger ui docs, press try and upload the test file (trained model)
  """
    return note


@app.post("/assign-label/")
def assign_labels(
    saved_model: UploadFile = File(...),
    file_name: str = Form(None),
    output_format: str = Form("json"),
):

    save_to_disk(saved_model)

    assign_cluster_labels(
        saved_model=saved_model.filename.replace(
            ".pkl", ""
        ),  # remove the ".pkl" from the filepath since pycaret automatically adds a ".pkl" to the filename
        save_output=True,
        file_name=file_name,
        output_format=output_format,
    )

    if file_name is None:
        file_name = saved_model.filename.replace(".pkl", "")

    if output_format == "json":
        cluster_labels = f"{file_name}.json"
    if output_format == "csv":
        cluster_labels = f"{file_name}.csv"

    return FileResponse(cluster_labels)

```

**Expected behavior**
Return a dataframe with the labels

**Additional context**
* There was a similar problem in #1052
* Full traceback:
```
Traceback (most recent call last):
  File "/root/venv/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 375, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/root/venv/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/root/venv/lib/python3.7/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/root/venv/lib/python3.7/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/root/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/root/venv/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/root/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/root/venv/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/root/venv/lib/python3.7/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/root/venv/lib/python3.7/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/root/venv/lib/python3.7/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/root/venv/lib/python3.7/site-packages/fastapi/routing.py", line 227, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/root/venv/lib/python3.7/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/root/venv/lib/python3.7/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/root/venv/lib/python3.7/site-packages/anyio/to_thread.py", line 29, in run_sync
    limiter=limiter)
  File "/root/venv/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 805, in run_sync_in_worker_thread
    return await future
  File "/root/venv/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 743, in run
    result = func(*args)
  File "./pycaret_test.py", line 109, in assign_labels
    output_format=output_format,
  File "./pycaret_test.py", line 43, in assign_cluster_labels
    kmeans_df = assign_model(saved_kmeans)
  File "/root/venv/lib/python3.7/site-packages/pycaret/clustering.py", line 585, in assign_model
    model, transformation=transformation, verbose=verbose
  File "/root/venv/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 8407, in assign_model
    name = _get_model_name(model)
  File "/root/venv/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 10151, in _get_model_name
    models = _all_models_internal
NameError: name '_all_models_internal' is not defined
```

**Versions**
<details>

pycaret == 2.3.4
fastapi == 0.70.0
</details>

**Comment by wkuopt** [comment]
The error occurs at line 43, where assign_model() is called after the model is loaded. I don't think this would work as assign_model() needs the data that's passed to the setup function. Since the pickle file only contains the transformation pipeline and the trained model, assign_model() will not work in this scenario.
