### ISSUE TITLE
error loading >> get_data('juice') in powerBI

### ISSUE THREAD

**Issue by rijesh123** [pycaret/pycaret#200]
# 'dataset' holds the input data for this script
from pycaret.datasets import get_data
data = get_data('juice')

error:
Details: "ADO.NET: Python script error.
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 12, in <module>
    data = get_data('juice')
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\pycaret\datasets.py", line 58, in get_data
    data = pd.read_csv(complete_address)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\pandas\io\parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\pandas\io\parsers.py", line 430, in _read
    fp_or_buf, _, compression, should_close = get_filepath_or_buffer(
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\pandas\io\common.py", line 172, in get_filepath_or_buffer
    req = urlopen(filepath_or_buffer)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\site-packages\pandas\io\common.py", line 141, in urlopen
    return urllib.request.urlopen(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\urllib\request.py", line 547, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\envs\myenv\lib\urllib\request.py", line 1421, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
"

**Comment by pycaret** [comment]
@rijesh123 Hi Rijesh,

Which environment are you running this function in? It seems to me you are using get_data within PowerBI. 

Thanks

**Comment by rijesh123** [comment]
@pycaret Thank you.
Yes, I am using that code in PowerBI
How can i proceed further?.

**Comment by rijesh123** [comment]
Ignore my error reported. It is not valid
