### ISSUE TITLE
[BUG] ValueError: could not broadcast input array from shape (169,1) into shape (169,)

### ISSUE THREAD

**Issue by jmrichardson** [pycaret/pycaret#2014]
Using classification and blend_models, including catboost gives the following error (works without catboost):

```
Traceback (most recent call last):
  File "D:\Anaconda3\envs\aim\lib\site-packages\IPython\core\interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-60-d1921fd94a00>", line 1, in <module>
    model = blend_models(estimator_list=el)
  File "D:\Anaconda3\envs\aim\lib\site-packages\pycaret\classification.py", line 1330, in blend_models
    return pycaret.internal.tabular.blend_models(
  File "D:\Anaconda3\envs\aim\lib\site-packages\pycaret\internal\tabular.py", line 5292, in blend_models
    model, model_fit_time = create_model_supervised(
  File "D:\Anaconda3\envs\aim\lib\site-packages\pycaret\internal\tabular.py", line 3167, in create_model_supervised
    scores = cross_validate(
  File "D:\Anaconda3\envs\aim\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "D:\Anaconda3\envs\aim\lib\site-packages\sklearn\model_selection\_validation.py", line 242, in cross_validate
    scores = parallel(
  File "D:\Anaconda3\envs\aim\lib\site-packages\joblib\parallel.py", line 1054, in __call__
    self.retrieve()
  File "D:\Anaconda3\envs\aim\lib\site-packages\joblib\parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "D:\Anaconda3\envs\aim\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "D:\Anaconda3\envs\aim\lib\concurrent\futures\_base.py", line 437, in result
    return self.__get_result()
  File "D:\Anaconda3\envs\aim\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
ValueError: could not broadcast input array from shape (169,1) into shape (169,)
```

here is the code:

```
            self.config = dict_of(
            data=train,
            test_data=test,
            target='target',
            normalize=True,
            transformation=False,
            remove_multicollinearity=True,
            data_split_shuffle=False,
            # remove_outliers: True,
            log_experiment=True,
            experiment_name=self.name,
            log_plots=True,
            log_profile=False,
            log_data=False,
            fold_strategy=PyCaretGapKFoldCV(X_index=train.index, n_splits=3),
            verbose=False,
            silent=True)

            self.config['fix_imbalance'] = True
            exp = setup(**self.config)
            el.append(create_model('lr', verbose=False))
            el.append(create_model('nb', verbose=False))
            el.append(create_model('gpc', verbose=False))
            el.append(create_model('ridge', verbose=False))
            el.append(create_model('gbc', verbose=False))
            el.append(create_model('lda', verbose=False))
            el.append(create_model('rbfsvm', verbose=False))
            el.append(create_model('qda', verbose=False))
            el.append(create_model('mlp', verbose=False))
            el.append(create_model('et', verbose=False))
            el.append(create_model('ada', verbose=False))
            el.append(create_model('rf', verbose=False))
            el.append(create_model('lightgbm', verbose=False))
            el.append(create_model('xgboost', verbose=False))
            el.append(create_model('dt', verbose=False))
            el.append(create_model('knn', verbose=False))
            el.append(create_model('svm', verbose=False))
            el.append(create_model('catboost', allow_writing_files=False, verbose=False))

            model = blend_models(estimator_list=el)

```

Pycaret Version: 2.3.5

**Comment by moezali1** [comment]
@jmrichardson Can you try updating the version of catboost?

**Comment by moezali1** [comment]
Closing as part of the 4.0 backlog cleanup — see #4177.

PyCaret 4.0 is a ground-up rewrite (OOP-only API, sklearn-native engine, Python 3.11+, sklearn ≥ 1.7) and almost all pre-4.0 issues either reference removed APIs (`setup()`, `plot_model`, `evaluate_model`, `interpret_model`, `automl`, the legacy time-series module, the Streamlit dashboard, …) or no longer reproduce on the new code path.

**If this still affects you in 4.0, please re-file as a new issue** with:

- the experiment constructor call (`Experiment(...)`),
- the operation that fails,
- the full traceback,
- your Python / sklearn / pycaret versions.

Resources for 4.0:

- Docs: https://pycaret.org/docs
- Migrate from 3.x: https://pycaret.org/docs/guides/migrating-from-3-x
- API reference: https://pycaret.org/reference
- FAQ: https://pycaret.org/docs/resources/faqs

Thanks for filing — and apologies for the long latency. The repo had drifted; we're starting clean.
