### ISSUE TITLE
[BUG] Problem within the SOD model in pycaret.anomaly

### ISSUE THREAD

**Issue by carlok** [pycaret/pycaret#2025]
Hi,
thanks for your work.
I tested all the algorithms in `anomaly` and they are fine but it seems that `SOD` has an issue, both creating/assigning it and predicting with it.
When I simply create/assign it with something like:

```python
s = setup(data, session_id = 123, silent=True)
model_current = create_model('sod')
model_results = assign_model(model_current)
save_model(model_current, 'model_sod')
```

it emits

```
OMP: Info #271: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
```

which it seems due to a dependency package.

Then while I try to use the previously saved model with something like

```python
dt_saved = load_model('model_sod')
prediction = predict_model(dt_saved, data = data_unseen)
```

it raises

```
OMP: Info #271: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Traceback (most recent call last):
  File "pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "outlier_detector.py", line 31, in <module>
    prediction = predict_model(dt_saved, data = data_unseen)
  File "pycaret/anomaly.py", line 869, in predict_model
    return pycaret.internal.tabular.predict_model_unsupervised(
  File "pycaret/internal/tabular.py", line 8545, in predict_model_unsupervised
    pred = estimator.predict(data_transformed)
  File "sklearn/utils/metaestimators.py", line 119, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "sklearn/pipeline.py", line 408, in predict
    return self.steps[-1][-1].predict(Xt, **predict_params)
  File "pyod/models/base.py", line 167, in predict
    pred_score = self.decision_function(X)
  File "pyod/models/sod.py", line 157, in decision_function
    return self._sod(X)
  File "pyod/models/sod.py", line 187, in _sod
    obs = X[i]
  File "pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 0
```

**Comment by moezali1** [comment]
The error still exist. Last tested on 21/8/2022
