### ISSUE TITLE
pycaret Load model not  working  

### ISSUE THREAD

**Issue by akramIOT** [pycaret/pycaret#2261]
**Describe the bug**

(python ) (base) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % conda env list
# conda environments:
#
AKRAM_CODE_FOLDER        /Users/akram/.conda/envs/AKRAM_CODE_FOLDER
base                  *  /Users/akram/opt/anaconda3
pycaret_akram            /Users/akram/opt/anaconda3/envs/pycaret_akram

(python ) (base) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % conda activate pycaret_akram 
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % 
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % ls
FreeWifi                        Tutorials                       pycaret-streamlit-google        streamlit-sales-dashboard
Juice.py                        logs.log                        st_1.py                         test_st.py
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % 
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % ls
FreeWifi                        Tutorials                       logs.log                        st_1.py                         test_st.py
Juice.py                        deployment_28042020.pkl         pycaret-streamlit-google        streamlit-sales-dashboard
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % 
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % 
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % 
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % streamlit run test_st.py     
2022-03-09 17:30:43.866 INFO    numexpr.utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2022-03-09 17:30:43.866 INFO    numexpr.utils: NumExpr defaulting to 8 threads.

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.24.21.99:8501

2022-03-09 17:30:48.440 Initializing load_model()
2022-03-09 17:30:48.440 Initializing load_model()
2022-03-09 17:30:48.440 Initializing load_model()
2022-03-09 17:30:48.441 load_model(model_name=deployment_28042020, platform=None, authentication=None, verbose=True)
Transformation Pipeline and Model Successfully Loaded
2022-03-09 17:30:48.441 load_model(model_name=deployment_28042020, platform=None, authentication=None, verbose=True)
Transformation Pipeline and Model Successfully Loaded
2022-03-09 17:30:48.441 load_model(model_name=deployment_28042020, platform=None, authentication=None, verbose=True)
Transformation Pipeline and Model Successfully Loaded
2022-03-09 17:30:48.454 Traceback (most recent call last):
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/streamlit/script_runner.py", line 430, in _run_script
    exec(code, module.__dict__)
  File "/Users/akram/AKRAM_CODE_FOLDER/ML/Washington_ML/STREAMLIT_APPS/test_st.py", line 7, in <module>
    model = load_model('deployment_28042020')
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/pycaret/regression.py", line 1930, in load_model
    return pycaret.internal.tabular.load_model(
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/pycaret/internal/tabular.py", line 8939, in load_model
    return pycaret.internal.persistence.load_model(
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/pycaret/internal/persistence.py", line 373, in load_model
    return joblib.load(model_name)
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1579, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'pycaret.preprocess'

2022-03-09 17:30:48.454 Traceback (most recent call last):
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/streamlit/script_runner.py", line 430, in _run_script
    exec(code, module.__dict__)
  File "/Users/akram/AKRAM_CODE_FOLDER/ML/Washington_ML/STREAMLIT_APPS/test_st.py", line 7, in <module>
    model = load_model('deployment_28042020')
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/pycaret/regression.py", line 1930, in load_model
    return pycaret.internal.tabular.load_model(
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/pycaret/internal/tabular.py", line 8939, in load_model
    return pycaret.internal.persistence.load_model(
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/pycaret/internal/persistence.py", line 373, in load_model
    return joblib.load(model_name)
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1579, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'pycaret.preprocess'

2022-03-09 17:30:48.454 Traceback (most recent call last):

pycaret                   2.2.2

====================
CODE:

rom pycaret.regression import *
from pycaret.classification import predict_model
import streamlit as st
import pandas as pd
import numpy as np

model = load_model('deployment_28042020')

def predict(model, input_df):
    predictions_df = predict_model(estimator=model, data=input_df)
    predictions = predictions_df['Label'][0]
    return predictions

def run():

    add_selectbox = st.sidebar.selectbox(
        "How would you like to predict?",
        ("Online", "Batch"))

    st.sidebar.info('This app is created to predict patient hospital charges')
    st.sidebar.success('https://www.pycaret.org')
    st.sidebar.text("Akram is here")
    st.title("Insurance Charges Prediction App")

    if add_selectbox == 'Online':

        age = st.number_input('Age', min_value=1, max_value=100, value=25)
        sex = st.selectbox('Sex', ['male', 'female'])
        bmi = st.number_input('BMI', min_value=10, max_value=50, value=10)
        children = st.selectbox('Children', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
        if st.checkbox('Smoker'):
            smoker = 'yes'
        else:
            smoker = 'no'
        region = st.selectbox('Region', ['southwest', 'northwest', 'northeast', 'southeast'])
        output = ""

        input_dict = {'age': age, 'sex': sex, 'bmi': bmi, 'children': children, 'smoker': smoker, 'region': region}
        input_df = pd.DataFrame([input_dict])
        st.write(input_df.head())

        if st.button("Predict"):
            output = predict(model=model, input_df=input_df)
            output = '$' + str(output)
        st.success('The output is {}'.format(output))

    if add_selectbox == 'Batch':
        file_upload = st.file_uploader("Upload csv file for predictions", type=["csv"])
        if file_upload is not None:
            data = pd.read_csv(file_upload)
            predictions = predict_model(estimator=model, data=data)
            st.write(predictions)

if __name__ == '__main__':
    run()

**To Reproduce**

```python
<Paste your code here>
```

**Expected behavior**

**Additional context**

**Versions**
<details>

</details>

**Comment by moezali1** [comment]
@akramIOT Seems like you are using the old version of PyCaret and it is causing some conflict. Can you please ensure you are in a fresh environment with `pycaret==2.3.6`. Please let me know if you still get the same error. 

Thanks.
