### ISSUE TITLE
Problem with numba

### ISSUE THREAD

**Issue by tciric-tc** [pycaret/pycaret#23]
Hi everyone!
When I try to run script where I use pycaret classification module this thing happens:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3_all\envs\intelliq_risk\lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
**ImportError: DLL load failed: The specified module could not be found.**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/tamara.ciric/PycharmProjects/intelliq/model/risk/services/ml/pycaret_train.py", line 76, in <module>
    train(date=datetime(2019, 1, 1), sources=config.DATA_SOURCES)
  File "C:/Users/tamara.ciric/PycharmProjects/intelliq/model/risk/services/ml/pycaret_train.py", line 43, in train
    exp_clf = setup(X, target=config.Y)
  File "C:\ProgramData\Anaconda3_all\envs\intelliq_risk\lib\site-packages\pycaret\classification.py", line 880, in setup
    from pycaret import preprocess
  File "C:\ProgramData\Anaconda3_all\envs\intelliq_risk\lib\site-packages\pycaret\preprocess.py", line 26, in <module>
    from pyod.models.knn import KNN
  File "C:\ProgramData\Anaconda3_all\envs\intelliq_risk\lib\site-packages\pyod\__init__.py", line 4, in <module>
    from . import utils
  File "C:\ProgramData\Anaconda3_all\envs\intelliq_risk\lib\site-packages\pyod\utils\__init__.py", line 11, in <module>
    from .stat_models import pairwise_distances_no_broadcast
  File "C:\ProgramData\Anaconda3_all\envs\intelliq_risk\lib\site-packages\pyod\utils\stat_models.py", line 11, in <module>
    from numba import njit
  File "C:\ProgramData\Anaconda3_all\envs\intelliq_risk\lib\site-packages\numba\__init__.py", line 20, in <module>
    from numba.misc.special import (
  File "C:\ProgramData\Anaconda3_all\envs\intelliq_risk\lib\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "C:\ProgramData\Anaconda3_all\envs\intelliq_risk\lib\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "C:\ProgramData\Anaconda3_all\envs\intelliq_risk\lib\site-packages\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "C:\ProgramData\Anaconda3_all\envs\intelliq_risk\lib\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "C:\ProgramData\Anaconda3_all\envs\intelliq_risk\lib\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

**The original error was: 'DLL load failed: The specified module could not be found.'**
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\ProgramData\Anaconda3_all\envs\intelliq_risk\python.exe

**Comment by pycaret** [comment]
Hi.

exp_clf = setup(X, target=config.Y)

Target variable should be part of dataframe X. 

Looking at the code above. Question is does config.Y contains string of target col name?

Thanks.

**Comment by tciric-tc** [comment]
Unfortunately, X contains the target variable and config.Y is its string name.

**Comment by pycaret** [comment]
Are you using Jupyter?

**Comment by nasospat** [comment]
I had the same problem and I uninstalled the pypi numba with 
`pip uninstall numba`
and then installed the conda version with 
`conda install numba`
After that it worked fine for me.

**Comment by pycaret** [comment]
@tciric-tc Can you try what @nasospat has suggested? Please let us know how it goes.

@nasospat  Thanks for sharing.
