### ISSUE TITLE
NameError: name 'prep_pipe' is not defined

### ISSUE THREAD

**Issue by karailker** [pycaret/pycaret#2371]
**Error:**
```
Traceback (most recent call last):
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/fastapi/applications.py", line 212, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/mnt/d/main.py", line 192, in make_predictions
    preds = pcc.predict_model(model, data=df_results[cnames])
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/pycaret/classification.py", line 2125, in predict_model
    return pycaret.internal.tabular.predict_model(
  File "/home/ilker/anaconda3/envs/pycenv/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 9038, in predict_model
    "dtypes", prep_pipe.named_steps["dtypes"]
NameError: name 'prep_pipe' is not defined
```

When I try to make predictions using saved classification model, I faced an error above.

The code sample that I used:

```
import pycaret.classification as pcc
model = pcc.load_model(model_path)
preds = pcc.predict_model(model, data=df_results[cnames])
```

I tried to make predictions with **PyCaret 2.3.8 & 2.3.9. Both versions gave this error**.

**But I downgraded the version to 2.3.6, this solved the issue.**

**Comment by ngupta23** [comment]
Related to #2348 which has a potential alternate solution while this is fixed.

**Comment by karailker** [comment]
Thanks for reply, the issue is exactly the same. 
Have a good day.
