### ISSUE TITLE
[BUG]: Compare Models with distributed execution (Fugue/Spark) not working with custom metrics

### ISSUE THREAD

**Issue by holetz** [pycaret/pycaret#2445]
### pycaret version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the main branch of pycaret.

### Reproducible Example

```python
from pycaret.datasets import get_data
from pycaret.classification import *
from pycaret.parallel import FugueBackend #Must install fugue package
import numpy as np
#Running from Databricks, no need to declare spark

setup(data=get_data("juice"), target = 'Purchase', n_jobs = 1, silent=True) #Without silent code won't run in Databricks or Google Colab
test_models = models().index.tolist()[:5]

def score_ks(y_true, y_prob, axis=0):
        y_true = np.asarray(y_true)
        k_prob = np.flip(np.argsort(y_prob,axis=axis),axis=axis)
        yk_true = np.take_along_axis(y_true,k_prob,axis=axis)
        yk_false = (yk_true == 0).astype(int)
        y_false = (y_true == 0).astype(int)
        yp_true = y_prob > 0.5
        yp_false = (yp_true == 0).astype(int)
        y_equal = (yp_true == y_true).astype(int)
        y_diff = (yp_true == y_false).astype(int)

        TP = np.sum(y_equal * yp_true, axis=axis, keepdims=True)
        FP = np.sum(y_diff * yp_true, axis=axis, keepdims=True)
        TN = np.sum(y_equal * yp_false, axis=axis, keepdims=True)
        FN = np.sum(y_diff * yp_false, axis=axis, keepdims=True)
        P = TP + FN
        N = TN + FP
        
        KS = np.max((np.cumsum(yk_true,axis=axis)/P)-(np.cumsum(yk_false,axis=axis)/N),axis=axis)
        return KS

add_metric(id = 'ks',
               name = 'KS',
               score_func = score_ks,
               target = 'pred_proba',
               greater_is_better = True,
               multiclass = True,
              ) #Adding custom function to calculate KS metric

compare_models(include=test_models, n_select=2, sort="Accuracy") #OK
compare_models(include=test_models, n_select=2, parallel=FugueBackend(spark), sort="Accuracy") #OK
compare_models(include=test_models, n_select=2, sort="KS") #Ok
compare_models(include=test_models, n_select=2, parallel=FugueBackend(spark), sort="KS") #Error
```

### Issue Description

I'm getting an error when comparing models together with Fugue and a custom metric.

### Expected Behavior

      _1 _State.RUNNING -> _State.FAILED  An error occurred while calling o7346.getResult.
      : org.apache.spark.SparkException: Exception thrown in awaitResult: 
	      at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:428)
	      at org.apache.spark.security.SocketAuthServer.getResult(SocketAuthServer.scala:107)
	      at org.apache.spark.security.SocketAuthServer.getResult(SocketAuthServer.scala:103)
	      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	      at java.lang.reflect.Method.invoke(Method.java:498)
	      at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	      at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	      at py4j.Gateway.invoke(Gateway.java:295)
	      at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	      at py4j.commands.CallCommand.execute(CallCommand.java:79)
	      at py4j.GatewayConnection.run(GatewayConnection.java:251)
	      at java.lang.Thread.run(Thread.java:748)
      Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Task 2 in stage 19.0 failed 4 times, most recent failure: Lost task 2.3 in stage 19.0 (TID 262) (10.69.251.1 executor 2): org.apache.spark.api.python.PythonException: 'ValueError: Sort method not supported. See docstring for list of available parameters.'. Full traceback below:
      Traceback (most recent call last):
        File "/databricks/spark/python/pyspark/worker.py", line 752, in main
          process()
        File "/databricks/spark/python/pyspark/worker.py", line 744, in process
          serializer.dump_stream(out_iter, outfile)
        File "/databricks/spark/python/pyspark/serializers.py", line 264, in dump_stream
          vs = list(itertools.islice(iterator, batch))
        File "/databricks/python/lib/python3.8/site-packages/fugue_spark/execution_engine.py", line 717, in run
          res = self.map_func(cursor, sub_df)
        File "/databricks/python/lib/python3.8/site-packages/fugue/extensions/_builtins/processors.py", line 335, in run
          return self.transformer.transform(df)
        File "/databricks/python/lib/python3.8/site-packages/fugue/extensions/transformer/convert.py", line 265, in transform
          return self._wrapper.run(
        File "/databricks/python/lib/python3.8/site-packages/fugue/_utils/interfaceless.py", line 224, in run
          rt = self._func(**rargs)
        File "/databricks/python/lib/python3.8/site-packages/pycaret/parallel/fugue_backend.py", line 186, in _remote_compare_models
          m = self._func(include=include, **params)
        File "/databricks/python/lib/python3.8/site-packages/pycaret/classification.py", line 823, in compare_models
          return pycaret.internal.tabular.compare_models(
        File "/databricks/python/lib/python3.8/site-packages/pycaret/internal/tabular.py", line 2019, in compare_models
          raise ValueError(
      ValueError: Sort method not supported. See docstring for list of available parameters.

	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:689)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:850)
	at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:832)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:642)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:491)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:759)
	at org.apache.spark.sql.execution.arrow.ArrowConverters$$anon$1.hasNext(ArrowConverters.scala:206)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:460)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
	at scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:105)
	at scala.collection.mutable.ArrayBuffer.$plus$plus$eq(ArrayBuffer.scala:49)
	at scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
	at scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
	at scala.collection.AbstractIterator.to(Iterator.scala:1431)
	at scala.collection.TraversableOnce.toBuffer(TraversableOnce.scala:358)
	at scala.collection.TraversableOnce.toBuffer$(TraversableOnce.scala:358)
	at scala.collection.AbstractIterator.toBuffer(Iterator.scala:1431)
	at scala.collection.TraversableOnce.toArray(TraversableOnce.scala:345)
	at scala.collection.TraversableOnce.toArray$(TraversableOnce.scala:339)
	at scala.collection.AbstractIterator.toArray(Iterator.scala:1431)
	at org.apache.spark.sql.Dataset.$anonfun$collectAsArrowToPython$7(Dataset.scala:3839)
	at org.apache.spark.SparkContext.$anonfun$runJob$3(SparkContext.scala:2722)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$3(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.$anonfun$runTask$1(ResultTask.scala:75)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:55)
	at org.apache.spark.scheduler.Task.doRunTask(Task.scala:153)
	at org.apache.spark.scheduler.Task.$anonfun$run$1(Task.scala:122)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.scheduler.Task.run(Task.scala:93)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$13(Executor.scala:825)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1667)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$4(Executor.scala:828)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.spark.util.ExecutorFrameProfiler$.record(ExecutorFrameProfiler.scala:110)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:684)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Installed Versions

<details>
2.3.10
</details>

**Comment by ngupta23** [comment]
Thanks for confirming. Can you try running that line without Spark (temporarily) and confirm whether the issue still exists or not? It will help narrow down the problem.

**Comment by ngupta23** [comment]
Thanks for confirming. I see that KS works when not using Spark backend. We will have someone look at why it is not working with Spark backend.

**Comment by goodwanghan** [comment]
Thank you for reporting, let me investigate.

**Comment by goodwanghan** [comment]
@holetz do you know how to pip install a branch? If so, you can test the change I just made ^^^. So I didn't notice `_all_metrics` is not set inside setup, so I just included it.

**Comment by holetz** [comment]
Sure. Apparently the error persists.
However, I'm not sure if I installed it correctly:

Running from a Databricks notebook with a cluster that has PyCaret in it as default:

    !pip install --upgrade git+https://github.com/goodwanghan/pycaret@fugue-add_metric

    Collecting git+https://github.com/goodwanghan/pycaret@fugue-add_metric
      Cloning https://github.com/goodwanghan/pycaret (to revision fugue-add_metric) to /tmp/pip-req-build-cpuberb7
      Running command git clone -q https://github.com/goodwanghan/pycaret /tmp/pip-req-build-cpuberb7
      Running command git checkout -b fugue-add_metric --track origin/fugue-add_metric
      Switched to a new branch 'fugue-add_metric'
      Branch 'fugue-add_metric' set up to track remote branch 'fugue-add_metric' from 'origin'.
    Requirement already satisfied: pandas in /databricks/python3/lib/python3.8/site-packages (from pycaret==2.3.10) (1.2.4)
    Requirement already satisfied: scipy<=1.5.4 in /databricks/python3/lib/python3.8/site-packages (from pycaret==2.3.10) (1.5.4)
    . . .
    Requirement already satisfied: pynndescent>=0.5 in /databricks/python3/lib/python3.8/site-packages (from umap-learn->pycaret==2.3.10) (0.5.6)
    WARNING: You are using pip version 21.0.1; however, version 22.0.4 is available.
    You should consider upgrading via the '/databricks/python3/bin/python -m pip install --upgrade pip' command.

Error:

    /databricks/python/lib/python3.8/site-packages/pycaret/internal/tabular.py in compare_models(include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, experiment_custom_tags, probability_threshold, verbose, display)
       2017         sort = _get_metric(sort)
       2018         if sort is None:
    -> 2019             raise ValueError(
       2020                 f"Sort method not supported. See docstring for list of available parameters."
       2021             )
    
    ValueError: Sort method not supported. See docstring for list of available parameters.

**Comment by goodwanghan** [comment]
Ah I don't think that is the right way to install. No worries I will test on Databricks.

**Comment by goodwanghan** [comment]
I verified this is working now
