### ISSUE TITLE
[ENH]: Improve error message when classification target column is part of `categorical_features` argument

### ISSUE THREAD

**Issue by mingjun1120** [pycaret/pycaret#2451]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the main branch of pycaret.

### Issue Description

I am facing the problem of ValueError: Column type forced for my target variable. I have checked the spelling of my target variable's name, it did spell correctly when I assign it to the `target` parameter in `setup()`.
![image](https://user-images.githubusercontent.com/54136320/164497777-c9394c48-5b83-4c45-a778-e2c01531b455.png)
![image](https://user-images.githubusercontent.com/54136320/164500413-b1b0ae27-4827-4c54-b27a-b76f5acce1cf.png)

<br>
Here is the traceback :

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-165-f6dee6ad0244> in <module>
      3 cat_idx_lst = [index for index, col in enumerate(claim_df.columns) if claim_df[col].dtype.name == 'object']
      4 
----> 5 s = setup(data=claim_df, target='EarlyClaimAndLapsed', train_size=0.8, use_gpu=True, fold_shuffle=True, 
      6           fix_imbalance=True, fix_imbalance_method=SMOTENC(random_state=42, categorical_features=cat_idx_lst),
      7           numeric_features=num_cols, categorical_features=cat_cols+target_col,

~\anaconda3\envs\medicalclaim\lib\site-packages\pycaret\classification.py in setup(data, target, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs)
    597         log_plots = ["auc", "confusion_matrix", "feature"]
    598 
--> 599     return pycaret.internal.tabular.setup(
    600         ml_usecase="classification",
    601         available_plots=available_plots,

~\anaconda3\envs\medicalclaim\lib\site-packages\pycaret\internal\tabular.py in setup(data, target, ml_usecase, available_plots, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, transform_target, transform_target_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs, display)
    643             if i not in all_cols:
    644                 if i == target:
--> 645                     raise ValueError(f"Column type forced  >> {i} << is target column.")
    646                 else:
    647                     raise ValueError(

ValueError: Column type forced  >> EarlyClaimAndLapsed << is target column.
```

### Reproducible Example

```python
from pycaret.classification import *

cat_idx_lst = [index for index, col in enumerate(claim_df.columns) if claim_df[col].dtype.name == 'object']

s = setup(data=claim_df, target='EarlyClaimAndLapsed', train_size=0.8, use_gpu=True, fold_shuffle=True, 
          fix_imbalance=True, fix_imbalance_method=SMOTENC(random_state=42, categorical_features=cat_idx_lst), 
          numeric_features=num_cols, categorical_features=cat_cols+target_col, 
          ordinal_features = { 'OCCUPATION_CLASS' : ['D', 'C', 'B', 'A'], 'RSK_SUM_ASSURE' : ['100', '150', '200', '300', '400', '600']}
         )
```

### Expected Behavior

The output should be something like this (Taken from documentation):

![image](https://user-images.githubusercontent.com/54136320/164499873-d6dd4fa8-ec55-4b8d-b61c-3f49298cc9cc.png)

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-165-f6dee6ad0244> in <module>
      3 cat_idx_lst = [index for index, col in enumerate(claim_df.columns) if claim_df[col].dtype.name == 'object']
      4 
----> 5 s = setup(data=claim_df, target='EarlyClaimAndLapsed', train_size=0.8, use_gpu=True, fold_shuffle=True, 
      6           fix_imbalance=True, fix_imbalance_method=SMOTENC(random_state=42, categorical_features=cat_idx_lst),
      7           numeric_features=num_cols, categorical_features=cat_cols+target_col,

~\anaconda3\envs\medicalclaim\lib\site-packages\pycaret\classification.py in setup(data, target, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs)
    597         log_plots = ["auc", "confusion_matrix", "feature"]
    598 
--> 599     return pycaret.internal.tabular.setup(
    600         ml_usecase="classification",
    601         available_plots=available_plots,

~\anaconda3\envs\medicalclaim\lib\site-packages\pycaret\internal\tabular.py in setup(data, target, ml_usecase, available_plots, train_size, test_data, preprocess, imputation_type, iterative_imputation_iters, categorical_features, categorical_imputation, categorical_iterative_imputer, ordinal_features, high_cardinality_features, high_cardinality_method, numeric_features, numeric_imputation, numeric_iterative_imputer, date_features, ignore_features, normalize, normalize_method, transformation, transformation_method, handle_unknown_categorical, unknown_categorical_method, pca, pca_method, pca_components, ignore_low_variance, combine_rare_levels, rare_level_threshold, bin_numeric_features, remove_outliers, outliers_threshold, remove_multicollinearity, multicollinearity_threshold, remove_perfect_collinearity, create_clusters, cluster_iter, polynomial_features, polynomial_degree, trigonometry_features, polynomial_threshold, group_features, group_names, feature_selection, feature_selection_threshold, feature_selection_method, feature_interaction, feature_ratio, interaction_threshold, fix_imbalance, fix_imbalance_method, transform_target, transform_target_method, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, custom_pipeline, html, session_id, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, silent, verbose, profile, profile_kwargs, display)
    643             if i not in all_cols:
    644                 if i == target:
--> 645                     raise ValueError(f"Column type forced  >> {i} << is target column.")
    646                 else:
    647                     raise ValueError(

ValueError: Column type forced  >> EarlyClaimAndLapsed << is target column.
```

### Installed Versions

<details>
'2.3.10'
</details>

**Comment by ngupta23** [comment]
@mingjun1120 Thanks for providing the detailed example. Since we don't have access to the dataset, can you either try to recreate this issue with an inbuilt dataset in PyCaret or provide us the dataset (even a fake dataset that recreates the problem is good enough for us - we do not need the actual data if it is proprietary).

**Comment by mingjun1120** [comment]
@ngupta23 I found the problem. The problem happens on this line of code:
`categorical_features=cat_cols+target_col,`

`cat_cols` and `target_col` are list variables where they **store the column names** of category features** and the **target feature** respectively. However, the `cat_cols` variable doesn't include the target variable column name so I add `target_col` with `cat_cols` when assigning to the `categorical_features` parameter in the `setup()` function. 

Now, I remove the `target_col` list when assigning to the `categorical_features` parameter in the `setup()` function as `target_col` list variable only store the target variable name called **EarlyClaimAndLapsed**.

**Comment by moezali1** [comment]
@mingjun1120 You are right. When you are using `pycaret.classification`, it is assumed that the target variable is categorical. You don't need to pass it in the `categorical_features` parameter.

**Comment by ngupta23** [comment]
@moezali1 , maybe the error message can be made clearer here by checking if the target variables is in the `categorical_features` list. I think I saw another user face this same issue. 

We can add this as an enhancement so I will open this issue until that is done.

**Comment by ngupta23** [comment]
To test fix

```python
from pycaret.datasets import get_data
from pycaret.classification import ClassificationExperiment

data = get_data("juice")

exp = ClassificationExperiment()
exp.setup(data=data, target="Purchase", categorical_features=["A", "PriceCH", "Purchase", "B"])
```

```python-traceback
  File "c:\Users\Nikhil\OneDrive\my_libraries\my_python_libraries\pycaret\pycaret_dev\pycaret\internal\utils.py", line 119, in check_features_exist
    raise ValueError(
ValueError:

Column(s): ['A', 'Purchase', 'B'] not found in the feature dataset!
They are either missing from the features or you have specified a target column as a feature. Available feature columns are:
['Id', 'WeekofPurchase', 'StoreID', 'PriceCH', 'PriceMM', 'DiscCH', 'DiscMM', 'SpecialCH', 'SpecialMM', 'LoyalCH', 'SalePriceMM', 'SalePriceCH', 'PriceDiff', 'Store7', 'PctDiscMM', 'PctDiscCH', 'ListPriceDiff', 'STORE']
```

**Comment by mingjun1120** [comment]
> To test fix
> 
> ```python
> from pycaret.datasets import get_data
> from pycaret.classification import ClassificationExperiment
> 
> data = get_data("juice")
> 
> exp = ClassificationExperiment()
> exp.setup(data=data, target="Purchase", categorical_features=["A", "PriceCH", "Purchase", "B"])
> ```
> 
> ```
>   File "c:\Users\Nikhil\OneDrive\my_libraries\my_python_libraries\pycaret\pycaret_dev\pycaret\internal\utils.py", line 119, in check_features_exist
>     raise ValueError(
> ValueError:
> 
> Column(s): ['A', 'Purchase', 'B'] not found in the feature dataset!
> They are either missing from the features or you have specified a target column as a feature. Available feature columns are:
> ['Id', 'WeekofPurchase', 'StoreID', 'PriceCH', 'PriceMM', 'DiscCH', 'DiscMM', 'SpecialCH', 'SpecialMM', 'LoyalCH', 'SalePriceMM', 'SalePriceCH', 'PriceDiff', 'Store7', 'PctDiscMM', 'PctDiscCH', 'ListPriceDiff', 'STORE']
> ```

Good error message raised!!!😊👍
Nice work and well done! Keep it up the good work 💪
