### ISSUE TITLE
[BUG]: Can't train models with exogenous variables and forecast horizons start larger than 1

### ISSUE THREAD

**Issue by rantos9** [pycaret/pycaret#2480]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the develop branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@develop).

### Issue Description

Whenever I try any values larger than 1 for the start of the forecast horizon I can't train any models with exogenous variables.

### Reproducible Example

```python
import pandas as pd
import numpy as np
from pycaret.time_series import TSForecastingExperiment

dates = pd.date_range('2019-01-1', '2022-04-15')

df = pd.DataFrame(np.random.randint(0, 4000, size=len(dates)), index=dates, columns=['qtde'])

df = df.assign(exoge_1=lambda x: x.qtde*np.random.randint(0, 10))

exp = TSForecastingExperiment()

exp.setup(
    data=df,
    fh=np.arange(1, 4),
    session_id=5005,
    seasonal_period=['Y'],
    fold=5,
    enforce_exogenous=True,
    target='qtde',
)
#this works
best = exp.compare_models(errors='raise', include=['knn_cds_dt'])

exp.setup(
    data=df,
    fh=np.arange(2, 4),
    session_id=5005,
    seasonal_period=['Y'],
    fold=5,
    enforce_exogenous=True,
    target='qtde',
)

exp.plot_model(
    plot='cv',
)
#this dosen't
best = exp.compare_models(errors='raise', include=['knn_cds_dt'])
```

### Expected Behavior

Models to be trained with no problems

### Actual Results

```python-traceback
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\externals\loky\process_executor.py", line 431, in _process_worker
    r = call_item()
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\externals\loky\process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\pycaret\utils\time_series\forecasting\model_selection.py", line 122, in _fit_and_score
    y_pred, lower, upper = get_predictions_with_intervals(
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\pycaret\utils\time_series\forecasting\__init__.py", line 47, in get_predictions_with_intervals
    return_values = forecaster.predict(
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\base\_base.py", line 205, in predict
    y_pred = self._predict(fh=fh, X=X_inner)
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\compose\_pipeline.py", line 280, in _predict
    return forecaster.predict(fh, X, return_pred_int=return_pred_int, alpha=alpha)
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\base\_base.py", line 205, in predict
    y_pred = self._predict(fh=fh, X=X_inner)
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\compose\_pipeline.py", line 429, in _predict
    y_pred = forecaster.predict(
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\base\_base.py", line 205, in predict
    y_pred = self._predict(fh=fh, X=X_inner)
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\pycaret\containers\models\time_series.py", line 2570, in _predict
    y = self._forecaster.predict(
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\base\_base.py", line 205, in predict
    y_pred = self._predict(fh=fh, X=X_inner)
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\compose\_pipeline.py", line 429, in _predict
    y_pred = forecaster.predict(
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\base\_base.py", line 205, in predict
    y_pred = self._predict(fh=fh, X=X_inner)
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\base\_sktime.py", line 78, in _predict
    return self._predict_fixed_cutoff(
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\base\_sktime.py", line 112, in _predict_fixed_cutoff
    y_pred = self._predict_last_window(
  File "C:\Users\Renan\anaconda3\envs\pycaret-ts\lib\site-packages\sktime\forecasting\compose\_reduce.py", line 417, in _predict_last_window
    last[:, 1:, window_length:] = X.T
ValueError: could not broadcast input array from shape (1,2) into shape (1,1,3)
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Input In [16], in <cell line: 39>()
     25 exp.setup(
     26     data=df,
     27     fh=np.arange(2, 4),
   (...)
     32     target='qtde',
     33 )
     35 exp.plot_model(
     36     plot='cv',
     37 )
---> 39 best = exp.compare_models(errors='raise', include=['knn_cds_dt'])

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\pycaret\time_series\forecasting\oop.py:1595, in TSForecastingExperiment.compare_models(self, include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, experiment_custom_tags, verbose)
   1503 """
   1504 This function trains and evaluates performance of all estimators available in the
   1505 model library using cross validation. The output of this function is a score grid
   (...)
   1590 
   1591 """
   1593 self._check_setup_ran()
-> 1595 return super().compare_models(
   1596     include=include,
   1597     exclude=exclude,
   1598     fold=fold,
   1599     round=round,
   1600     cross_validation=cross_validation,
   1601     sort=sort,
   1602     n_select=n_select,
   1603     budget_time=budget_time,
   1604     turbo=turbo,
   1605     errors=errors,
   1606     fit_kwargs=fit_kwargs,
   1607     experiment_custom_tags=experiment_custom_tags,
   1608     verbose=verbose,
   1609 )

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py:693, in _SupervisedExperiment.compare_models(self, include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, experiment_custom_tags, probability_threshold, verbose, display)
    691 results_columns_to_ignore = ["Object", "runtime", "cutoff"]
    692 if errors == "raise":
--> 693     model, model_fit_time = self.create_model(**create_model_args)
    694     model_results = self.pull(pop=True)
    695 else:

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\pycaret\time_series\forecasting\oop.py:1718, in TSForecastingExperiment.create_model(self, estimator, fold, round, cross_validation, fit_kwargs, experiment_custom_tags, verbose, **kwargs)
   1623 """
   1624 This function trains and evaluates the performance of a given estimator
   1625 using cross validation. The output of this function is a score grid with
   (...)
   1713 
   1714 """
   1716 self._check_setup_ran()
-> 1718 return super().create_model(
   1719     estimator=estimator,
   1720     fold=fold,
   1721     round=round,
   1722     cross_validation=cross_validation,
   1723     fit_kwargs=fit_kwargs,
   1724     experiment_custom_tags=experiment_custom_tags,
   1725     verbose=verbose,
   1726     **kwargs,
   1727 )

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py:1472, in _SupervisedExperiment.create_model(self, estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, probability_threshold, experiment_custom_tags, verbose, system, add_to_model_list, X_train_data, y_train_data, metrics, display, **kwargs)
   1469         return model, model_fit_time
   1470     return model
-> 1472 model, model_fit_time, model_results, avgs_dict = self._create_model_with_cv(
   1473     model,
   1474     data_X,
   1475     data_y,
   1476     fit_kwargs,
   1477     round,
   1478     cv,
   1479     groups,
   1480     metrics,
   1481     refit,
   1482     system,
   1483     display,
   1484 )
   1486 # end runtime
   1487 runtime_end = time.time()

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\pycaret\time_series\forecasting\oop.py:1869, in TSForecastingExperiment._create_model_with_cv(self, model, data_X, data_y, fit_kwargs, round, cv, groups, metrics, refit, system, display)
   1862 ###############################################
   1863 #### Add the correct model to the pipeline ####
   1864 ###############################################
   1865 pipeline_with_model = _add_model_to_pipeline(
   1866     pipeline=self.pipeline, model=model
   1867 )
-> 1869 scores, cutoffs = cross_validate(
   1870     forecaster=pipeline_with_model,
   1871     y=data_y,
   1872     X=data_X,
   1873     scoring=metrics_dict,
   1874     cv=cv,
   1875     n_jobs=n_jobs,
   1876     verbose=0,
   1877     fit_params=fit_kwargs,
   1878     return_train_score=False,
   1879     error_score=0,
   1880     **additional_scorer_kwargs,
   1881 )
   1883 model_fit_end = time.time()
   1884 model_fit_time = np.array(model_fit_end - model_fit_start).round(2)

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\pycaret\utils\time_series\forecasting\model_selection.py:235, in cross_validate(forecaster, y, X, cv, scoring, fit_params, n_jobs, return_train_score, error_score, verbose, **additional_scorer_kwargs)
    232     scoring = _get_metrics_dict(scoring)
    233     parallel = Parallel(n_jobs=n_jobs)
--> 235     out = parallel(
    236         delayed(_fit_and_score)(
    237             forecaster=clone(forecaster),
    238             y=y,
    239             X=X,
    240             scoring=scoring,
    241             train=train,
    242             test=test,
    243             parameters=None,
    244             fit_params=fit_params,
    245             return_train_score=return_train_score,
    246             error_score=error_score,
    247             **additional_scorer_kwargs,
    248         )
    249         for train, test in get_folds(cv, y)
    250     )
    251 # raise key exceptions
    252 except Exception:

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\parallel.py:1054, in Parallel.__call__(self, iterable)
   1051     self._iterating = False
   1053 with self._backend.retrieval_context():
-> 1054     self.retrieve()
   1055 # Make sure that we get a last message telling us we are done
   1056 elapsed_time = time.time() - self._start_time

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\parallel.py:933, in Parallel.retrieve(self)
    931 try:
    932     if getattr(self._backend, 'supports_timeout', False):
--> 933         self._output.extend(job.get(timeout=self.timeout))
    934     else:
    935         self._output.extend(job.get())

File ~\anaconda3\envs\pycaret-ts\lib\site-packages\joblib\_parallel_backends.py:542, in LokyBackend.wrap_future_result(future, timeout)
    539 """Wrapper for Future.result to implement the same behaviour as
    540 AsyncResults.get from multiprocessing."""
    541 try:
--> 542     return future.result(timeout=timeout)
    543 except CfTimeoutError as e:
    544     raise TimeoutError from e

File ~\anaconda3\envs\pycaret-ts\lib\concurrent\futures\_base.py:444, in Future.result(self, timeout)
    442     raise CancelledError()
    443 elif self._state == FINISHED:
--> 444     return self.__get_result()
    445 else:
    446     raise TimeoutError()

File ~\anaconda3\envs\pycaret-ts\lib\concurrent\futures\_base.py:389, in Future.__get_result(self)
    387 if self._exception:
    388     try:
--> 389         raise self._exception
    390     finally:
    391         # Break a reference cycle with the exception in self._exception
    392         self = None

ValueError: could not broadcast input array from shape (1,2) into shape (1,1,3)
```

### Installed Versions

<details>
System:
    python: 3.8.13 (default, Mar 28 2022, 06:59:08) [MSC v.1916 64 bit (AMD64)]
executable: C:\Users\Renan\anaconda3\envs\pycaret-ts\python.exe
   machine: Windows-10-10.0.19044-SP0

Python dependencies:
          pip: 21.2.2
   setuptools: 61.2.0
      pycaret: 3.0.0
      sklearn: 1.0.2
       sktime: 0.10.1
  statsmodels: 0.13.2
        numpy: 1.21.6
        scipy: 1.7.3
       pandas: 1.4.2
   matplotlib: 3.5.1
       plotly: 5.6.0
       joblib: 1.0.1
        numba: 0.55.1
       mlflow: Not installed
     lightgbm: 3.3.2
      xgboost: Not installed
     pmdarima: 1.8.5
        tbats: Installed but version unavailable
      prophet: Not installed
      tsfresh: Not installed
</details>

**Comment by ngupta23** [comment]
Hi @rantos9 Thank you for reporting this bug and providing a reproducible example. That really helped to debug this issue (because it does not occur in all cases). It seems that this is an underlying bug in `sktime`. I have filed a bug report with them. Once I hear back from them, I can make the necessary changes in pycaret.

https://github.com/alan-turing-institute/sktime/issues/2598
