### ISSUE TITLE
lib issue power BI

### ISSUE THREAD

**Issue by Om-patel2398** [pycaret/pycaret#252]
This is the first time i am trying pycaret, I followed the medium blog by pycaret [about using it with power BI](https://towardsdatascience.com/machine-learning-in-power-bi-using-pycaret-34307f09394a). I did everything as specified, I created a new conda environment for pycaret and installed py caret there. I also specified my power BI to use that environment. I fetched data from given git link, then as said in the first example in article I tried performing clustering by 
`from pycaret.clustering import *`
`dataset = get_clusters(data = dataset)`
but my python script is giving following error

DataSource.Error: ADO.NET: Python script error.
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 14, in <module>
    dataset = get_clusters(data = dataset)
  File "D:\ana\a3\envs\pycaret\lib\site-packages\pycaret\clustering.py", line 3228, in get_clusters
    from pycaret import preprocess
  File "D:\ana\a3\envs\pycaret\lib\site-packages\pycaret\preprocess.py", line 8, in <module>
    import ipywidgets as wg 
  File "D:\ana\a3\envs\pycaret\lib\site-packages\ipywidgets\__init__.py", line 25, in <module>
    from .widgets import *
  File "D:\ana\a3\envs\pycaret\lib\site-packages\ipywidgets\widgets\__init__.py", line 4, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization
  File "D:\ana\a3\envs\pycaret\lib\site-packages\ipywidgets\widgets\widget.py", line 18, in <module>
    from ipykernel.comm import Comm
  File "D:\ana\a3\envs\pycaret\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "D:\ana\a3\envs\pycaret\lib\site-packages\ipykernel\connect.py", line 18, in <module>
    import jupyter_client
  File "D:\ana\a3\envs\pycaret\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "D:\ana\a3\envs\pycaret\lib\site-packages\jupyter_client\connect.py", line 21, in <module>
    import zmq
  File "D:\ana\a3\envs\pycaret\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "D:\ana\a3\envs\pycaret\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "D:\ana\a3\envs\pycaret\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "D:\ana\a3\envs\pycaret\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "D:\ana\a3\envs\pycaret\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "D:\ana\a3\envs\pycaret\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.
Details:
    DataSourceKind=Python
    DataSourcePath=Python
    Message=Python script error.
Traceback (most recent call last):
  File "PythonScriptWrapper.PY", line 14, in <module>
    dataset = get_clusters(data = dataset)
  File "D:\ana\a3\envs\pycaret\lib\site-packages\pycaret\clustering.py", line 3228, in get_clusters
    from pycaret import preprocess
  File "D:\ana\a3\envs\pycaret\lib\site-packages\pycaret\preprocess.py", line 8, in <module>
    import ipywidgets as wg 
  File "D:\ana\a3\envs\pycaret\lib\site-packages\ipywidgets\__init__.py", line 25, in <module>
    from .widgets import *
  File "D:\ana\a3\envs\pycaret\lib\site-packages\ipywidgets\widgets\__init__.py", line 4, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization
  File "D:\ana\a3\envs\pycaret\lib\site-packages\ipywidgets\widgets\widget.py", line 18, in <module>
    from ipykernel.comm import Comm
  File "D:\ana\a3\envs\pycaret\lib\site-packages\ipykernel\__init__.py", line 2, in <module>
    from .connect import *
  File "D:\ana\a3\envs\pycaret\...
    ErrorCode=-2147467259
    ExceptionType=Microsoft.PowerBI.Scripting.Python.Exceptions.PythonScriptRuntimeException

I couldn't figure out the problem

**Comment by pycaret** [comment]
@Om-patel2398 This seems like it is same as #128
