### ISSUE TITLE
[BUG]: RC3: Setup getting stuck at preprocessing pipeline

### ISSUE THREAD

**Issue by jnsflt** [pycaret/pycaret#2748]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Yesterday I upgraded to the latest release of pycaret (3.0.0rc3) from rc2. While it did fix a lot of bugs from previous version, I could not run `exp.setup(...)` with my dataset. This has not been an issue before. When running it gets stuck on some preprocessing step as you can see in the picture below.

![image](https://user-images.githubusercontent.com/107557528/178691805-2e71480f-1d07-4485-a124-7c61f3251c55.png)

As I write this, it has run for 10 min without continuing (setup usually takes maximum 1 min with my dataset). After interrupting the process, it turns out that I am stuck here:

![image](https://user-images.githubusercontent.com/107557528/178692724-843ebaa8-6e59-4ee0-a581-ee57a4aaf77c.png)

Unfortunately, I can not share my full dataset and can not reproduce the error on any of the open datasets. 

My dataset has shapes (4460,906) and has a lot of null values.

I understand that it is hard for you to find the error that occurs for me without my dataset. I will try to manipulate my dataset to upload it here. In the meantime, if you know what may be causing the issue, please tell me!

### Reproducible Example

```python
df = pd.read_csv('my_csv.csv')
exp = ClassificationExperiment()
exp.setup(data=df)
```

### Expected Behavior

Run as intentional.

### Actual Results

```python-traceback
Getting stuck in preprocessing as mentioned above.
```

### Installed Versions

<details>
3.0.0rc3
</details>

**Comment by jnsflt** [comment]
It turns out that it will continue eventually, but can take a really long time. I narrowed the dataset down to (4460,11) and setup took 2m31s to finish. Perhaps some efficiancy issues?

**Comment by jnsflt** [comment]
When I wait it out on my full dataset (4460,906) I get this error message:


>  File ".../lib/python3.8/site-packages/pycaret/classification/oop.py", line 850, in setup
    self.pipeline.fit(self.X_train, self.y_train)
  File ".../lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 158, in fit
    _fit_one(self._final_estimator, X, y, **fit_params_last_step)
  File ".../lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 36, in _fit_one
    transformer.fit(*args, **fit_params)
  File ".../lib/python3.8/site-packages/pycaret/internal/preprocess/transformers.py", line 209, in fit
    self.transformer.fit(*args, **fit_params)
  File ".../python3.8/site-packages/sklearn/feature_selection/_variance_threshold.py", line 104, in fit
    self.variances_ = np.nanvar(X, axis=0)
  File "<__array_function__ internals>", line 5, in nanvar
  File ".../lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 1518, in nanvar
    arr, mask = _replace_nan(a, 0)
  File ".../lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 107, in _replace_nan
    a = np.array(a, subok=True, copy=True)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 209. GiB for an array with shape (4460, 6292333) and data type float64

**Comment by Yard1** [comment]
Can you share your setup code and full logs.log file?

**Comment by jnsflt** [comment]
[logs.log](https://github.com/pycaret/pycaret/files/9101026/logs.log)

Here is the log file. Will try share the setup code later!

**Comment by tvdboom** [comment]
The problem is caused by the `low_variance_threshold` step in preprocessing. Setting it equal to `None` should solve it. The reason this causes memory issues is probably due to the large number of NaNs you have. It seems like a sklearn bug tbh. As you can see in your error output, the code in https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.VarianceThreshold.html is trying to replace your `NaNs` with zeros in order to be able to calculate the variance. For some reason, to achieve this, it is keeping multiple copies of your dataset in memory. If I have time later today, I could try to see what's happening exactly at a deeper level. For now, just use `low_variance_trheshold=None`. Maybe we should set this as the default value of the parameter...

**Comment by jnsflt** [comment]
Sorry to bother you again, just mentioning that the same issue occurs when setting `remove_multicollinearity = True`

> 2022-07-13 13:05:53 - [ERROR] [main.<module>:119]: Traceback (most recent call last):
...
  File ".../lib/python3.8/site-packages/pycaret/classification/oop.py", line 850, in setup
    self.pipeline.fit(self.X_train, self.y_train)
  File ".../lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 158, in fit
    _fit_one(self._final_estimator, X, y, **fit_params_last_step)
  File ".../lib/python3.8/site-packages/pycaret/internal/pipeline.py", line 36, in _fit_one
    transformer.fit(*args, **fit_params)
  File ".../lib/python3.8/site-packages/pycaret/internal/preprocess/transformers.py", line 209, in fit
    self.transformer.fit(*args, **fit_params)
  File ".../lib/python3.8/site-packages/pycaret/internal/preprocess/transformers.py", line 389, in fit
    data = X.merge(y.to_frame(), left_index=True, right_index=True)
  File ".../lib/python3.8/site-packages/pandas/core/frame.py", line 9351, in merge
    return merge(
  File ".../lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 122, in merge
    return op.get_result()
  File ".../lib/python3.8/site-packages/pandas/core/reshape/merge.py", line 725, in get_result
    result_data = concatenate_managers(
  File ".../lib/python3.8/site-packages/pandas/core/internals/concat.py", line 221, in concatenate_managers
    values = values.copy()
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 209. GiB for an array with shape (6292333, 4460) and data type float64


Now I have `low_variance_threshold=None`.

**Comment by tvdboom** [comment]
Uhmm, that's weird. I would like to debug this but I cant' reproduce the error. How many of your values are `NaN`? run `df.isna().sum().sum() / df.size`. How large is the dataset? run `df.memory_usage()`.

**Comment by jnsflt** [comment]
I have to debug it further. I will return if I have something to send you. Thanks for taking the time!

**Comment by jnsflt** [comment]
Hi, some updates:

I located the remove_multicollinearity down to one specific column which looks like this:
![image](https://user-images.githubusercontent.com/107557528/178929772-d85e034b-e9c5-41ed-8e1e-ac80c280fb57.png)

If I drop this column, remove_multicollinearity will work. Otherwise I get the allocation of 200 GB error as before.

It seems like a very specific bug, which did not occur in 3.0.0RC2, so I will probably rollback to that version.

Let me know if you can replicate it or find some solution to it!
