### ISSUE TITLE
[BUG]: Unable to use customer CV fold_strategy

### ISSUE THREAD

**Issue by jmrichardson** [pycaret/pycaret#2764]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Unable to pass custom CV generator with latest 3.0.0rc3.  I've commented out preproccesor.py  code for as a temporary workaround on line 252:

```
        elif fold_strategy not in allowed_fold_strategy:
            raise ValueError(
                "Invalid value for the fold_strategy parameter. "
                f"Choose from: {', '.join(allowed_fold_strategy)}."
            )
```

### Reproducible Example

```python
from sklearn.model_selection import KFold
        cv = KFold(n_splits=2)

        self.config = {
            'data': train,
            'test_data': test,
            'target': 'label',
            'normalize': False,
            'transformation': False,
            'remove_multicollinearity': False,
            'data_split_shuffle': False,
            'log_experiment': False,
            'experiment_name': self.name,
            'log_plots': False,
            'log_profile': False,
            'log_data': False,
            # 'fold': None,
            'fold_strategy': cv,
            'verbose': False,
            # 'numeric_features': [c for c in train.columns if c != 'label'],  # All features are numeric
            'session_id': 123,
        }
```

### Expected Behavior

Should allow custom fold strategy

### Actual Results

```python-traceback
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2021.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/Projects/finml/strategies/jmrichardson/nai.py", line 40, in <module>
    pipeline = pipeline.fit(features)
  File "D:\Projects\finml\fml\pipelines\standard.py", line 179, in fit
    model = copy.deepcopy(model).fit(features, target.purge)
  File "D:\Anaconda3\envs\fml\lib\site-packages\joblib\memory.py", line 595, in __call__
    return self._cached_call(args, kwargs)[0]
  File "D:\Anaconda3\envs\fml\lib\site-packages\joblib\memory.py", line 538, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "D:\Anaconda3\envs\fml\lib\site-packages\joblib\memory.py", line 788, in call
    output = self.func(*args, **kwargs)
  File "D:\Projects\finml\fml\models\pycaret_blend.py", line 82, in fit
    self.exp.setup(**self.config)
  File "D:\Anaconda3\envs\fml\lib\site-packages\pycaret\regression\oop.py", line 697, in setup
    self._prepare_folds(
  File "D:\Anaconda3\envs\fml\lib\site-packages\pycaret\internal\preprocess\preprocessor.py", line 253, in _prepare_folds
    raise ValueError(
ValueError: Invalid value for the fold_strategy parameter. Choose from: kfold, stratifiedkfold, groupkfold, timeseries.
```

### Installed Versions

<details>
from pycaret import show_versions; show_versions()
System:
    python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:00) [MSC v.1929 64 bit (AMD64)]
executable: D:\Anaconda3\envs\fml\python.exe
   machine: Windows-10-10.0.19044-SP0
PyCaret required dependencies:
Backend TkAgg is interactive backend. Turning interactive mode on.
                 pip: 22.1.2
          setuptools: 62.6.0
             pycaret: 3.0.0.rc3
             IPython: 8.4.0
          ipywidgets: 7.7.1
                tqdm: 4.64.0
               numpy: 1.21.6
              pandas: 1.4.3
              jinja2: 3.0.3
               scipy: 1.5.4
              joblib: 1.2.0.dev0
             sklearn: 1.1.1
                pyod: Installed but version unavailable
            imblearn: 0.9.1
   category_encoders: 2.5.0
            lightgbm: 3.3.2
               numba: 0.55.2
            requests: 2.28.1
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.4
              plotly: 5.9.0
             kaleido: 0.2.1
         statsmodels: 0.13.2
              sktime: 0.11.4
               tbats: Installed but version unavailable
            pmdarima: 1.8.5
              psutil: 5.9.1
</details>

**Comment by tvdboom** [comment]
Hi. Thanks for pointing it out. The issue is fixed in #2768

**Comment by moezali1** [comment]
@tvdboom Can we close this if the issue is fixed?
