### ISSUE TITLE
[BUG]: Cannot specify bracketed column names in target at setup()

### ISSUE THREAD

**Issue by nockn** [pycaret/pycaret#2800]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Hi.

I get an error when I specify a column with a name containing parentheses in target in setup().
I have recently started using PyCaret, so there may be a workaround, but I have not found one as far as I have looked.

Thank you.

### Reproducible Example

```python
import pandas as pd
from pycaret.regression import *

df = pd.DataFrame(data=[[1, 2, 3], [1, 2, 3], [1, 2, 3]], columns=["a", "b", "c[d]"])

setup_config = setup(df, target="c[d]")
```

### Expected Behavior

setup() completes.

### Actual Results

```python-traceback
Traceback (most recent call last):
  File ".\sample.py", line 7, in <module>
    setup_config = setup(df, target="c[d]")
  File "C:\Users\*****\AppData\Local\miniforge3\envs\optmz_exp\lib\site-packages\pycaret\regression.py", line 668, in setup
    profile_kwargs=profile_kwargs,
  File "C:\Users\*****\AppData\Local\miniforge3\envs\optmz_exp\lib\site-packages\pycaret\internal\tabular.py", line 1413, in setup
    X_train = train_data.drop(target, axis=1)
  File "C:\Users\*****\AppData\Local\miniforge3\envs\optmz_exp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\*****\AppData\Local\miniforge3\envs\optmz_exp\lib\site-packages\pandas\core\frame.py", line 4913, in drop
    errors=errors,
  File "C:\Users\*****\AppData\Local\miniforge3\envs\optmz_exp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\*****\AppData\Local\miniforge3\envs\optmz_exp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\*****\AppData\Local\miniforge3\envs\optmz_exp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")

KeyError: "['c[d]'] not found in axis"
```

### Installed Versions

<details>
2.3.10
</details>

**Comment by moezali1** [comment]
@nockn Works in the latest version of pycaret.

`pip install --pre pycaret`

![image](https://user-images.githubusercontent.com/54699234/202961440-d19820a1-a882-4b63-94b7-4f381fed0c92.png)
