### ISSUE TITLE
[BUG]: skopt custom search grid throws ValueError 

### ISSUE THREAD

**Issue by MMYusuf** [pycaret/pycaret#2990]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Hi,

tuning using skopt with custom search dicts gives valueError on the dicts values. 

looking into the log, I find that all dict are taken as CategoricalDistribution even when it should be Real or Integer:

2022-09-26 13:25:30,139:INFO:Initializing tune_model()
2022-09-26 13:25:30,139:INFO:tune_model(estimator=SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='scale',
    kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False), fold=None, round=4, n_iter=10, custom_grid={'epsilon': (1e-06, 0.1, 'uniform'), 'C': (1e-06, 1000000.0, 'log-uniform'), 'gamma': (1e-06, 10.0, 'log-uniform'), 'kernel': ['rbf']}, optimize=R2, custom_scorer=None, search_library=scikit-optimize, search_algorithm=None, early_stopping=False, early_stopping_max_iters=10, choose_better=False, fit_kwargs=None, groups=None, return_tuner=False, verbose=True, tuner_verbose=True, display=None, return_train_score=False, kwargs={})
2022-09-26 13:25:30,140:INFO:Checking exceptions
2022-09-26 13:25:30,147:INFO:Preparing display monitor
2022-09-26 13:25:30,164:INFO:Copying training dataset
2022-09-26 13:25:30,165:INFO:Checking base model
2022-09-26 13:25:30,166:INFO:Base model : Support Vector Regression
2022-09-26 13:25:30,173:INFO:Declaring metric variables
2022-09-26 13:25:30,179:INFO:Defining Hyperparameters
2022-09-26 13:25:30,276:INFO:custom_grid: {'actual_estimator__epsilon': CategoricalDistribution(values=[1e-06, 0.1, 'uniform']), 'actual_estimator__C': CategoricalDistribution(values=[1e-06, 1000000.0, 'log-uniform']), 'actual_estimator__gamma': CategoricalDistribution(values=[1e-06, 10.0, 'log-uniform']), 'actual_estimator__kernel': CategoricalDistribution(values=['rbf'])}
2022-09-26 13:25:30,277:INFO:Tuning with n_jobs=-1
2022-09-26 13:25:30,281:INFO:Initializing skopt.BayesSearchCV

Is there something that I am missing?

Thanks for your efforts, lib is amazing

### Reproducible Example

```python
from pycaret.datasets import get_data
from pycaret.regression import *


dataset = get_data("diamond")

exp_reg101 = setup(data=dataset, target="Price", session_id=123)


svr = create_model("svm")
svr_tuned = tune_model(
    svr,
    n_iter=10,
    search_library="scikit-optimize",
    custom_grid={
        "epsilon": (1e-6, 1e-1, "uniform"),
        "C": (1e-6, 1e6, "log-uniform"),
        "gamma": (1e-6, 1e1, "log-uniform"),
        "kernel": ["rbf"],  # categorical parameter
    },
)
```

### Expected Behavior

a tuned model is returned  

### Actual Results

```python-traceback
Output exceeds the size limit. Open the full output data in a text editor
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/myusuf3/.local/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
    r = call_item()
  File "/home/myusuf3/.local/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/myusuf3/.local/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 620, in __call__
    return self.func(*args, **kwargs)
  File "/home/myusuf3/.local/lib/python3.9/site-packages/joblib/parallel.py", line 288, in __call__
    return [func(*args, **kwargs)
  File "/home/myusuf3/.local/lib/python3.9/site-packages/joblib/parallel.py", line 288, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/myusuf3/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/myusuf3/.local/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 118, in fit
    result = super().fit(X, y=y, **fit_kwargs)
  File "/home/myusuf3/.local/lib/python3.9/site-packages/imblearn/pipeline.py", line 281, in fit
    self._final_estimator.fit(Xt, yt, **fit_params)
  File "/home/myusuf3/.local/lib/python3.9/site-packages/sklearn/svm/_base.py", line 205, in fit
    raise ValueError(
ValueError: When 'gamma' is a string, it should be either 'scale' or 'auto'. Got '10.0' instead.
```

### Installed Versions

<details>
'2.3.10'
</details>

**Comment by moezali1** [comment]
Can you try removing gamma from custom_grid and show what happened?

**Comment by MMYusuf** [comment]
doesn't work.. gives this error when gamma is removed

> Traceback (most recent call last):
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 428, in _process_worker
>     r = call_item()
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 275, in __call__
>     return self.fn(*self.args, **self.kwargs)
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 620, in __call__
>     return self.func(*args, **kwargs)
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/joblib/parallel.py", line 288, in __call__
>     return [func(*args, **kwargs)
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/joblib/parallel.py", line 288, in <listcomp>
>     return [func(*args, **kwargs)
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 531, in _fit_and_score
>     estimator.fit(X_train, y_train, **fit_params)
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 118, in fit
>     result = super().fit(X, y=y, **fit_kwargs)
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/imblearn/pipeline.py", line 281, in fit
>     self._final_estimator.fit(Xt, yt, **fit_params)
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/sklearn/svm/_base.py", line 217, in fit
>     fit(X, y, sample_weight, solver_type, kernel, random_seed=seed)
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/sklearn/svm/_base.py", line 268, in _dense_fit
>     self._probB, self.fit_status_ = libsvm.fit(
>   File "sklearn/svm/_libsvm.pyx", line 60, in sklearn.svm._libsvm.fit
> TypeError: must be real number, not str
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/mnt/c/Users/x3085550/Desktop/GitRepo/sohpbm/regression/pycaret_test.py", line 11, in <module>
>     svr_tuned = tune_model(
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/pycaret/regression.py", line 1151, in tune_model
>     return pycaret.internal.tabular.tune_model_supervised(
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 4681, in tune_model_supervised
>     model_grid.fit(X_train, y_train, groups=groups, **fit_kwargs)
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/skopt/searchcv.py", line 466, in fit
>     super().fit(X=X, y=y, groups=groups, **fit_params)
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
>     return f(**kwargs)
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/sklearn/model_selection/_search.py", line 736, in fit
>     self._run_search(evaluate_candidates)
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/skopt/searchcv.py", line 512, in _run_search
>     optim_result = self._step(
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/skopt/searchcv.py", line 408, in _step
>     all_results = evaluate_candidates(params_dict)
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/sklearn/model_selection/_search.py", line 708, in evaluate_candidates
>     out = parallel(delayed(_fit_and_score)(clone(base_estimator),
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/joblib/parallel.py", line 1098, in __call__
>     self.retrieve()
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/joblib/parallel.py", line 975, in retrieve
>     self._output.extend(job.get(timeout=self.timeout))
>   File "/home/myusuf3/.local/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
>     return future.result(timeout=timeout)
>   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 446, in result
>     return self.__get_result()
>   File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
>     raise self._exception
> TypeError: must be real number, not str

**Comment by moezali1** [comment]
Closing as part of the 4.0 backlog cleanup — see #4177.

PyCaret 4.0 is a ground-up rewrite (OOP-only API, sklearn-native engine, Python 3.11+, sklearn ≥ 1.7) and almost all pre-4.0 issues either reference removed APIs (`setup()`, `plot_model`, `evaluate_model`, `interpret_model`, `automl`, the legacy time-series module, the Streamlit dashboard, …) or no longer reproduce on the new code path.

**If this still affects you in 4.0, please re-file as a new issue** with:

- the experiment constructor call (`Experiment(...)`),
- the operation that fails,
- the full traceback,
- your Python / sklearn / pycaret versions.

Resources for 4.0:

- Docs: https://pycaret.org/docs
- Migrate from 3.x: https://pycaret.org/docs/guides/migrating-from-3-x
- API reference: https://pycaret.org/reference
- FAQ: https://pycaret.org/docs/resources/faqs

Thanks for filing — and apologies for the long latency. The repo had drifted; we're starting clean.
