### ISSUE TITLE
[INSTALL]: PyCaret 3.0 installation issue

### ISSUE THREAD

**Issue by Hussam1** [pycaret/pycaret#3150]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

.

### Installation Method

pip install

### pycaret Version

3.0

### Python Version

3.8

### Description

When trying to install PyCaret[full] I get the below error
after removing the [full], it downloaded 2.3.10

```
Preparing metadata (setup.py) ... done
  Downloading Boruta-0.1.4.tar.gz (8.9 kB)
  Preparing metadata (setup.py) ... done
  Downloading Boruta-0.1.3.tar.gz (8.9 kB)
  Preparing metadata (setup.py) ... done
  Downloading Boruta-0.1.2.tar.gz (10 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      long_description_markdown_filename: dist = <setuptools.dist.Distribution object at 0x000002627C196B50>; attr = 'long_description_markdown_filename'; value = 'README.md'
      markdown_filename = 'C:\\Users\\HAXY8W\\AppData\\Local\\Temp\\pip-install-s6tk4h5o\\boruta_fe771e3ba2bc4fec84264bb9a059531e\\README.md'
      C:\Users\HAXY8W\.conda\envs\pycaret_py38\lib\site-packages\setuptools\dist.py:770: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      C:\Users\HAXY8W\.conda\envs\pycaret_py38\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\HAXY8W\AppData\Local\Temp\pip-install-s6tk4h5o\boruta_fe771e3ba2bc4fec84264bb9a059531e\setup.py", line 3, in <module>
          setup(name='Boruta',
        File "C:\Users\HAXY8W\.conda\envs\pycaret_py38\lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\HAXY8W\.conda\envs\pycaret_py38\lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "C:\Users\HAXY8W\.conda\envs\pycaret_py38\lib\site-packages\setuptools\dist.py", line 475, in __init__
          _Distribution.__init__(
        File "C:\Users\HAXY8W\.conda\envs\pycaret_py38\lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
          self.finalize_options()
        File "C:\Users\HAXY8W\.conda\envs\pycaret_py38\lib\site-packages\setuptools\dist.py", line 899, in finalize_options
          ep(self)
        File "C:\Users\HAXY8W\.conda\envs\pycaret_py38\lib\site-packages\setuptools\dist.py", line 919, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "c:\users\haxy8w\appdata\local\temp\pip-install-s6tk4h5o\boruta_fe771e3ba2bc4fec84264bb9a059531e\.eggs\setuptools_markdown-0.4.1-py3.8.egg\setuptools_markdown.py", line 43, in long_description_markdown_filename
          output = pypandoc.convert(markdown_filename, 'rst', format='md')
      AttributeError: module 'pypandoc' has no attribute 'convert'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

### Installation Logs

<details>

Replace this line with the installation logs.

</details>

**Comment by ngupta23** [comment]
What platform are you using?

**Comment by ngupta23** [comment]
Please try with the following (in a new python environment). 

```
pip install --pre -U pycaret
```

**Comment by moezali1** [comment]
@Hussam1 As @ngupta23 suggested can you please try to install just PyCaret without the `full` notation. Let us know if that works.

To install PyCaret 2.3.10 (stable)

```
pip install pycaret
```

To install release candidate of PyCaret 3 (unstable)

```
pip install --pre pycaret
```

**Comment by ngupta23** [comment]
Since 3.0.0 is in pre release you will have to add --pre to install it. Without it, you will get 2.3.10 only.

**Comment by sunnyguntuka** [comment]
@moezali1 / @ngupta23 , is there a way to install pycaret[full]==2.3.10? I was working on XGBoost using this version in Nov, 2022 and all of a sudden I couldn't replicate it to continue my work. Below is the snapshot of the error.

<img width="446" alt="image" src="https://user-images.githubusercontent.com/65372100/207649964-98dc4a5e-d29a-4edb-ab9b-eb4770647448.png">

**Comment by ngupta23** [comment]
@sunnyguntuka Please file a new issue with your specific issue. Mixing issues can cause confusion since the root cause may be different.
