### ISSUE TITLE
Spacy language model error in NLP example

### ISSUE THREAD

**Issue by ngupta23** [pycaret/pycaret#318]
I get the following error when running the NLP example in the examples folder. Looks like Spacy needs to be installed

```python
from pycaret.nlp import *
nlp1 = setup(data, target = 'en', session_id=123, log_experiment=True, log_plots = True, experiment_name='kiva1')
```

```
ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Traceback (most recent call last):
  File "C:\Users\Nikhil\.conda\envs\pycaret\lib\site-packages\pycaret\nlp.py", line 281, in setup
    sp = spacy.load('en_core_web_sm', disable=['parser', 'ner'])
  File "C:\Users\Nikhil\.conda\envs\pycaret\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "C:\Users\Nikhil\.conda\envs\pycaret\lib\site-packages\spacy\util.py", line 169, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nikhil\.conda\envs\pycaret\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-bf00d5b2c3ec>", line 2, in <module>
    nlp1 = setup(data, target = 'en', session_id=42, log_experiment=True, log_plots = True, experiment_name='kiva1')
  File "C:\Users\Nikhil\.conda\envs\pycaret\lib\site-packages\pycaret\nlp.py", line 283, in setup
    sys.exit('(Type Error): spacy english model is not yet downloaded. See the documentation of setup to see installation guide.')
SystemExit: (Type Error): spacy english model is not yet downloaded. See the documentation of setup to see installation guide.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nikhil\.conda\envs\pycaret\lib\site-packages\IPython\core\ultratb.py", line 1148, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "C:\Users\Nikhil\.conda\envs\pycaret\lib\site-packages\IPython\core\ultratb.py", line 316, in wrapped
    return f(*args, **kwargs)
  File "C:\Users\Nikhil\.conda\envs\pycaret\lib\site-packages\IPython\core\ultratb.py", line 350, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "C:\Users\Nikhil\.conda\envs\pycaret\lib\inspect.py", line 1502, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
AttributeError: 'tuple' object has no attribute 'tb_frame'

An exception has occurred, use %tb to see the full traceback.

---------------------------------------------------------------------------

During handling of the above exception, another exception occurred:

SystemExit: (Type Error): spacy english model is not yet downloaded. See the documentation of setup to see installation guide.
```

**Comment by ngupta23** [comment]
The solution is to add the following 2 lines to the notebook code

```python
import spacy
!python -m spacy download en_core_web_sm
```

**Comment by pycaret** [comment]
@ngupta23 This is the exception exit. Unfortunately "!python -m spacy download en_code_web_sm" cannot be part of the code. Therefore, in the documentation or also in the docstring of setup I have included that language model must be downloaded separately.

Once you have it downloaded, you won't get this error. The second line "spacy.load. .. " is part of pycaret.nlp setup function code.
