### ISSUE TITLE
alembic can't be installed

### ISSUE THREAD

**Issue by RockLeeStudio** [pycaret/pycaret#328]
ERROR: Command errored out with exit status 1:
   command: 'c:\app\python3\python.exe' 'c:\app\python3\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\100026~1\AppData\Local\Temp\pip-build-env-h4yb0t20\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "c:\app\python3\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "c:\app\python3\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "c:\app\python3\lib\site-packages\pip\__main__.py", line 16, in <module>
      from pip._internal import main as _main  # isort:skip # noqa
    File "c:\app\python3\lib\site-packages\pip\_internal\__init__.py", line 4, in <module>
      import locale
    File "c:\app\python3\lib\locale.py", line 16, in <module>
      import re
    File "c:\app\python3\lib\re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\app\python3\python.exe' 'c:\app\python3\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\100026~1\AppData\Local\Temp\pip-build-env-h4yb0t20\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.

**Comment by RockLeeStudio** [comment]
solved.
