### ISSUE TITLE
[INSTALL]: Unable to install pip install pycaret[full] in clean python 3.8 conda environment.

### ISSUE THREAD

**Issue by sorenwacker** [pycaret/pycaret#3293]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

On Rocky Linux distribution with a fresh Python 3.8 conda environment the installation ends with an error.

### Reproducible Example

```python
conda create -n pycaret python=3.8 pip
conda activate pycaret
pip install pycaret[full]
```

### Expected Behavior

Installation should be successful. 

### Actual Results

```python-traceback
Downloading Boruta-0.1.3.tar.gz (8.9 kB)
  Preparing metadata (setup.py) ... done
  Downloading Boruta-0.1.2.tar.gz (10 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      long_description_markdown_filename: dist = <setuptools.dist.Distribution object at 0x7fd5712787c0>; attr = 'long_description_markdown_filename'; value = 'README.md'
      markdown_filename = '/tmp/pip-install-9sjstgw2/boruta_d7babc9ab23143acb0eeba02946dbfce/README.md'
      /bulk/LSARP/envs/conda/pycaret/lib/python3.8/site-packages/setuptools/dist.py:770: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      /bulk/LSARP/envs/conda/pycaret/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-9sjstgw2/boruta_d7babc9ab23143acb0eeba02946dbfce/setup.py", line 3, in <module>
          setup(name='Boruta',
        File "/bulk/LSARP/envs/conda/pycaret/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/bulk/LSARP/envs/conda/pycaret/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/bulk/LSARP/envs/conda/pycaret/lib/python3.8/site-packages/setuptools/dist.py", line 475, in __init__
          _Distribution.__init__(
        File "/bulk/LSARP/envs/conda/pycaret/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/bulk/LSARP/envs/conda/pycaret/lib/python3.8/site-packages/setuptools/dist.py", line 899, in finalize_options
          ep(self)
        File "/bulk/LSARP/envs/conda/pycaret/lib/python3.8/site-packages/setuptools/dist.py", line 919, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-install-9sjstgw2/boruta_d7babc9ab23143acb0eeba02946dbfce/.eggs/setuptools_markdown-0.4.1-py3.8.egg/setuptools_markdown.py", line 43, in long_description_markdown_filename
          output = pypandoc.convert(markdown_filename, 'rst', format='md')
      AttributeError: module 'pypandoc' has no attribute 'convert'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
```


### Installed Versions

The installer is trying to install pycaret 2.3.10.

**Comment by ngupta23** [comment]
I would recommend installing the base version of pycaret first (instead of full - since full has a lot of extra dependencies that may not be used by you). After installing the base version, install any extra libraries you need manually.

**Comment by ngupta23** [comment]
Closing this for now. Feel free to reopen if the above recommendation does not resolve the issue.
