### ISSUE TITLE
[INSTALL]: Installing pycaret[full]

### ISSUE THREAD

**Issue by basitalimian1** [pycaret/pycaret#3330]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

Windows-10-10.0.19045-SP0

### Installation Method

pip install

### pycaret Version

2.3.10

### Python Version

3.8

### Description

When I run
pip install pycaret[full]

it install most of the dependencies but at last it through error

### Installation Logs

 error: subprocess-exited-with-error
  
  python setup.py egg_info did not run successfully.
  exit code: 1
  
  [26 lines of output]
  long_description_markdown_filename: dist = <setuptools.dist.Distribution object at 0x000001790EA1EEE0>; attr = 'long_description_markdown_filename'; value = 'README.md'
  markdown_filename = 'C:\\Users\\basitali.ghulam\\AppData\\Local\\Temp\\pip-install-afw_cgex\\boruta_da308496aa0d4c24bd2d30ded4488794\\README.md'
  C:\Users\basitali.ghulam\Anaconda3\envs\pycaret\lib\site-packages\setuptools\dist.py:770: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  C:\Users\basitali.ghulam\Anaconda3\envs\pycaret\lib\site-packages\setuptools\installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
    warnings.warn(
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\basitali.ghulam\AppData\Local\Temp\pip-install-afw_cgex\boruta_da308496aa0d4c24bd2d30ded4488794\setup.py", line 3, in <module>
      setup(name='Boruta',
    File "C:\Users\basitali.ghulam\Anaconda3\envs\pycaret\lib\site-packages\setuptools\__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\basitali.ghulam\Anaconda3\envs\pycaret\lib\site-packages\setuptools\_distutils\core.py", line 147, in setup
      _setup_distribution = dist = klass(attrs)
    File "C:\Users\basitali.ghulam\Anaconda3\envs\pycaret\lib\site-packages\setuptools\dist.py", line 475, in __init__
      _Distribution.__init__(
    File "C:\Users\basitali.ghulam\Anaconda3\envs\pycaret\lib\site-packages\setuptools\_distutils\dist.py", line 283, in __init__
      self.finalize_options()
    File "C:\Users\basitali.ghulam\Anaconda3\envs\pycaret\lib\site-packages\setuptools\dist.py", line 899, in finalize_options
      ep(self)
    File "C:\Users\basitali.ghulam\Anaconda3\envs\pycaret\lib\site-packages\setuptools\dist.py", line 919, in _finalize_setup_keywords
      ep.load()(self, ep.name, value)
    File "c:\users\basitali.ghulam\appdata\local\temp\pip-install-afw_cgex\boruta_da308496aa0d4c24bd2d30ded4488794\.eggs\setuptools_markdown-0.4.1-py3.8.egg\setuptools_markdown.py", line 43, in long_description_markdown_filename
      output = pypandoc.convert(markdown_filename, 'rst', format='md')
  AttributeError: module 'pypandoc' has no attribute 'convert'
  [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
​

**Comment by ngupta23** [comment]
Avoid doing the full installation. There are just too many extra packages that are installed. Instead, do the base install, then manually install any required optional packages. It will be much easier to manage this in the long run.

FYI... With the 3.0.0 release, the number of dependencies are reduced so it should help.

**Comment by ngupta23** [comment]
Closing this for now. Feel free to reopen if there are issues with the recommended approach.
