### ISSUE TITLE
[INSTALL]:   error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by syedsajjadaskari** [pycaret/pycaret#3378]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

macOS-12.6.1-x86_64-i386-64bit

### Installation Method

pip install

### pycaret Version

2.3.10

### Python Version

3.8

### Description

  Using cached Boruta-0.1.2.tar.gz (10 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      long_description_markdown_filename: dist = <setuptools.dist.Distribution object at 0x105ce4fd0>; attr = 'long_description_markdown_filename'; value = 'README.md'
      markdown_filename = '/private/var/folders/_h/57lq9q7j333144ybnyl0hz280000gn/T/pip-install-v6habxf2/boruta_3f6ace6a844940e58544387ca28946ae/README.md'

### Installation Logs

<details>

/Users/syedaskari/ML_XAI/ML_XAI_DASHBOARD/venv/lib/python3.8/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/_h/57lq9q7j333144ybnyl0hz280000gn/T/pip-install-v6habxf2/boruta_3f6ace6a844940e58544387ca28946ae/setup.py", line 3, in <module>
          setup(name='Boruta',
        File "/Users/syedaskari/ML_XAI/ML_XAI_DASHBOARD/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/Users/syedaskari/ML_XAI/ML_XAI_DASHBOARD/venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/Users/syedaskari/ML_XAI/ML_XAI_DASHBOARD/venv/lib/python3.8/site-packages/setuptools/dist.py", line 475, in __init__
          _Distribution.__init__(
        File "/Users/syedaskari/ML_XAI/ML_XAI_DASHBOARD/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/Users/syedaskari/ML_XAI/ML_XAI_DASHBOARD/venv/lib/python3.8/site-packages/setuptools/dist.py", line 899, in finalize_options
          ep(self)
        File "/Users/syedaskari/ML_XAI/ML_XAI_DASHBOARD/venv/lib/python3.8/site-packages/setuptools/dist.py", line 919, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/private/var/folders/_h/57lq9q7j333144ybnyl0hz280000gn/T/pip-install-v6habxf2/boruta_3f6ace6a844940e58544387ca28946ae/.eggs/setuptools_markdown-0.4.1-py3.8.egg/setuptools_markdown.py", line 43, in long_description_markdown_filename
          output = pypandoc.convert(markdown_filename, 'rst', format='md')
      AttributeError: module 'pypandoc' has no attribute 'convert'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

</details>

**Comment by moezali1** [comment]
@syedsajjadaskari Can you try to update pypandoc

```
pip install -U pypandoc
```

**Comment by SBFallout** [comment]
I faced the same install problem in macbook m1, google colab, win10. And I try pip install -U pypandoc as well without solving the problem.

**Comment by ngupta23** [comment]
The solution, for now, would be to not install the full version as it has a lot of extra dependencies and you may not need all of them. Please refer to this as an alternate solution: https://github.com/pycaret/pycaret/issues/3293#issuecomment-1416730490

Also, if you are using pycaret version 2.3.x, it only supprts upto Python 3.8. To use Python 3.9 and 3.10, make sure you are installing the pre-release version (in a new clean environment)

```
pip install -U --pre pycaret
```

**Comment by ngupta23** [comment]
FYI... 3.0.0 was officially released yesterday. You can try it now and check if it works for you.
