### ISSUE TITLE
[BUG]: warnings from mlflow (latest version)

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3383]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

```
from pycaret.datasets import get_data
data = get_data('juice')

from pycaret.classification import *
s = setup(data, target = 'Purchase', log_experiment = True, experiment_name = 'juice_sucks')
```

WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
2023/03/10 20:14:36 INFO mlflow.tracking.fluent: Experiment with name 'juice_sucks' does not exist. Creating a new experiment.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.

```
best = compare_models()
```
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
WARNING:root:Malformed experiment '2'. Detailed error Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 290, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 383, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1083, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\store\tracking\file_store.py", line 1076, in _read_helper
    result = read_yaml(root, file_name)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\mlflow\utils\file_utils.py", line 214, in read_yaml
    raise MissingConfigException("Yaml file '%s' does not exist." % file_path)
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\owner\mlruns\2\meta.yaml' does not exist.

### Reproducible Example

```python
see above
```

### Expected Behavior

see above

### Actual Results

```python-traceback
see above
```

### Installed Versions

rc9

**Comment by moezali1** [comment]
Not able to reproduce on colab.
