### ISSUE TITLE
[BUG]: custom model failing

### ISSUE THREAD

**Issue by moezali1** [pycaret/pycaret#3384]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

One of the example in pycaret.gitbook.io documentation is failing. This is RE: training custom model: 

(it works in PyCaret 2 but fails in PyCaret 3)

```
# load dataset 
from pycaret.datasets import get_data 
insurance= get_data('insurance') 

# init setup
from pycaret.regression import * 
reg1 = setup(data = insurance, target = 'charges')

# create custom estimator
import numpy as np
from sklearn.base import BaseEstimator
class MyOwnModel(BaseEstimator):
    
    def __init__(self):
        self.mean = 0
        
    def fit(self, X, y):
        self.mean = y.mean()
        return self
    
    def predict(self, X):
        return np.array(X.shape[0]*[self.mean])
        
# create an instance
my_own_model = MyOwnModel()

# train model
my_model_trained = create_model(my_own_model)
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_18864\16285340.py in <cell line: 28>()
     26 
     27 # train model
---> 28 my_model_trained = create_model(my_own_model)

~\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\utils\generic.py in wrapper(*args, **kwargs)
    962                 if globals_d[name] is None:
    963                     raise ValueError(message)
--> 964             return func(*args, **kwargs)
    965 
    966         return wrapper

~\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\regression\functional.py in create_model(estimator, fold, round, cross_validation, fit_kwargs, groups, experiment_custom_tags, engine, verbose, return_train_score, **kwargs)
    992     """
    993 
--> 994     return _CURRENT_EXPERIMENT.create_model(
    995         estimator=estimator,
    996         fold=fold,

~\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\regression\oop.py in create_model(self, estimator, fold, round, cross_validation, fit_kwargs, groups, experiment_custom_tags, engine, verbose, return_train_score, **kwargs)
   1287 
   1288         try:
-> 1289             return_values = super().create_model(
   1290                 estimator=estimator,
   1291                 fold=fold,

~\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py in create_model(self, estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, probability_threshold, experiment_custom_tags, verbose, return_train_score, **kwargs)
   1754             for x in kwargs
   1755         )
-> 1756         return self._create_model(
   1757             estimator=estimator,
   1758             fold=fold,

~\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py in _create_model(self, estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, probability_threshold, experiment_custom_tags, verbose, system, add_to_model_list, X_train_data, y_train_data, metrics, display, model_only, return_train_score, **kwargs)
   1521             return model
   1522 
-> 1523         model, model_fit_time, model_results, _ = self._create_model_with_cv(
   1524             model,
   1525             data_X,

~\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\pycaret_experiment\supervised_experiment.py in _create_model_with_cv(self, model, data_X, data_y, fit_kwargs, round, cv, groups, metrics, refit, system, display, return_train_score)
   1115             model_fit_start = time.time()
   1116             with redirect_output(self.logger):
-> 1117                 scores = cross_validate(
   1118                     pipeline_with_model,
   1119                     data_X,

~\anaconda3\envs\pycaretrc5\lib\site-packages\sklearn\model_selection\_validation.py in cross_validate(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, error_score)
    283     )
    284 
--> 285     _warn_or_raise_about_fit_failures(results, error_score)
    286 
    287     # For callabe scoring, the return type is only know after calling. If the

~\anaconda3\envs\pycaretrc5\lib\site-packages\sklearn\model_selection\_validation.py in _warn_or_raise_about_fit_failures(results, error_score)
    365                 f"Below are more details about the failures:\n{fit_errors_summary}"
    366             )
--> 367             raise ValueError(all_fits_failed_message)
    368 
    369         else:

ValueError: 
All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\pipeline.py", line 252, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\memory.py", line 594, in __call__
    return self._cached_call(args, kwargs)[0]
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 310, in _cached_call
    func_id, args_id = self._get_output_identifiers(*args, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\memory.py", line 638, in _get_output_identifiers
    argument_hash = self._get_argument_hash(*args, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 251, in _get_argument_hash
    return fast_hash(
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 239, in fast_hash
    return hasher.hash(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 94, in hash
    self.dump(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 487, in dump
    self.save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 206, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 176, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 140, in _batch_setitems
    Pickler._batch_setitems(self, iter(sorted(items)))
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 997, in _batch_setitems
    save(v)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 206, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 176, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 687, in save_reduce
    save(cls)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 206, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 176, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 111, in save_global
    Pickler.save_global(self, obj, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 1070, in save_global
    raise PicklingError(
_pickle.PicklingError: ("Can't pickle <class '__main__.MyOwnModel'>: it's not found as __main__.MyOwnModel", 'PicklingError while hashing {\'transformer\': MyOwnModel(), \'X\':       age  sex        bmi  children  smoker  region_northeast  region_southeast  region_northwest  region_southwest\n94   18.0  1.0  33.535000       0.0     1.0               1.0               0.0               0.0               0.0\n95   18.0  1.0  41.139999       0.0     0.0               0.0               1.0               0.0               0.0\n96   23.0  0.0  34.865002       0.0     0.0               1.0               0.0               0.0               0.0\n97   57.0  1.0  40.369999       0.0     0.0               0.0               1.0               0.0               0.0\n98   62.0  0.0  39.160000       0.0     0.0               0.0               1.0               0.0               0.0\n..    ...  ...        ...       ...     ...               ...               ...               ...               ...\n931  44.0  1.0  29.735001       2.0     0.0               1.0               0.0               0.0               0.0\n932  39.0  0.0  32.799999       0.0     0.0               0.0               0.0               0.0               1.0\n933  59.0  1.0  24.700001       0.0     0.0               1.0               0.0               0.0               0.0\n934  19.0  0.0  28.309999       0.0     1.0               0.0               0.0               1.0               0.0\n935  42.0  0.0  37.900002       0.0     0.0               0.0               0.0               0.0               1.0\n\n[842 rows x 9 columns], \'y\': 94     34617.839844\n95      1146.796631\n96      2899.489258\n97     10982.500977\n98     13470.804688\n           ...     \n931    32108.662109\n932     5649.714844\n933    12323.935547\n934    17468.984375\n935     6474.013184\nName: charges, Length: 842, dtype: float32, \'message\': None, \'**\': {}}: PicklingError("Can\'t pickle <class \'__main__.MyOwnModel\'>: it\'s not found as __main__.MyOwnModel")')

--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\pipeline.py", line 252, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\memory.py", line 594, in __call__
    return self._cached_call(args, kwargs)[0]
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 310, in _cached_call
    func_id, args_id = self._get_output_identifiers(*args, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\memory.py", line 638, in _get_output_identifiers
    argument_hash = self._get_argument_hash(*args, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 251, in _get_argument_hash
    return fast_hash(
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 239, in fast_hash
    return hasher.hash(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 94, in hash
    self.dump(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 487, in dump
    self.save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 206, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 176, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 140, in _batch_setitems
    Pickler._batch_setitems(self, iter(sorted(items)))
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 997, in _batch_setitems
    save(v)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 206, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 176, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 687, in save_reduce
    save(cls)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 206, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 176, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 111, in save_global
    Pickler.save_global(self, obj, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 1070, in save_global
    raise PicklingError(
_pickle.PicklingError: ("Can't pickle <class '__main__.MyOwnModel'>: it's not found as __main__.MyOwnModel", 'PicklingError while hashing {\'transformer\': MyOwnModel(), \'X\':       age  sex        bmi  children  smoker  region_northeast  region_southeast  region_southwest  region_northwest\n0    30.0  1.0  37.430000       3.0     0.0               1.0               0.0               0.0               0.0\n1    36.0  1.0  34.430000       2.0     0.0               0.0               1.0               0.0               0.0\n2    59.0  1.0  37.400002       0.0     0.0               0.0               0.0               1.0               0.0\n3    56.0  1.0  34.430000       0.0     0.0               0.0               1.0               0.0               0.0\n4    46.0  0.0  27.719999       1.0     0.0               0.0               1.0               0.0               0.0\n..    ...  ...        ...       ...     ...               ...               ...               ...               ...\n931  44.0  1.0  29.735001       2.0     0.0               1.0               0.0               0.0               0.0\n932  39.0  0.0  32.799999       0.0     0.0               0.0               0.0               1.0               0.0\n933  59.0  1.0  24.700001       0.0     0.0               1.0               0.0               0.0               0.0\n934  19.0  0.0  28.309999       0.0     1.0               0.0               0.0               0.0               1.0\n935  42.0  0.0  37.900002       0.0     0.0               0.0               0.0               1.0               0.0\n\n[842 rows x 9 columns], \'y\': 0       5428.727539\n1       5584.305664\n2      21797.000000\n3      10594.225586\n4       8232.638672\n           ...     \n931    32108.662109\n932     5649.714844\n933    12323.935547\n934    17468.984375\n935     6474.013184\nName: charges, Length: 842, dtype: float32, \'message\': None, \'**\': {}}: PicklingError("Can\'t pickle <class \'__main__.MyOwnModel\'>: it\'s not found as __main__.MyOwnModel")')

--------------------------------------------------------------------------------
3 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\pipeline.py", line 252, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\memory.py", line 594, in __call__
    return self._cached_call(args, kwargs)[0]
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 310, in _cached_call
    func_id, args_id = self._get_output_identifiers(*args, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\memory.py", line 638, in _get_output_identifiers
    argument_hash = self._get_argument_hash(*args, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 251, in _get_argument_hash
    return fast_hash(
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 239, in fast_hash
    return hasher.hash(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 94, in hash
    self.dump(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 487, in dump
    self.save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 206, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 176, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 140, in _batch_setitems
    Pickler._batch_setitems(self, iter(sorted(items)))
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 997, in _batch_setitems
    save(v)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 206, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 176, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 687, in save_reduce
    save(cls)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 206, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 176, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 111, in save_global
    Pickler.save_global(self, obj, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 1070, in save_global
    raise PicklingError(
_pickle.PicklingError: ("Can't pickle <class '__main__.MyOwnModel'>: it's not found as __main__.MyOwnModel", 'PicklingError while hashing {\'transformer\': MyOwnModel(), \'X\':       age  sex        bmi  children  smoker  region_northeast  region_southeast  region_southwest  region_northwest\n0    30.0  1.0  37.430000       3.0     0.0               1.0               0.0               0.0               0.0\n1    36.0  1.0  34.430000       2.0     0.0               0.0               1.0               0.0               0.0\n2    59.0  1.0  37.400002       0.0     0.0               0.0               0.0               1.0               0.0\n3    56.0  1.0  34.430000       0.0     0.0               0.0               1.0               0.0               0.0\n4    46.0  0.0  27.719999       1.0     0.0               0.0               1.0               0.0               0.0\n..    ...  ...        ...       ...     ...               ...               ...               ...               ...\n931  44.0  1.0  29.735001       2.0     0.0               1.0               0.0               0.0               0.0\n932  39.0  0.0  32.799999       0.0     0.0               0.0               0.0               1.0               0.0\n933  59.0  1.0  24.700001       0.0     0.0               1.0               0.0               0.0               0.0\n934  19.0  0.0  28.309999       0.0     1.0               0.0               0.0               0.0               1.0\n935  42.0  0.0  37.900002       0.0     0.0               0.0               0.0               1.0               0.0\n\n[843 rows x 9 columns], \'y\': 0       5428.727539\n1       5584.305664\n2      21797.000000\n3      10594.225586\n4       8232.638672\n           ...     \n931    32108.662109\n932     5649.714844\n933    12323.935547\n934    17468.984375\n935     6474.013184\nName: charges, Length: 843, dtype: float32, \'message\': None, \'**\': {}}: PicklingError("Can\'t pickle <class \'__main__.MyOwnModel\'>: it\'s not found as __main__.MyOwnModel")')

--------------------------------------------------------------------------------
1 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\pipeline.py", line 252, in fit
    fitted_estimator = self._memory_fit(
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\memory.py", line 594, in __call__
    return self._cached_call(args, kwargs)[0]
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 310, in _cached_call
    func_id, args_id = self._get_output_identifiers(*args, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\memory.py", line 638, in _get_output_identifiers
    argument_hash = self._get_argument_hash(*args, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 251, in _get_argument_hash
    return fast_hash(
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 239, in fast_hash
    return hasher.hash(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 94, in hash
    self.dump(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 487, in dump
    self.save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 206, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 176, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 971, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 140, in _batch_setitems
    Pickler._batch_setitems(self, iter(sorted(items)))
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 997, in _batch_setitems
    save(v)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 206, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 176, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 603, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 687, in save_reduce
    save(cls)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 206, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\pycaret\internal\memory.py", line 176, in save
    super().save(obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 560, in save
    f(self, obj)  # Call unbound method with explicit self
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\site-packages\joblib\hashing.py", line 111, in save_global
    Pickler.save_global(self, obj, **kwargs)
  File "C:\Users\owner\anaconda3\envs\pycaretrc5\lib\pickle.py", line 1070, in save_global
    raise PicklingError(
_pickle.PicklingError: ("Can't pickle <class '__main__.MyOwnModel'>: it's not found as __main__.MyOwnModel", 'PicklingError while hashing {\'transformer\': MyOwnModel(), \'X\':       age  sex        bmi  children  smoker  region_northeast  region_southeast  region_southwest  region_northwest\n0    30.0  1.0  37.430000       3.0     0.0               1.0               0.0               0.0               0.0\n1    36.0  1.0  34.430000       2.0     0.0               0.0               1.0               0.0               0.0\n2    59.0  1.0  37.400002       0.0     0.0               0.0               0.0               1.0               0.0\n3    56.0  1.0  34.430000       0.0     0.0               0.0               1.0               0.0               0.0\n4    46.0  0.0  27.719999       1.0     0.0               0.0               1.0               0.0               0.0\n..    ...  ...        ...       ...     ...               ...               ...               ...               ...\n838  51.0  0.0  21.559999       1.0     0.0               0.0               1.0               0.0               0.0\n839  31.0  0.0  21.754999       0.0     0.0               0.0               0.0               0.0               1.0\n840  23.0  1.0  27.360001       1.0     0.0               0.0               0.0               0.0               1.0\n841  31.0  0.0  32.775002       2.0     0.0               0.0               0.0               0.0               1.0\n842  39.0  1.0  29.600000       4.0     0.0               0.0               0.0               1.0               0.0\n\n[843 rows x 9 columns], \'y\': 0       5428.727539\n1       5584.305664\n2      21797.000000\n3      10594.225586\n4       8232.638672\n           ...     \n838     9855.131836\n839     4134.082520\n840     2789.057373\n841     5327.400391\n842     7512.267090\nName: charges, Length: 843, dtype: float32, \'message\': None, \'**\': {}}: PicklingError("Can\'t pickle <class \'__main__.MyOwnModel\'>: it\'s not found as __main__.MyOwnModel")')

### Reproducible Example

```python
see above
```

### Expected Behavior

see above

### Actual Results

```python-traceback
see above
```

### Installed Versions

rc9

**Comment by moezali1** [comment]
tested using `master` branch on 3/15/2023. The issue has been fixed.
