### ISSUE TITLE
option to deploy to JVM environments

### ISSUE THREAD

**Issue by yairdata** [pycaret/pycaret#345]
would be good to be able to export the model + transformation pipeline to format that will allow to infer in a real time environment like a JVM.
pmml, mleap or native API will be great options.

**Comment by pycaret** [comment]
@yairdata Thanks for suggestion. I don't have experience working with pmml or mleap. Would you like to work on this issue? Please let me know. We can discuss before you start working on this (if you want). Reach out moez.ali@queensu.ca

**Comment by vruusmann** [comment]
The PyCaret training process yields a data preparation pipeline and a model. They can be manually combined into an `PMMLPipeline` object and then converted to PMML representation using the [SkLearn2PMML](https://github.com/jpmml/sklearn2pmml) package as usual.

Example:
```python
from pycaret.regression import *

# Do the standard PyCaret stuff

from pycaret.regression import prep_pipe
from sklearn2pmml.pipeline import PMMLPipeline

pmml_pipeline = PMMLPipeline([
	("prep_pipe", prep_pipe),
	("final_model", final_model)
])

from sklearn2pmml import sklearn2pmml

sklearn2pmml(pmml_pipeline, "regression.pmml")
```

**Comment by vruusmann** [comment]
Cross-linking with https://github.com/pycaret/pycaret/issues/114

**Comment by pycaret** [comment]
@vruusmann How do we load back `pmml` pipeline in notebook?

**Comment by pycaret** [comment]
@vruusmann When I try to save `prep_pipe` I get this error:

Standard output is empty
Standard error:
Aug 09, 2020 2:17:06 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Aug 09, 2020 2:17:06 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 15 ms.
Exception in thread "main" java.lang.IllegalArgumentException: The object (Python class numpy.core.multiarray._reconstruct) is not a PMMLPipeline
	at org.jpmml.sklearn.Main.run(Main.java:192)
	at org.jpmml.sklearn.Main.main(Main.java:151)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-21-eba2fcb48313> in <module>
      1 prep_pipe = get_config('prep_pipe')
----> 2 save_model(prep_pipe, model_name = 'prep-pipe-pmml', type = 'pmml')

~\pycaret\pycaret\pycaret\classification.py in save_model(model, model_name, type, model_only, verbose)
   9299         model_name = model_name + '.pmml'
   9300         from sklearn2pmml import sklearn2pmml
-> 9301         sklearn2pmml(pmml_pipeline, model_name)
   9302 
   9303     logger.info(str(model_name) + ' saved in current working directory')

~\Anaconda3\envs\pycaret-dev\lib\site-packages\sklearn2pmml\__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    256                                 print("Standard error is empty")
    257                 if retcode:
--> 258                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    259         finally:
    260                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams

**Comment by pycaret** [comment]
@vruusmann I have recently refactor `save_model` function to append estimator as a last step of pipeline so that only one object i.e. `Pipeline`  is saved as `pkl`, where last item of the pipeline is a trained `estimator`. (see `/pycaret/classification.py` on master). What I am trying to do now is add a parameter `type` in `save_model` so that when somebody selects `pmml` as type the entire `Pipeline` which is a combination of `prep_pipe` and `estimator` and stored in a parameter called `model_` is converted as `pmml` and saved on local disk. However I realized in doing so I am getting an error from `sklearn2pmml` due to `prep_pipe` object. (see error above). I also tried to just save estimator instead of the entire pipeline (this is not ideal though). At estimator level, I am having issues with these estimators in `classification.py`:

- lr 
- gpc
- lda 
- qda,
- ada,
- catboost

I am planning to add this feature in `2.1` (targetting release by end of Aug 2020). 

Are you able to help?

**Comment by vruusmann** [comment]
> Exception in thread "main" java.lang.IllegalArgumentException: The object (Python class numpy.core.multiarray._reconstruct) is not a PMMLPipeline

The SkLearn2PMML package saves the `PMMLPipeline` object to a temporary file in Pickle data format, and then executes a Java command-line application to perform the conversion work.

The above exception means that the Java exception is looking into the pickle file, but cannot find the `PMMLPipeline` object in it. Instead, there's an unexpected `numpy.ndarray` object.

TBH, I got this exception myself, when making the above comment: https://github.com/pycaret/pycaret/issues/345#issuecomment-668748620

It appears to be the case that PyCaret is meddling with the definition of `joblib.dump` function, so that the `PMMLPipeline` object somehow gets replaced with the `numpy.array` object. I've never seen this "object replacement" happen before, so I kind of blame PyCaret here (overriding the `joblib.dump` using globals somehow).

The workaround is to save the `PMMLPipeline` object manually, using the `pickle.dump` function:

```python
pmml_pipeline = PMMLPipeline([
	("prep_pipe", prep_pipe),
	("final_model", final_model)
])

import pickle

with open("regression.pkl", "wb") as pf:
	pickle.dump(pmml_pipeline, pf
```

And then execute the [JPMML-SkLearn](https://github.com/jpmml/jpmml-sklearn) command-line application manually on the `regression.pkl` file.

**Comment by vruusmann** [comment]
> How do we load back pmml pipeline in notebook?

There is no going back from PMML to a (ML framework native-) Python object. PMML documents can be evaluated using PMML engines, such as [JPMML-Evaluator](https://github.com/jpmml/jpmml-evaluator) for Java or [JPMML-Evaluator-Python](https://github.com/jpmml/jpmml-evaluator-python) for Python.

> I have recently refactor save_model function to append estimator as a last step of pipeline so that only one object i.e. Pipeline is saved as pkl

I looked into `save_model` functions about a week ago when I was trying to figure out how to fetch all the pieces (ie. `prep_pipe` and `final_model`). Sure, replacing an array `[prep_pipe, final_model]` with a single pipeline object is a step in the right direction.

Perhaps you should introduce a PyCaret-specific `Pipeline` subclass, at least for persistence (save/load) purposes? A custom pipeline class would make it possible to store all sorts of metadata in there (target transformations etc), plus make it easier for third parties to establish the identity of the pipeline object. For example, if the pickle file contains class `pycaret.pipeline.PyCaretPipeline`, then it would be fairly easy to associate it with the PyCaret framework.

 > I am trying to do now is add a parameter type in save_model...

PMML is a one way street. The save operation translates low- to medium-level PyCaret/Scikit-Learn/Python representation (binary, machine-oriented) to a high-level PMML representation (text-based, human-oriented).

Perhaps you should keep `save_model`/`load_model` functions unchanged, and if necessary, introduce a separate `export_model` function? For starters, perhaps it will be sufficient if PyCaret documentation simply states that some PyCaret pipelines can be translated to different representations using different tools (plus examples)?

> At estimator level, I am having issues with these estimators in classification.py

Some Scikit-Learn estimator to PMML converters have not been built yet, and some only work for limited configurations.

The PMML export functionality should come with a "limited support" disclaimer ("limited export functionality, dependent on a third-party package").

For starters, the SkLearn2PMML package first needs to learn about custom PyCaret transformation classes (eg `DataTypes_Auto_infer`), so let's not rush it.

**Comment by mahmoudyusof** [comment]
I've been trying with this for a while now and it seems that saving the model alone is working without a problem except with `lr` you need to set the `multi_class` kwarg to either `ovr` or `multinomial`, it cannot be left as `auto`, however saving the pipeline causes the java error that @pycaret  saw 
```
Standard output is empty
Standard error:
Aug 09, 2020 2:17:06 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Aug 09, 2020 2:17:06 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 15 ms.
Exception in thread "main" java.lang.IllegalArgumentException: The object (Python class numpy.core.multiarray._reconstruct) is not a PMMLPipeline
at org.jpmml.sklearn.Main.run(Main.java:192)
at org.jpmml.sklearn.Main.main(Main.java:151)
```

**Comment by mahmoudyusof** [comment]
after trying for a while I've come to the same conclusion, however, saving the model only works without a problem except when it comes to `LogisticRegression`, one must explicitly specify the `multi_class` argument to either `ovr` or `multinomial`, this is possible in pycaret==2.0 so
```
lr = create_model('lr', multi_class='ovr')
save_model(lr, format="pmml", model_only=True) 
```
this code works, but I don't think it would be of great use.

**Comment by moezali1** [comment]
Closing as part of the 4.0 backlog cleanup — see #4177.

PyCaret 4.0 is a ground-up rewrite (OOP-only API, sklearn-native engine, Python 3.11+, sklearn ≥ 1.7) and almost all pre-4.0 issues either reference removed APIs (`setup()`, `plot_model`, `evaluate_model`, `interpret_model`, `automl`, the legacy time-series module, the Streamlit dashboard, …) or no longer reproduce on the new code path.

**If this still affects you in 4.0, please re-file as a new issue** with:

- the experiment constructor call (`Experiment(...)`),
- the operation that fails,
- the full traceback,
- your Python / sklearn / pycaret versions.

Resources for 4.0:

- Docs: https://pycaret.org/docs
- Migrate from 3.x: https://pycaret.org/docs/guides/migrating-from-3-x
- API reference: https://pycaret.org/reference
- FAQ: https://pycaret.org/docs/resources/faqs

Thanks for filing — and apologies for the long latency. The repo had drifted; we're starting clean.
