### ISSUE TITLE
[BUG]: "interpret_model" not working correctly

### ISSUE THREAD

**Issue by loschicosdeldato** [pycaret/pycaret#3468]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Hello there!

When trying to interpret the model through the **"interpret_model"** funtion the following error pops up.

`TypeError: This function only supports tree based models for binary classification: dt, et, catboost, xgboost, rf, lightgbm.`

The thing is that, the models that I am including in the setup are tree based models which doesnt match with the raised error. This is the printing of the final step inside my pipeline (`print(final_model[-1])`).

```
                ('actual_estimator',
                 <catboost.core.CatBoostClassifier object at 0x7f7b3f336fd0>)]
```

**pycaret version: 3.0.0**

### Reproducible Example

```python
from pycaret.classification import *
import mlflow 
from typing import Union, List, Any, Tuple
import pandas as pd
#from sklearn.model_selection import train_test_split
import logging
import os

class Model():
    def __init__(self,
                target_label: str,
                mlflow_tracking_uri: str,
                model_version: str):
        self.target_label = target_label
        self.model_version = model_version
        mlflow.set_tracking_uri(mlflow_tracking_uri)

    def fit(self,
            X: pd.DataFrame,
            y: pd.Series):
        
        # create a dataframe with the target label
        df = X
        features = df.columns
        # add the target label to the dataframe
        df[self.target_label] = y
        
        # setup the experiment
        setup(
            data = df,
            data_split_stratify=["target"],
            target = self.target_label,
            max_encoding_ohe=0,# only one hot encode the target label
            log_experiment=True,# log experiment in mlflow
            log_plots= True, # pycaret 3.1.0 milestone to support logging plots in MLflow
            experiment_name=self.model_version,
            n_jobs=None,
            verbose=False,
            session_id=123,
        )
        
        # Only include the top 3 models
        # sort by AUC as it is a metric not affected by imbalanceness
        best_model = compare_models(include=["lightgbm","xgboost","catboost"], sort = "AUC", verbose=False)

        # Tune the best model
        tuned_model = tune_model(best_model, optimize = "AUC", verbose=False)

        # train model with the entire train dataset    
        final_model = finalize_model(tuned_model)
        
        # interpret the model with SHAP(Shapley Additive exPlanations)
        # It only supports tree based algorithms.
        # pycaret 3.1.0 milestone to support logging plots in MLflow
        print(final_model)
        print(final_model[-1])

        # Create a folder to save the SHAP plots
        folder_path = "artifacts/metrics/plots/{}".format(self.model_version) # Replace with the path to the folder you want to create

        if not os.path.exists(folder_path):
            os.makedirs(folder_path)
            logging.info("SHAP Plots Folder created at", folder_path)
        else:
            logging.info("SHAP Plots Folder already exists at", folder_path)

        interpret_model(final_model,plot='summary',save='{}/shap_summary_plot.png'.format(folder_path))
        interpret_model(final_model,plot='reason',save='{}/shap_reason_plot.png'.format(folder_path))
        interpret_model(final_model,plot='error',save='{}/shap_error_plot.png'.format(folder_path))
        interpret_model(final_model,plot='rfe',save='{}/shap_rfe_plot.png'.format(folder_path))
        interpret_model(final_model,plot='msa',save='{}/shap_msa_plot.png'.format(folder_path))
```

### Expected Behavior

- SHAP plots run without any error
- Plots to be saved in the selected folder
- MLflow tracks the plots as artifacts loaded to the corresponding experiment

### Actual Results

```python-traceback
('actual_estimator',
                 <catboost.core.CatBoostClassifier object at 0x7f7b3f336fd0>)],
         verbose=False)
<catboost.core.CatBoostClassifier object at 0x7f7b3f336fd0>
Traceback (most recent call last):
  File "src/train/train.py", line 46, in <module>
    main()
  File "src/train/train.py", line 42, in main
    pipeline = train_model(data)
  File "src/train/train.py", line 31, in train_model
    pipeline.fit(df, y)
  File "/home/makingscience/.cache/pypoetry/virtualenvs/model-delio-leads-scoring-2ot0QuGS-py3.8/lib/python3.8/site-packages/sklearn/pipeline.py", line 405, in fit
    self._final_estimator.fit(Xt, y, **fit_params_last_step)
  File "/home/makingscience/code_rocket/model-delio-leads-scoring/src/train/pipeline/model.py", line 73, in fit
    interpret_model(final_model,plot='summary',save='{}/shap_summary_plot.png'.format(folder_path))
  File "/home/makingscience/.cache/pypoetry/virtualenvs/model-delio-leads-scoring-2ot0QuGS-py3.8/lib/python3.8/site-packages/pycaret/utils/generic.py", line 965, in wrapper
    return func(*args, **kwargs)
  File "/home/makingscience/.cache/pypoetry/virtualenvs/model-delio-leads-scoring-2ot0QuGS-py3.8/lib/python3.8/site-packages/pycaret/classification/functional.py", line 1937, in interpret_model
    return _CURRENT_EXPERIMENT.interpret_model(
  File "/home/makingscience/.cache/pypoetry/virtualenvs/model-delio-leads-scoring-2ot0QuGS-py3.8/lib/python3.8/site-packages/pycaret/classification/oop.py", line 2283, in interpret_model
    return super().interpret_model(
  File "/home/makingscience/.cache/pypoetry/virtualenvs/model-delio-leads-scoring-2ot0QuGS-py3.8/lib/python3.8/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py", line 4065, in interpret_model
    raise TypeError(
TypeError: This function only supports tree based models for binary classification: dt, et, catboost, xgboost, rf, lightgbm.
```

### Installed Versions

<details>
Replace this line with the output of the version code above.
</details>

**Comment by OleksandrSG** [comment]
I also can't interpret saved/loaded tree model((
only fresh trained can be interpreted in pycaret.
any solution?

**Comment by moezali1** [comment]
Closing as part of the 4.0 backlog cleanup — see #4177.

PyCaret 4.0 is a ground-up rewrite (OOP-only API, sklearn-native engine, Python 3.11+, sklearn ≥ 1.7) and almost all pre-4.0 issues either reference removed APIs (`setup()`, `plot_model`, `evaluate_model`, `interpret_model`, `automl`, the legacy time-series module, the Streamlit dashboard, …) or no longer reproduce on the new code path.

**If this still affects you in 4.0, please re-file as a new issue** with:

- the experiment constructor call (`Experiment(...)`),
- the operation that fails,
- the full traceback,
- your Python / sklearn / pycaret versions.

Resources for 4.0:

- Docs: https://pycaret.org/docs
- Migrate from 3.x: https://pycaret.org/docs/guides/migrating-from-3-x
- API reference: https://pycaret.org/reference
- FAQ: https://pycaret.org/docs/resources/faqs

Thanks for filing — and apologies for the long latency. The repo had drifted; we're starting clean.
