### ISSUE TITLE
Automatically handle `add_metric` with string target labels

### ISSUE THREAD

**Issue by bottyBotz** [pycaret/pycaret#3491]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [x] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Similar issue to those identified in https://github.com/pycaret/pycaret/issues/3351.

Specificity is just the recall for the negative class in a binary classification task. Therefore we just return scikit-learn's recall function where the pos_label is 0. We utilize the zero_division parameter to return 1 if there is a zero_division error. It is worth noting that the default behavior of scikit-learn's recall function sets zero_division = 'warn' which is equivalent to zero_division = 0.

### Reproducible Example

```python
from pycaret.datasets import get_data
from sklearn.metrics import recall_score
data = get_data('juice')

from pycaret.classification import *
s = setup(data, target = 'Purchase', session_id = 123)

# create a custom function
def specificity(y_true, y_pred):
    return recall_score(y_true
                        , y_pred
                        , pos_label=0
                        , zero_division=1)


# add metric to PyCaret
add_metric('specificity', 'specificity', specificity, greater_is_better = True)

lr = create_model('lr')
```

### Expected Behavior

Expected behavior would be that specificity is correctly calculated. 

### Actual Results

```python-traceback
Actual results are that all zeros are returned.

![image](https://user-images.githubusercontent.com/67231425/233394122-b4954d33-64e8-4d29-901f-a182a9f9c22a.png)
```

### Installed Versions

<details>
3.0.0
</details>

**Comment by bottyBotz** [comment]
In the master branch, I needed to use slightly different code when testing to ensure the result set was pulled back. That reproducible code is below:

`from pycaret.datasets import get_data
from sklearn.metrics import recall_score
data = get_data('juice')

from pycaret.classification import *
s = setup(data, target = 'Purchase', session_id = 123)

# create a custom function
def specificity(y_true, y_pred):
    return recall_score(y_true
                        , y_pred
                        , pos_label=0
                        , zero_division=1)


# add metric to PyCaret
add_metric('specificity', 'specificity', specificity, greater_is_better = True)

lr = create_model('lr')

lr_results = pull()

lr_results`

**Comment by moezali1** [comment]
warnings.warn(

2023-05-05 20:42:10,937:WARNING:/usr/local/lib/python3.10/dist-packages/pycaret/internal/metrics.py:192: FitFailedWarning: Metric 'make_scorer(specificity)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pycaret/internal/metrics.py", line 184, in _score
    return super()._score(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 282, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "<ipython-input-33-5a9fd694da4e>", line 4, in specificity
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 2098, in recall_score
    _, r, _, _ = precision_recall_fscore_support(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 1573, in precision_recall_fscore_support
    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 1382, in _check_set_wise_labels
    raise ValueError(
ValueError: pos_label=0 is not a valid label. It should be one of ['CH', 'MM']

  warnings.warn(

2023-05-05 20:42:11,581:WARNING:/usr/local/lib/python3.10/dist-packages/pycaret/internal/metrics.py:192: FitFailedWarning: Metric 'make_scorer(specificity)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pycaret/internal/metrics.py", line 184, in _score
    return super()._score(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_scorer.py", line 282, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "<ipython-input-33-5a9fd694da4e>", line 4, in specificity
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 2098, in recall_score
    _, r, _, _ = precision_recall_fscore_support(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 1573, in precision_recall_fscore_support
    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py", line 1382, in _check_set_wise_labels
    raise ValueError(
ValueError: pos_label=0 is not a valid label. It should be one of ['CH', 'MM']

  warnings.warn(

2023-05-05 20:42:11,594:INFO:Calculating mean and std
2023-05-05 20:42:11,597:INFO:Creating metrics dataframe
2023-05-05 20:42:11,661:INFO:Finalizing model
2023-05-05 20:42:12,081:INFO:Uploading results into container
2023-05-05 20:42:12,083:INFO:Uploading model into container now
2023-05-05 20:42:12,134:INFO:_master_model_container: 3
2023-05-05 20:42:12,134:INFO:_display_container: 5
2023-05-05 20:42:12,136:INFO:LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=123, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
2023-05-05 20:42:12,136:INFO:create_model() successfully completed......................................

**Comment by Yard1** [comment]
```
2023-05-14 21:17:44,845:WARNING:/home/ubuntu/pycaret/pycaret/internal/metrics.py:192: FitFailedWarning: Metric 'make_scorer(specificity)' failed and error score 0.0 has been returned instead. If this is a custom metric, this usually means that the error is in the metric code. Full exception below:
Traceback (most recent call last):
  File "/home/ubuntu/pycaret/pycaret/internal/metrics.py", line 184, in _score
    return super()._score(
  File "/home/ubuntu/pycaret/clean/lib/python3.8/site-packages/sklearn/metrics/_scorer.py", line 282, in _score
    return self._sign * self._score_func(y_true, y_pred, **self._kwargs)
  File "/tmp/ipykernel_596908/3682197142.py", line 10, in specificity
  File "/home/ubuntu/pycaret/clean/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 2098, in recall_score
    _, r, _, _ = precision_recall_fscore_support(
  File "/home/ubuntu/pycaret/clean/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1573, in precision_recall_fscore_support
    labels = _check_set_wise_labels(y_true, y_pred, average, labels, pos_label)
  File "/home/ubuntu/pycaret/clean/lib/python3.8/site-packages/sklearn/metrics/_classification.py", line 1382, in _check_set_wise_labels
    raise ValueError(
ValueError: pos_label=0 is not a valid label. It should be one of ['CH', 'MM']
```

This is correctly propagated to log on master.

**Comment by Yard1** [comment]
I'll leave this open as an improvement to automatically handle this case.
