### ISSUE TITLE
[BUG]: error occured after execute second plot_model

### ISSUE THREAD

**Issue by tankienleong** [pycaret/pycaret#3581]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [ ] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

_tkinter.TclError: invalid command name ".!navigationtoolbar2tk.!button2" error occurred after execute second plot_model

### Reproducible Example

```python
from pycaret.datasets import get_data
from pycaret.classification import *

juice = get_data('juice')  
setup(data=juice,  target='Purchase')
logr = create_model('lr')
tuned_logr = tune_model(logr) 

plot_model(estimator = tuned_logr, plot = 'feature_all')
plot_model(estimator = tuned_logr, plot = 'confusion_matrix') 
plot_model(estimator = tuned_logr, plot = 'auc') 
plot_model(estimator = tuned_logr, plot = 'pr') 
plot_model(estimator = tuned_logr, plot = 'error')
```

### Expected Behavior

all plot show display without error

### Actual Results

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/pycaret/utils/generic.py", line 965, in wrapper
    return func(*args, **kwargs)
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/pycaret/classification/functional.py", line 1747, in plot_model
    return _CURRENT_EXPERIMENT.plot_model(
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/pycaret/classification/oop.py", line 2095, in plot_model
    return super().plot_model(
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/pycaret/internal/pycaret_experiment/tabular_experiment.py", line 2078, in plot_model
    return self._plot_model(
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/pycaret/internal/pycaret_experiment/tabular_experiment.py", line 1944, in _plot_model
    ret = locals()[plot]()
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/pycaret/internal/pycaret_experiment/tabular_experiment.py", line 1189, in pr
    return show_yellowbrick_plot(
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/pycaret/internal/plots/yellowbrick.py", line 115, in show_yellowbrick_plot
    visualizer.show(clear_figure=True)
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/yellowbrick/base.py", line 249, in show
    self.fig.clear()
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/matplotlib/figure.py", line 2806, in clear
    super().clear(keep_observers=keep_observers)
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/matplotlib/figure.py", line 957, in clear
    self.delaxes(ax)  # Remove ax from self._axstack.
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/matplotlib/figure.py", line 925, in delaxes
    self._axobservers.process("_axes_change_event", self)
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 292, in process
    self.exception_handler(exc)
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 96, in _exception_printer
    raise exc
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/matplotlib/cbook/__init__.py", line 287, in process
    func(*args, **kwargs)
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/matplotlib/figure.py", line 2921, in <lambda>
    self._axobservers.connect("_axes_change_event", lambda arg: func(arg))
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 2799, in notify_axes_change
    self.toolbar.update()
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/matplotlib/backend_bases.py", line 3302, in update
    self.set_history_buttons()
  File "/home/test/.pyenv/versions/pycaret_venv/lib/python3.8/site-packages/matplotlib/backends/_backend_tk.py", line 738, in set_history_buttons
    self._buttons['Back']['state'] = state_map[can_back]
  File "/home/test/.pyenv/versions/3.8.10/lib/python3.8/tkinter/__init__.py", line 1657, in __setitem__
    self.configure({key: value})
  File "/home/test/.pyenv/versions/3.8.10/lib/python3.8/tkinter/__init__.py", line 1646, in configure
    return self._configure('configure', cnf, kw)
  File "/home/test/.pyenv/versions/3.8.10/lib/python3.8/tkinter/__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!navigationtoolbar2tk.!button2"
```

### Installed Versions

<details>
System:
    python: 3.8.10 (default, Apr  4 2023, 16:32:19)  [GCC 7.5.0]
executable: /home/test/.pyenv/versions/pycaret_venv/bin/python3
   machine: Linux-5.4.0-149-generic-x86_64-with-glibc2.2.5

PyCaret required dependencies:
                 pip: 23.1.2
          setuptools: 56.0.0
             pycaret: 3.0.0
             IPython: 7.34.0
          ipywidgets: 7.7.5
                tqdm: 4.64.1
               numpy: 1.23.5
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.9.1
              joblib: 1.2.0
             sklearn: 1.2.2
                pyod: 1.0.9
            imblearn: 0.10.1
   category_encoders: 2.6.0
            lightgbm: 3.3.5
               numba: 0.56.4
            requests: 2.28.2
          matplotlib: 3.5.2
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.14.0
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.17.0
               tbats: 1.1.2
            pmdarima: 2.0.3
              psutil: 5.9.4

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.3.2
                umap: 0.5.3
    pandas_profiling: 4.1.2
  explainerdashboard: 0.4.2.1
             autoviz: 0.1.58
           fairlearn: 0.7.0
             xgboost: 1.7.5
            catboost: 1.1.1
              kmodes: 0.12.2
             mlxtend: 0.22.0
       statsforecast: 1.5.0
        tune_sklearn: 0.4.5
                 ray: 2.3.1
            hyperopt: 0.2.7
              optuna: 3.1.0
               skopt: 0.9.0
              mlflow: 1.30.0
              gradio: 3.24.1
             fastapi: 0.95.0
             uvicorn: 0.21.1
              m2cgen: 0.10.0
           evidently: 0.2.8
               fugue: 0.8.3
           streamlit: Not installed
             prophet: Not installed
</details>

**Comment by moezali1** [comment]
Unable to reproduce the issue.
