### ISSUE TITLE
AttributeError: module 'pycaret' has no attribute 'preprocess'  

### ISSUE THREAD

**Issue by sarikanyaram** [pycaret/pycaret#359]
AttributeError: module 'pycaret' has no attribute 'preprocess'  while 
exp_red = setup(data = series, target = ' Bytes', session_id= 143, html = False)   

Here I am using Time series data with two columns along the index column.
here I am pasting few lines of my dataset

                      Frames   Bytes
Dateandtime                         
1999-12-01 11:55:48      106    5194
1999-12-01 11:55:49      117    5733
1999-12-01 11:55:50      106    5194
1999-12-01 11:55:51      101    4949
1999-12-01 11:55:52       83    4067

Please give me the solution for this

**Comment by pycaret** [comment]
@sarikanyaram Can you please provide sample data so that I can try to reproduce the issue?

**Comment by sarikanyaram** [comment]
import pycaret as pc
from pycaret.regression import *
import pandas as pd
from pycaret.preprocess import *


series = pd.read_csv('/home/sarika/Documents/papers/split pcaps/sample.csv', header=0, parse_dates=[0],index_col=0, squeeze=True)
print(series.head())
series = series.resample('H').mean()

print(series.head())
exp_red = setup(data = series, target = ' Bytes', session_id= 143, html = False)
compare_models()


This is the code I wrote for the time series regression


[sample.zip](https://github.com/pycaret/pycaret/files/5032731/sample.zip)

**Comment by pycaret** [comment]
@sarikanyaram Can you please update pycaret to 2.2 and try again? `pip install --upgrade pycaret`.

Let us know if the issue persists.

**Comment by pycaret** [comment]
@sarikanyaram Are you still facing this issue, please confirm?

**Comment by sarikanyaram** [comment]
THis issue is was solved but when i am using univariate time series for
xgboost using create_model(xgb) i am getting the below error. For rf and
lightgbm it is working.

I am unable to build the stack model using selected model.



IntProgress(value=0, description='Processing: ', max=4)







Initiated . . . . . . . . . . . . . . . . . . 12:56:33
Status . . . . . . . . . . . . . . . . . . Fitting 10 Folds
Estimator . . . . . . . . . . . . . . . . . . Extreme Gradient Boosting

MAE MSE RMSE R2 RMSLE MAPE

---------------------------------------------------------------------------Empty
                                    Traceback (most recent call
last)~/.local/lib/python3.6/site-packages/joblib/parallel.py in
dispatch_one_batch(self, iterator)    807             try:--> 808
           tasks = self._ready_batches.get(block=False)    809
    except queue.Empty:
/usr/lib/python3.6/queue.py in get(self, block, timeout)    160
         if not self._qsize():--> 161                     raise Empty
  162             elif timeout is None:
Empty:

During handling of the above exception, another exception occurred:
XGBoostError                              Traceback (most recent call
last)<ipython-input-10-31fad250561b> in <module>----> 1 xgb =
create_model('xgboost')
~/.local/lib/python3.6/site-packages/pycaret/regression.py in
create_model(estimator, fold, round, cross_validation, fit_kwargs,
groups, verbose, **kwargs)    886         groups=groups,    887
 verbose=verbose,--> 888         **kwargs,    889     )    890
~/.local/lib/python3.6/site-packages/pycaret/internal/tabular.py in
create_model_supervised(estimator, fold, round, cross_validation,
predict, fit_kwargs, groups, refit, verbose, system, X_train_data,
y_train_data, metrics, display, **kwargs)   3066
n_jobs=n_jobs,   3067             return_train_score=False,-> 3068
        error_score=0,   3069         )   3070         model_fit_end =
time.time()
~/.local/lib/python3.6/site-packages/sklearn/utils/validation.py in
inner_f(*args, **kwargs)     70
FutureWarning)     71         kwargs.update({k: arg for k, arg in
zip(sig.parameters, args)})---> 72         return f(**kwargs)     73
  return inner_f     74
~/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py
in cross_validate(estimator, X, y, groups, scoring, cv, n_jobs,
verbose, fit_params, pre_dispatch, return_train_score,
return_estimator, error_score)    246             return_times=True,
return_estimator=return_estimator,    247
error_score=error_score)--> 248         for train, test in cv.split(X,
y, groups))    249     250     zipped_scores = list(zip(*scores))
~/.local/lib/python3.6/site-packages/joblib/parallel.py in
__call__(self, iterable)   1027             # remaining jobs.   1028
          self._iterating = False-> 1029             if
self.dispatch_one_batch(iterator):   1030
self._iterating = self._original_iterator is not None   1031
~/.local/lib/python3.6/site-packages/joblib/parallel.py in
dispatch_one_batch(self, iterator)    817
big_batch_size = batch_size * n_jobs    818 --> 819
islice = list(itertools.islice(iterator, big_batch_size))    820
          if len(islice) == 0:    821                     return False
~/.local/lib/python3.6/site-packages/sklearn/model_selection/_validation.py
in <genexpr>(.0)    246             return_times=True,
return_estimator=return_estimator,    247
error_score=error_score)--> 248         for train, test in cv.split(X,
y, groups))    249     250     zipped_scores = list(zip(*scores))
~/.local/lib/python3.6/site-packages/sklearn/utils/validation.py in
inner_f(*args, **kwargs)     70
FutureWarning)     71         kwargs.update({k: arg for k, arg in
zip(sig.parameters, args)})---> 72         return f(**kwargs)     73
  return inner_f     74
~/.local/lib/python3.6/site-packages/sklearn/base.py in
clone(estimator, safe)     86     for name, param in
new_object_params.items():     87         new_object_params[name] =
clone(param, safe=False)---> 88     new_object =
klass(**new_object_params)     89     params_set =
new_object.get_params(deep=False)     90
~/.local/lib/python3.6/site-packages/pycaret/internal/pipeline.py in
__init__(self, steps, memory, verbose)     22
super().__init__(steps, memory=memory, verbose=verbose)     23
self._fit_vars = set()---> 24
self._carry_over_final_estimator_fit_vars()     25      26
@property
~/.local/lib/python3.6/site-packages/pycaret/internal/pipeline.py in
_carry_over_final_estimator_fit_vars(self)     56         if
hasattr(self._final_estimator, "fit"):     57             for k, v in
get_all_object_vars_and_properties(---> 58
self._final_estimator     59             ).items():     60
    if is_fit_var(k):
~/.local/lib/python3.6/site-packages/pycaret/internal/utils.py in
get_all_object_vars_and_properties(object)    555     return {    556
       k: getattr(object, k, "")--> 557         for k in
object.__dir__()    558         if k[:2] != "__" and
type(getattr(object, k, "")).__name__ != "method"    559     }
~/.local/lib/python3.6/site-packages/pycaret/internal/utils.py in
<dictcomp>(.0)    556         k: getattr(object, k, "")    557
for k in object.__dir__()--> 558         if k[:2] != "__" and
type(getattr(object, k, "")).__name__ != "method"    559     }    560
~/.local/lib/python3.6/site-packages/xgboost/sklearn.py in
feature_importances_(self)    685                 'Feature importance
is not defined for Booster type {}'    686
.format(self.booster))--> 687         b = self.get_booster()    688
     score = b.get_score(importance_type=self.importance_type)    689
       all_features = [score.get(f, 0.) for f in b.feature_names]
~/.local/lib/python3.6/site-packages/xgboost/sklearn.py in
get_booster(self)    259         """    260         if not
hasattr(self, '_Booster'):--> 261             raise XGBoostError('need
to call fit or load_model beforehand')    262         return
self._Booster    263
XGBoostError: need to call fit or load_model beforehand

**Comment by pycaret** [comment]
@sarikanyaram Please update your `xgboost` version by `pip install --upgrade xgboost`.

**Comment by jisho-iemoto** [comment]
I have a similar error when loading a model.
Now I'm re-building a model with updated PyCaret (ver2.2) and will see if the said error will arise.

Then, I can't import a module named 'pycaret.preprocess' and this is the very error I've encountered.
Do you have any ideas on this?

**Comment by jisho-iemoto** [comment]
> I have a similar error when loading a model.
> Now I'm re-building a model with updated PyCaret (ver2.2) and will see if the said error will arise.
> 
> Then, I can't import a module named 'pycaret.preprocess' and this is the very error I've encountered.
> Do you have any ideas on this?

The message attached below is the actual one when loading a model. 


Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Admin\Anaconda3-2\envs\New_AK\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "<ipython-input-94-76e714b91ac4>", line 167, in EveryWeek
    Shutsu_2()
  File "<ipython-input-105-a8f72c53d653>", line 9, in Shutsu_2
    ShutsubaPredict_3(KisoKoushin=False,Jisseki=False,OddsUP=True)
  File "<ipython-input-79-e4155e15e930>", line 614, in ShutsubaPredict_3
    clf =load_model('H:\\競馬予想\\全データマルチモデル_All'+RC+Basho+'_True')
  File "C:\Users\Admin\Anaconda3-2\envs\New_AK\lib\site-packages\pycaret\classification.py", line 2111, in load_model
    verbose=verbose,
  File "C:\Users\Admin\Anaconda3-2\envs\New_AK\lib\site-packages\pycaret\internal\tabular.py", line 8891, in load_model
    model_name, platform, authentication, verbose
  File "C:\Users\Admin\Anaconda3-2\envs\New_AK\lib\site-packages\pycaret\internal\persistence.py", line 370, in load_model
    return joblib.load(model_name)
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\joblib\numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\joblib\numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "C:\Users\Admin\Anaconda3-2\envs\New_AK\lib\pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "C:\Users\Admin\Anaconda3-2\envs\New_AK\lib\pickle.py", line 1376, in load_global
    klass = self.find_class(module, name)
  File "C:\Users\Admin\Anaconda3-2\envs\New_AK\lib\pickle.py", line 1426, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'pycaret.preprocess'

**Comment by pycaret** [comment]
@jisho-iemoto Models trained using version < 2.2 will not work with 2.2 and forward. I suggest you retrain the model using `pycaret==2.2`.
