### ISSUE TITLE
[BUG]: Failed to use the Train custom models(PLSRegression) with scikit-learn

### ISSUE THREAD

**Issue by m-kaka** [pycaret/pycaret#3635]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

When used the Train custom models within scikit-learn, it showed the error.

### Reproducible Example

```python
from pycaret.datasets import get_data
data = get_data("boston")
exp = setup(data, target = 'medv', session_id = 123)
PLS_model =  PLSRegression(n_components=2)
pls = create_model(PLS_model)
```

### Expected Behavior

Train the custom model

### Actual Results

```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[25], line 5
      3 exp = setup(data, target = 'medv', session_id = 123)
      4 PLS_model =  PLSRegression(n_components=2)
----> 5 pls = create_model(PLS_model)

File /usr/local/lib/python3.10/site-packages/pycaret/utils/generic.py:965, in check_if_global_is_not_none.<locals>.decorator.<locals>.wrapper(*args, **kwargs)
    963     if globals_d[name] is None:
    964         raise ValueError(message)
--> 965 return func(*args, **kwargs)

File /usr/local/lib/python3.10/site-packages/pycaret/regression/functional.py:998, in create_model(estimator, fold, round, cross_validation, fit_kwargs, groups, experiment_custom_tags, engine, verbose, return_train_score, **kwargs)
    870 @check_if_global_is_not_none(globals(), _CURRENT_EXPERIMENT_DECORATOR_DICT)
    871 def create_model(
    872     estimator: Union[str, Any],
   (...)
    882     **kwargs,
    883 ):
    884     """
    885     This function trains and evaluates the performance of a given estimator
    886     using cross validation. The output of this function is a score grid with
   (...)
    995 
    996     """
--> 998     return _CURRENT_EXPERIMENT.create_model(
    999         estimator=estimator,
   1000         fold=fold,
   1001         round=round,
   1002         cross_validation=cross_validation,
   1003         fit_kwargs=fit_kwargs,
   1004         groups=groups,
   1005         experiment_custom_tags=experiment_custom_tags,
   1006         engine=engine,
   1007         verbose=verbose,
   1008         return_train_score=return_train_score,
   1009         **kwargs,
   1010     )

File /usr/local/lib/python3.10/site-packages/pycaret/regression/oop.py:1293, in RegressionExperiment.create_model(self, estimator, fold, round, cross_validation, fit_kwargs, groups, experiment_custom_tags, engine, verbose, return_train_score, **kwargs)
   1290     self._set_engine(estimator=estimator, engine=engine, severity="error")
   1292 try:
-> 1293     return_values = super().create_model(
   1294         estimator=estimator,
   1295         fold=fold,
   1296         round=round,
   1297         cross_validation=cross_validation,
   1298         fit_kwargs=fit_kwargs,
   1299         groups=groups,
   1300         experiment_custom_tags=experiment_custom_tags,
   1301         verbose=verbose,
   1302         return_train_score=return_train_score,
   1303         **kwargs,
   1304     )
   1305 finally:
   1306     if engine is not None:
   1307         # Reset the models back to the default engines

File /usr/local/lib/python3.10/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py:1751, in _SupervisedExperiment.create_model(self, estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, probability_threshold, experiment_custom_tags, verbose, return_train_score, **kwargs)
   1739 # TODO improve error message
   1740 assert not any(
   1741     x
   1742     in (
   (...)
   1749     for x in kwargs
   1750 )
-> 1751 return self._create_model(
   1752     estimator=estimator,
   1753     fold=fold,
   1754     round=round,
   1755     cross_validation=cross_validation,
   1756     predict=predict,
   1757     fit_kwargs=fit_kwargs,
   1758     groups=groups,
   1759     refit=refit,
   1760     probability_threshold=probability_threshold,
   1761     experiment_custom_tags=experiment_custom_tags,
   1762     verbose=verbose,
   1763     return_train_score=return_train_score,
   1764     **kwargs,
   1765 )

File /usr/local/lib/python3.10/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py:1519, in _SupervisedExperiment._create_model(self, estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, probability_threshold, experiment_custom_tags, verbose, system, add_to_model_list, X_train_data, y_train_data, metrics, display, model_only, return_train_score, **kwargs)
   1516         return model, model_fit_time
   1517     return model
-> 1519 model, model_fit_time, model_results, _ = self._create_model_with_cv(
   1520     model,
   1521     data_X,
   1522     data_y,
   1523     fit_kwargs,
   1524     round,
   1525     cv,
   1526     groups,
   1527     metrics,
   1528     refit,
   1529     system,
   1530     display,
   1531     return_train_score=return_train_score,
   1532 )
   1534 # end runtime
   1535 runtime_end = time.time()

File /usr/local/lib/python3.10/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py:1114, in _SupervisedExperiment._create_model_with_cv(self, model, data_X, data_y, fit_kwargs, round, cv, groups, metrics, refit, system, display, return_train_score)
   1112 model_fit_start = time.time()
   1113 with redirect_output(self.logger):
-> 1114     scores = cross_validate(
   1115         pipeline_with_model,
   1116         data_X,
   1117         data_y,
   1118         cv=cv,
   1119         groups=groups,
   1120         scoring=metrics_dict,
   1121         fit_params=fit_kwargs,
   1122         n_jobs=n_jobs,
   1123         return_train_score=return_train_score,
   1124         error_score=0,
   1125     )
   1126 model_fit_end = time.time()
   1127 model_fit_time = np.array(model_fit_end - model_fit_start).round(2)

File /usr/local/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:285, in cross_validate(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, error_score)
    265 parallel = Parallel(n_jobs=n_jobs, verbose=verbose, pre_dispatch=pre_dispatch)
    266 results = parallel(
    267     delayed(_fit_and_score)(
    268         clone(estimator),
   (...)
    282     for train, test in cv.split(X, y, groups)
    283 )
--> 285 _warn_or_raise_about_fit_failures(results, error_score)
    287 # For callabe scoring, the return type is only know after calling. If the
    288 # return type is a dictionary, the error scores can now be inserted with
    289 # the correct key.
    290 if callable(scoring):

File /usr/local/lib/python3.10/site-packages/sklearn/model_selection/_validation.py:367, in _warn_or_raise_about_fit_failures(results, error_score)
    360 if num_failed_fits == num_fits:
    361     all_fits_failed_message = (
    362         f"\nAll the {num_fits} fits failed.\n"
    363         "It is very likely that your model is misconfigured.\n"
    364         "You can try to debug the error by setting error_score='raise'.\n\n"
    365         f"Below are more details about the failures:\n{fit_errors_summary}"
    366     )
--> 367     raise ValueError(all_fits_failed_message)
    369 else:
    370     some_fits_failed_message = (
    371         f"\n{num_failed_fits} fits failed out of a total of {num_fits}.\n"
    372         "The score on these train-test partitions for these parameters"
   (...)
    376         f"Below are more details about the failures:\n{fit_errors_summary}"
    377     )

ValueError: 
All the 10 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sklearn/model_selection/_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 260, in fit
    fitted_estimator = self._memory_fit(
  File "/usr/local/lib/python3.10/site-packages/joblib/memory.py", line 594, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/usr/local/lib/python3.10/site-packages/pycaret/internal/memory.py", line 398, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pycaret/internal/memory.py", line 309, in call
    output = self.func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 66, in _fit_one
    transformer.fit(*args, **fit_params)
TypeError: PLSRegression.fit() missing 1 required positional argument: 'Y'
```

### Installed Versions

<details>
System:
    python: 3.9.17 (main, Jun 14 2023, 18:56:13)  [GCC 12.2.0]
executable: /usr/local/bin/python
   machine: Linux-4.14.311-233.529.amzn2.x86_64-x86_64-with-glibc2.36

PyCaret required dependencies:
                 pip: 23.0.1
          setuptools: 58.1.0
             pycaret: 3.0.4
             IPython: 7.34.0
          ipywidgets: 7.7.5
                tqdm: 4.65.0
               numpy: 1.23.0
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.10.1
              joblib: 1.3.1
             sklearn: 1.2.2
                pyod: 1.1.0
            imblearn: 0.10.1
   category_encoders: 2.6.1
            lightgbm: 3.3.5
               numba: 0.57.1
            requests: 2.31.0
          matplotlib: 3.7.1
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.15.0
    plotly-resampler: Not installed
             kaleido: 0.2.1
           schemdraw: 0.15
         statsmodels: 0.14.0
              sktime: 0.20.0
               tbats: 1.1.3
            pmdarima: 2.0.3
              psutil: 5.9.5
          markupsafe: 2.1.3
             pickle5: Not installed
         cloudpickle: 2.2.1
         deprecation: 2.1.0
              xxhash: 3.2.0
           wurlitzer: 3.0.3

PyCaret optional dependencies:
                shap: 0.41.0
           interpret: 0.4.2
                umap: 0.5.3
    pandas_profiling: 3.6.6
  explainerdashboard: 0.4.2.2
             autoviz: 0.1.720
           fairlearn: 0.7.0
          deepchecks: 0.17.3
             xgboost: 1.7.6
            catboost: 1.2
              kmodes: 0.12.2
             mlxtend: 0.22.0
       statsforecast: 1.5.0
        tune_sklearn: 0.4.6
                 ray: 2.5.1
            hyperopt: 0.2.7
              optuna: 3.2.0
               skopt: 0.9.0
              mlflow: 1.30.1
              gradio: 3.35.2
             fastapi: 0.99.1
             uvicorn: 0.22.0
              m2cgen: 0.10.0
           evidently: 0.2.8
               fugue: 0.8.5
           streamlit: Not installed
             prophet: Not installed
</details>

**Comment by ngupta23** [comment]
This is a bug/incosistency in scikit learn. The standard scikit interface should have the argument in lowercase "y" not uppercase "Y". Can you open an issue on their repository?

https://github.com/scikit-learn/scikit-learn/blob/7f9bad99d6e0a3e8ddf92a7e5561245224dab102/sklearn/cross_decomposition/_pls.py#L622

Try this as a stop gap measure (code from @Yard1)
```python
from pycaret.datasets import get_data
data = get_data("boston")
exp = setup(data, target = 'medv', session_id = 123)

class PLSRegressionFixed(PLSRegression)
    def fit(X, y, **args, **kwargs):
        return super(X, y, **args, **kwargs)


PLS_model =  PLSRegressionFixed(n_components=2)
pls = create_model(PLS_model)
```

**Comment by m-kaka** [comment]
I see. I will open this issue on Scikit-learn project.
