### ISSUE TITLE
[BUG]: AttributeError: 'ClassificationExperiment' object has no attribute 'logging_param'

### ISSUE THREAD

**Issue by pavelsr** [pycaret/pycaret#3644]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Probably also refers to "dependency issue related to gradio and is not reproducible at the moment" ([link](https://github.com/pycaret/pycaret/issues/3578#issuecomment-1574284881)) but need to verify

### Reproducible Example

```python
from pycaret.classification import ClassificationExperiment
s = ClassificationExperiment()
loaded_model = s.load_model('neuro/my_best_pipeline')
s.create_api(loaded_model, 'ml_api')
```

### Expected Behavior

It must create FastAPI app, but it doesn't.

### Actual Results

```python-traceback
Traceback (most recent call last):
  File "/home/a/projects/callbot.myguru.ru/t.py", line 6, in <module>
    s.create_api(loaded_model, 'ml_api')
  File "/usr/local/lib/python3.10/dist-packages/pycaret/internal/pycaret_experiment/tabular_experiment.py", line 2575, in create_api
    self.save_model(estimator, model_name=api_name, verbose=False)
  File "/usr/local/lib/python3.10/dist-packages/pycaret/classification/oop.py", line 3040, in save_model
    return super().save_model(
  File "/usr/local/lib/python3.10/dist-packages/pycaret/internal/pycaret_experiment/tabular_experiment.py", line 2385, in save_model
    if self.logging_param:
AttributeError: 'ClassificationExperiment' object has no attribute 'logging_param'
```

### Installed Versions

<details>
>>> from pycaret import show_versions; show_versions()

System:
    python: 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
executable: /usr/bin/python3
   machine: Linux-5.15.0-41-generic-x86_64-with-glibc2.35

PyCaret required dependencies:
                 pip: 22.0.2
          setuptools: 59.6.0
             pycaret: 3.0.1
             IPython: 7.34.0
          ipywidgets: 7.7.5
                tqdm: 4.64.1
               numpy: 1.21.5
              pandas: 1.5.2
              jinja2: 3.1.2
               scipy: 1.9.3
              joblib: 1.2.0
             sklearn: 1.2.0
                pyod: 1.1.0
            imblearn: 0.11.0
   category_encoders: 2.6.1
            lightgbm: 3.3.5
               numba: 0.56.3
            requests: 2.25.1
          matplotlib: 3.6.2
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.15.0
             kaleido: 0.2.1
         statsmodels: 0.13.5
              sktime: 0.17.0
               tbats: 1.1.3
            pmdarima: 2.0.3
              psutil: 5.9.0

PyCaret optional dependencies:
                shap: 0.42.1
           interpret: 0.4.2
                umap: 0.5.3
    pandas_profiling: 4.1.0
  explainerdashboard: 0.4.2.2
             autoviz: 0.1.730
           fairlearn: 0.7.0
             xgboost: 1.7.6
            catboost: 1.2
              kmodes: 0.12.2
             mlxtend: 0.22.0
       statsforecast: 1.5.0
        tune_sklearn: 0.4.6
                 ray: 2.5.1
            hyperopt: 0.2.7
              optuna: 3.2.0
               skopt: 0.9.0
              mlflow: 1.30.1
              gradio: 3.37.0
             fastapi: 0.80.0
             uvicorn: 0.18.3
              m2cgen: 0.10.0
           evidently: 0.2.8
               fugue: 0.8.5
           streamlit: Not installed
             prophet: Not installed
>>> 
</details>

**Comment by ngupta23** [comment]
It is possible that the model was created in a pycaret version different from the one where you are creating the API. Make sure that the model creation and the API creation is using the same pycaret version.

**Comment by moezali1** [comment]
Closing as part of the 4.0 backlog cleanup — see #4177.

PyCaret 4.0 is a ground-up rewrite (OOP-only API, sklearn-native engine, Python 3.11+, sklearn ≥ 1.7) and almost all pre-4.0 issues either reference removed APIs (`setup()`, `plot_model`, `evaluate_model`, `interpret_model`, `automl`, the legacy time-series module, the Streamlit dashboard, …) or no longer reproduce on the new code path.

**If this still affects you in 4.0, please re-file as a new issue** with:

- the experiment constructor call (`Experiment(...)`),
- the operation that fails,
- the full traceback,
- your Python / sklearn / pycaret versions.

Resources for 4.0:

- Docs: https://pycaret.org/docs
- Migrate from 3.x: https://pycaret.org/docs/guides/migrating-from-3-x
- API reference: https://pycaret.org/reference
- FAQ: https://pycaret.org/docs/resources/faqs

Thanks for filing — and apologies for the long latency. The repo had drifted; we're starting clean.
