### ISSUE TITLE
[BUG]: Model setup error on Snowflake

### ISSUE THREAD

**Issue by wishshi** [pycaret/pycaret#3681]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Tried to build model with Pycaret on Snowflake, but got error: 

> TypeError: cpu_count() got an unexpected keyword argument 'logical'.

### Reproducible Example

```python
Have same error, I copied the example from Snowflake forum(https://community.snowflake.com/s/question/0D5Do00000rXqBTKA0/in-python-38-pycaret-302-setup-function-raises-a-typeerror-on-its-own)
CREATE OR REPLACE PROCEDURE TRAINING_DEBUG()
RETURNS VARCHAR
LANGUAGE PYTHON
RUNTIME_VERSION = 3.8
PACKAGES = ('SNOWFLAKE-SNOWPARK-PYTHON', 'PYCARET')
HANDLER = 'train'
AS
$$
def debug(session):
    import sys
    import pycaret
    raise Exception(f"{sys.version = } -- {pycaret.__version__ = }")
 
def train(session):
    import pandas as pd
    from pycaret.regression import RegressionExperiment
    data = pd.DataFrame({'X1': list(range(8)), 'X2': list(range(8))[::-1], 'y': [0, 0, 0, 0, 1, 1, 1, 1]})
 
    train_data = data.iloc[:-2]
    test_data = data.iloc[-2:]
    
    exp = RegressionExperiment()
    exp.setup(
        data=train_data,
        test_data=test_data,
        target="y"
    )
 
    return "ok"
$$;
 
 
CALL TRAINING_DEBUG();
```

### Expected Behavior

Build a model and return 'ok'.

### Actual Results

```python-traceback
Traceback (most recent call last):
  File "_udf_code.py", line 16, in train
  File "/usr/lib/python_udf/96f60daf41aef075057a42475b202968a259b1c55fc9fbba41efdd1b3f74f832/lib/python3.8/site-packages/pycaret/regression/oop.py", line 680, in setup
    self._initialize_setup(
  File "/usr/lib/python_udf/96f60daf41aef075057a42475b202968a259b1c55fc9fbba41efdd1b3f74f832/lib/python3.8/site-packages/pycaret/internal/pycaret_experiment/tabular_experiment.py", line 330, in _initialize_setup
    self._check_environment()
  File "/usr/lib/python_udf/96f60daf41aef075057a42475b202968a259b1c55fc9fbba41efdd1b3f74f832/lib/python3.8/site-packages/pycaret/internal/pycaret_experiment/pycaret_experiment.py", line 115, in _check_environment
    self.logger.info(f"Physical Core: {psutil.cpu_count(logical=False)}")
TypeError: cpu_count() got an unexpected keyword argument 'logical'
 in function TRAINING_DEBUG with handler train
```

### Installed Versions

python version (3.8.17) and pycaret version (3.0.2)

**Comment by wishshi** [comment]
This error is related to psutil. It seems Snowflake doesn't tell how many CPUs. psutil.cpu_count() return -1.

**Comment by moezali1** [comment]
Closing as part of the 4.0 backlog cleanup — see #4177.

PyCaret 4.0 is a ground-up rewrite (OOP-only API, sklearn-native engine, Python 3.11+, sklearn ≥ 1.7) and almost all pre-4.0 issues either reference removed APIs (`setup()`, `plot_model`, `evaluate_model`, `interpret_model`, `automl`, the legacy time-series module, the Streamlit dashboard, …) or no longer reproduce on the new code path.

**If this still affects you in 4.0, please re-file as a new issue** with:

- the experiment constructor call (`Experiment(...)`),
- the operation that fails,
- the full traceback,
- your Python / sklearn / pycaret versions.

Resources for 4.0:

- Docs: https://pycaret.org/docs
- Migrate from 3.x: https://pycaret.org/docs/guides/migrating-from-3-x
- API reference: https://pycaret.org/reference
- FAQ: https://pycaret.org/docs/resources/faqs

Thanks for filing — and apologies for the long latency. The repo had drifted; we're starting clean.
