### ISSUE TITLE
[BUG]: `from pycaret import classification` throws ImportError

### ISSUE THREAD

**Issue by jmakov** [pycaret/pycaret#3759]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

 `from pycaret import classification` throws ImportError

### Reproducible Example

```python
from pycaret import classification
```

### Expected Behavior

According to docs this should work.

### Actual Results

```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jernej_m/mambaforge-pypy3/envs/test/lib/python3.10/site-packages/pycaret/classification.py", line 10, in <module>
    import pycaret.internal.tabular
  File "/home/jernej_m/mambaforge-pypy3/envs/test/lib/python3.10/site-packages/pycaret/internal/tabular.py", line 17, in <module>
    from pycaret.internal.pipeline import (
  File "/home/jernej_m/mambaforge-pypy3/envs/test/lib/python3.10/site-packages/pycaret/internal/pipeline.py", line 15, in <module>
    from sklearn.utils.metaestimators import if_delegate_has_method
ImportError: cannot import name 'if_delegate_has_method' from 'sklearn.utils.metaestimators' (/home/jernej_m/mambaforge-pypy3/envs/test/lib/python3.10/site-packages/sklearn/utils/metaestimators.py)
```

### Installed Versions

<details>
System:
    python: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:40:32) [GCC 12.3.0]
executable: /home/jernej_m/mambaforge-pypy3/envs/quantlab/bin/python
   machine: Linux-6.1.53-1-MANJARO-x86_64-with-glibc2.38

PyCaret required dependencies:
                 pip: 23.2.1
          setuptools: 68.2.2
             pycaret: 3.0.4
             IPython: 8.16.0
          ipywidgets: 8.1.1
                tqdm: 4.66.1
               numpy: 1.23.5
              pandas: 1.5.3
              jinja2: 3.1.2
               scipy: 1.11.3
              joblib: 1.3.2
             sklearn: 1.2.2
                pyod: 1.1.0
            imblearn: 0.11.0
   category_encoders: 2.6.2
            lightgbm: 4.0.0
               numba: 0.57.1
            requests: 2.31.0
          matplotlib: 3.8.0
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.17.0
    plotly-resampler: Not installed
             kaleido: 0.2.1
           schemdraw: 0.15
         statsmodels: 0.14.0
              sktime: 0.21.1
               tbats: 1.1.3
            pmdarima: 2.0.2
              psutil: 5.9.5
          markupsafe: 2.1.3
             pickle5: Not installed
         cloudpickle: 2.2.1
         deprecation: 2.1.0
              xxhash: Not installed
           wurlitzer: 3.0.3

PyCaret optional dependencies:
                shap: Not installed
           interpret: Not installed
                umap: 0.5.4
    pandas_profiling: Not installed
  explainerdashboard: Not installed
             autoviz: Not installed
           fairlearn: Not installed
          deepchecks: Not installed
             xgboost: Not installed
            catboost: Not installed
              kmodes: Not installed
             mlxtend: Not installed
       statsforecast: Not installed
        tune_sklearn: Not installed
                 ray: 2.6.3
            hyperopt: Not installed
              optuna: Not installed
               skopt: Not installed
              mlflow: Not installed
              gradio: Not installed
             fastapi: Not installed
             uvicorn: Not installed
              m2cgen: Not installed
           evidently: Not installed
               fugue: Not installed
           streamlit: Not installed
             prophet: Not installed
</details>

**Comment by jmakov** [comment]
For future reference, `pycaret` has to be installed via `pip`, not `conda`.
