### ISSUE TITLE
[INSTALL]: 

### ISSUE THREAD

**Issue by lalitsc12** [pycaret/pycaret#3769]
### Installation check

- [X] I have read the [installation guide](https://pycaret.gitbook.io/docs/get-started/installation).

### Platform

macOS-14.0-arm64-arm-64bit

### Installation Method

pip install

### pycaret Version

latest

### Python Version

Python 3.11.5

### Description

Getting Numpy related errror while installing Pycaret 

### Installation Logs

<details>

Collecting pycaret
  Obtaining dependency information for pycaret from https://files.pythonhosted.org/packages/d5/54/d575af389203fc27d6c6cf7d60c4e67fcabfda4bc8e84271c8a396bd4a03/pycaret-3.1.0-py3-none-any.whl.metadata
  Using cached pycaret-3.1.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: ipython>=5.5.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (8.15.0)
Requirement already satisfied: ipywidgets>=7.6.5 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (8.0.4)
Requirement already satisfied: tqdm>=4.62.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (4.65.0)
Collecting numpy<1.24,>=1.21 (from pycaret)
  Using cached numpy-1.23.5-cp311-cp311-macosx_11_0_arm64.whl (13.3 MB)
Collecting pandas<2.0.0,>=1.3.0 (from pycaret)
  Using cached pandas-1.5.3-cp311-cp311-macosx_11_0_arm64.whl (10.8 MB)
Requirement already satisfied: jinja2>=1.2 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (3.1.2)
Collecting scipy~=1.10.1 (from pycaret)
  Using cached scipy-1.10.1-cp311-cp311-macosx_12_0_arm64.whl (28.7 MB)
Requirement already satisfied: joblib>=1.2.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (1.2.0)
Collecting scikit-learn<1.3.0,>=1.0 (from pycaret)
  Using cached scikit_learn-1.2.2-cp311-cp311-macosx_12_0_arm64.whl (8.4 MB)
Collecting pyod>=1.0.8 (from pycaret)
  Using cached pyod-1.1.0.tar.gz (153 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: imbalanced-learn>=0.8.1 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (0.10.1)
Collecting category-encoders>=2.4.0 (from pycaret)
  Obtaining dependency information for category-encoders>=2.4.0 from https://files.pythonhosted.org/packages/1f/e2/495811f12b2e90753fff0e42a07adb0370a725de17cc23a579ac9d3ca67c/category_encoders-2.6.2-py2.py3-none-any.whl.metadata
  Using cached category_encoders-2.6.2-py2.py3-none-any.whl.metadata (8.0 kB)
Collecting lightgbm>=3.0.0 (from pycaret)
  Using cached lightgbm-4.1.0.tar.gz (1.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numba>=0.55.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (0.57.1)
Requirement already satisfied: requests>=2.27.1 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (2.31.0)
Requirement already satisfied: psutil>=5.9.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (5.9.0)
Requirement already satisfied: markupsafe>=2.0.1 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (2.1.1)
Requirement already satisfied: importlib-metadata>=4.12.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (6.0.0)
Requirement already satisfied: nbformat>=4.2.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (5.9.2)
Requirement already satisfied: cloudpickle in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (2.2.1)
Collecting deprecation>=2.1.0 (from pycaret)
  Using cached deprecation-2.1.0-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: xxhash in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (2.0.2)
Requirement already satisfied: matplotlib>=3.3.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (3.7.2)
Collecting scikit-plot>=0.3.7 (from pycaret)
  Using cached scikit_plot-0.3.7-py3-none-any.whl (33 kB)
Collecting yellowbrick>=1.4 (from pycaret)
  Using cached yellowbrick-1.5-py3-none-any.whl (282 kB)
Requirement already satisfied: plotly>=5.0.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (5.9.0)
Requirement already satisfied: kaleido>=0.2.1 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (0.2.1)
Collecting schemdraw==0.15 (from pycaret)
  Using cached schemdraw-0.15-py3-none-any.whl (106 kB)
Collecting plotly-resampler>=0.8.3.1 (from pycaret)
  Obtaining dependency information for plotly-resampler>=0.8.3.1 from https://files.pythonhosted.org/packages/08/1d/87d4ed45c26226630bcb0a205ff006c00645cc68977e22c0f6f16a7f5d2b/plotly_resampler-0.9.1-py3-none-any.whl.metadata
  Using cached plotly_resampler-0.9.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: statsmodels>=0.12.1 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (0.14.0)
Collecting sktime!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0,>=0.16.1 (from pycaret)
  Obtaining dependency information for sktime!=0.17.1,!=0.17.2,!=0.18.0,<0.22.0,>=0.16.1 from https://files.pythonhosted.org/packages/0f/70/a791db68c6f6922eb9e79baf1466263147a487c5b7ba7813f5868901e032/sktime-0.21.1-py3-none-any.whl.metadata
  Using cached sktime-0.21.1-py3-none-any.whl.metadata (25 kB)
Collecting tbats>=1.1.3 (from pycaret)
  Using cached tbats-1.1.3-py3-none-any.whl (44 kB)
Collecting pmdarima!=1.8.1,<3.0.0,>=1.8.0 (from pycaret)
  Using cached pmdarima-2.0.3-cp311-cp311-macosx_11_0_arm64.whl (574 kB)
Requirement already satisfied: wurlitzer in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pycaret) (3.0.2)
Requirement already satisfied: patsy>=0.5.1 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from category-encoders>=2.4.0->pycaret) (0.5.3)
Requirement already satisfied: packaging in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from deprecation>=2.1.0->pycaret) (23.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from imbalanced-learn>=0.8.1->pycaret) (2.2.0)
Requirement already satisfied: zipp>=0.5 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from importlib-metadata>=4.12.0->pycaret) (3.11.0)
Requirement already satisfied: backcall in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from ipython>=5.5.0->pycaret) (0.2.0)
Requirement already satisfied: decorator in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from ipython>=5.5.0->pycaret) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from ipython>=5.5.0->pycaret) (0.18.1)
Requirement already satisfied: matplotlib-inline in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from ipython>=5.5.0->pycaret) (0.1.6)
Requirement already satisfied: pickleshare in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from ipython>=5.5.0->pycaret) (0.7.5)
Requirement already satisfied: prompt-toolkit!=3.0.37,<3.1.0,>=3.0.30 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from ipython>=5.5.0->pycaret) (3.0.36)
Requirement already satisfied: pygments>=2.4.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from ipython>=5.5.0->pycaret) (2.15.1)
Requirement already satisfied: stack-data in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from ipython>=5.5.0->pycaret) (0.2.0)
Requirement already satisfied: traitlets>=5 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from ipython>=5.5.0->pycaret) (5.7.1)
Requirement already satisfied: pexpect>4.3 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from ipython>=5.5.0->pycaret) (4.8.0)
Requirement already satisfied: appnope in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from ipython>=5.5.0->pycaret) (0.1.2)
Requirement already satisfied: ipykernel>=4.5.1 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from ipywidgets>=7.6.5->pycaret) (6.25.0)
Requirement already satisfied: widgetsnbextension~=4.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from ipywidgets>=7.6.5->pycaret) (4.0.5)
Requirement already satisfied: jupyterlab-widgets~=3.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from ipywidgets>=7.6.5->pycaret) (3.0.5)
Requirement already satisfied: contourpy>=1.0.1 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.3.0->pycaret) (1.0.5)
Requirement already satisfied: cycler>=0.10 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.3.0->pycaret) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.3.0->pycaret) (4.25.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.3.0->pycaret) (1.4.4)
Requirement already satisfied: pillow>=6.2.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.3.0->pycaret) (9.4.0)
Requirement already satisfied: pyparsing<3.1,>=2.3.1 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.3.0->pycaret) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from matplotlib>=3.3.0->pycaret) (2.8.2)
Requirement already satisfied: fastjsonschema in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from nbformat>=4.2.0->pycaret) (2.16.2)
Requirement already satisfied: jsonschema>=2.6 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from nbformat>=4.2.0->pycaret) (4.17.3)
Requirement already satisfied: jupyter-core in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from nbformat>=4.2.0->pycaret) (5.3.0)
Requirement already satisfied: llvmlite<0.41,>=0.40.0dev0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from numba>=0.55.0->pycaret) (0.40.0)
Requirement already satisfied: pytz>=2020.1 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from pandas<2.0.0,>=1.3.0->pycaret) (2023.3.post1)
Requirement already satisfied: tenacity>=6.2.0 in /Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages (from plotly>=5.0.0->pycaret) (8.2.2)
Collecting dash<3.0.0,>=2.11.0 (from plotly-resampler>=0.8.3.1->pycaret)
  Obtaining dependency information for dash<3.0.0,>=2.11.0 from https://files.pythonhosted.org/packages/9b/b4/d522c16b41a8da013fd60a67f9618e57c504cd2c80e02a7a861413b93906/dash-2.13.0-py3-none-any.whl.metadata
  Using cached dash-2.13.0-py3-none-any.whl.metadata (11 kB)
INFO: pip is looking at multiple versions of plotly-resampler to determine which version is compatible with other requirements. This could take a while.
Collecting plotly-resampler>=0.8.3.1 (from pycaret)
  Obtaining dependency information for plotly-resampler>=0.8.3.1 from https://files.pythonhosted.org/packages/f2/74/ffa10e51ca8ea05299cd850c4d42112e597bfefee33ba904e8dfc5f7cbab/plotly_resampler-0.9.0-py3-none-any.whl.metadata
  Using cached plotly_resampler-0.9.0-py3-none-any.whl.metadata (12 kB)
  Obtaining dependency information for plotly-resampler>=0.8.3.1 from https://files.pythonhosted.org/packages/0c/3b/1f9aab0535f23e04f085911cd761fafc31f2e085c771b6e3c04c84d1d5cf/plotly_resampler-0.9.0rc6-py3-none-any.whl.metadata
  Downloading plotly_resampler-0.9.0rc6-py3-none-any.whl.metadata (12 kB)
Collecting jupyter-dash>=0.4.2 (from plotly-resampler>=0.8.3.1->pycaret)
  Using cached jupyter_dash-0.4.2-py3-none-any.whl (23 kB)
Collecting plotly-resampler>=0.8.3.1 (from pycaret)
  Obtaining dependency information for plotly-resampler>=0.8.3.1 from https://files.pythonhosted.org/packages/a1/4e/a01e8b5971763b2171a6920cfab8265e0964e9f42e323baf62cb86335fab/plotly_resampler-0.9.0rc5-py3-none-any.whl.metadata
  Downloading plotly_resampler-0.9.0rc5-py3-none-any.whl.metadata (12 kB)
  Obtaining dependency information for plotly-resampler>=0.8.3.1 from https://files.pythonhosted.org/packages/8b/5c/f3cdf85aac0647e3b2fbaead567b9c1cd1b0b3f8420568d0bbc17e30b021/plotly_resampler-0.9.0rc4-py3-none-any.whl.metadata
  Downloading plotly_resampler-0.9.0rc4-py3-none-any.whl.metadata (12 kB)
  Obtaining dependency information for plotly-resampler>=0.8.3.1 from https://files.pythonhosted.org/packages/a7/6d/b4ae01eec257c0a0bab5e8ebc2d04f3223556e12951e589ce94f08accbea/plotly_resampler-0.9.0rc3-py3-none-any.whl.metadata
  Downloading plotly_resampler-0.9.0rc3-py3-none-any.whl.metadata (13 kB)
  Downloading plotly_resampler-0.9.0rc2-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.5/77.5 kB 1.4 MB/s eta 0:00:00a 0:00:01
  Downloading plotly_resampler-0.9.0rc1-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.4/77.4 kB 1.1 MB/s eta 0:00:00a 0:00:01
INFO: pip is still looking at multiple versions of plotly-resampler to determine which version is compatible with other requirements. This could take a while.
  Downloading plotly_resampler-0.9.0rc0-py3-none-any.whl (77 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.2/77.2 kB 1.0 MB/s eta 0:00:00ta 0:00:01
  Downloading plotly_resampler-0.8.4rc1.tar.gz (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 1.1 MB/s eta 0:00:00a 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Requested plotly-resampler>=0.8.3.1 from https://files.pythonhosted.org/packages/d7/5e/71a9e34a36c1855d0c4e30a88405d58c4bbbe7ece802b188628a643f2cda/plotly_resampler-0.8.4rc1.tar.gz (from pycaret), but installing version 0.8.4rc1
Collecting Flask-Cors<4.0.0,>=3.0.10 (from plotly-resampler>=0.8.3.1->pycaret)
  Using cached Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
Collecting Werkzeug<=2.1.2 (from plotly-resampler>=0.8.3.1->pycaret)
  Using cached Werkzeug-2.1.2-py3-none-any.whl (224 kB)
Collecting plotly-resampler>=0.8.3.1 (from pycaret)
  Using cached plotly_resampler-0.8.3.2.tar.gz (46 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached plotly-resampler-0.8.3.1.tar.gz (68 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pandas<2.0.0,>=1.3.0 (from pycaret)
  Using cached pandas-1.5.2-cp311-cp311-macosx_11_0_arm64.whl (10.7 MB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Using cached pandas-1.5.1-cp311-cp311-macosx_11_0_arm64.whl (10.7 MB)
  Using cached pandas-1.5.0-cp311-cp311-macosx_11_0_arm64.whl (10.7 MB)
  Downloading pandas-1.5.0rc0.tar.gz (5.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 2.4 MB/s eta 0:00:0000:0100:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Requested pandas<2.0.0,>=1.3.0 from https://files.pythonhosted.org/packages/95/d5/7baf2083097a55d4ec1e456099c1c750680cea5427a24e1edd4613a9ba1e/pandas-1.5.0rc0.tar.gz (from pycaret), but installing version 1.5.0rc0
  Using cached pandas-1.4.4.tar.gz (4.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached pandas-1.4.3.tar.gz (4.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached pandas-1.4.2.tar.gz (4.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached pandas-1.4.1.tar.gz (4.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached pandas-1.4.0.tar.gz (4.9 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Downloading pandas-1.4.0rc0.tar.gz (4.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 2.4 MB/s eta 0:00:0000:0100:010m
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  WARNING: Requested pandas<2.0.0,>=1.3.0 from https://files.pythonhosted.org/packages/29/e3/6bd596d81eaf9f5b35398fdac0c535efadd9bbf8d0f859739badf9f90c63/pandas-1.4.0rc0.tar.gz (from pycaret), but installing version 1.4.0rc0
  Using cached pandas-1.3.5.tar.gz (4.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached pandas-1.3.4.tar.gz (4.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Using cached pandas-1.3.3.tar.gz (4.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/lalitchaudhari/anaconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/lf/1f6ct58d2w97x353jy20psh40000gn/T/pip-build-env-3rbg1x_w/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/lf/1f6ct58d2w97x353jy20psh40000gn/T/pip-build-env-3rbg1x_w/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/lf/1f6ct58d2w97x353jy20psh40000gn/T/pip-build-env-3rbg1x_w/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/lf/1f6ct58d2w97x353jy20psh40000gn/T/pip-build-env-3rbg1x_w/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 18, in <module>
      ModuleNotFoundError: No module named 'numpy'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Note: you may need to restart the kernel to use updated packages.

</details>

**Comment by lalitsc12** [comment]
moving to old verson of python3.10 resolved the issue
