### ISSUE TITLE
[BUG]: Incompatible with Pandas 2.0

### ISSUE THREAD

**Issue by cee-mnitin** [pycaret/pycaret#3908]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

When running pycaret 3.2.0 with pandas 2.0 and above, getting an error as follows - 

ModuleNotFoundError: No module named 'pandas.core.indexes.numeric'

Here is the stack trace - 

  File "isolation_forest_pycaret.py", line 82, in infer_outlier
    iforest_model = pycaret_anomaly.load_model(f"{model_folder}/iforest_pipeline")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycaret/anomaly/functional.py", line 993, in load_model
    return experiment.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycaret/internal/pycaret_experiment/tabular_experiment.py", line 2433, in load_model
    model = pycaret.internal.persistence.load_model(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycaret/internal/persistence.py", line 393, in load_model
    model = joblib.load(model_name)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
          ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "/usr/local/lib/python3.11/pickle.py", line 1538, in load_stack_global
    self.append(self.find_class(module, name))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pickle.py", line 1580, in find_class
    __import__(module, level=0)

Request if this can be resolved.

### Reproducible Example

```python
iforest_model = pycaret_anomaly.load_model(f"{model_folder}/iforest_pipeline")

This statement in an environment with pycaret 3.2.0 and pandas 2.2.0 generates the above error. Is f pandas is downgraded to 1.5, it works without any error.
```

### Expected Behavior

It should work with both pandas 1.5 and > 2.0

### Actual Results

```python-traceback
Error in Algo Function: Traceback (most recent call last):
  File "common_algo_funcs.py", line 123, in execute_algo
    part_results, part_errors = algo_loaded(
                                ^^^^^^^^^^^^
  File "isolation_forest_pycaret.py", line 33, in outlier_by_if
    recent_inference_results = infer_outlier_from_model(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "isolation_forest_pycaret.py", line 82, in infer_outlier_from_model
    iforest_model = pycaret_anomaly.load_model(f"{model_folder}/iforest_pipeline")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycaret/anomaly/functional.py", line 993, in load_model
    return experiment.load_model(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycaret/internal/pycaret_experiment/tabular_experiment.py", line 2433, in load_model
    model = pycaret.internal.persistence.load_model(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pycaret/internal/persistence.py", line 393, in load_model
    model = joblib.load(model_name)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
          ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "/usr/local/lib/python3.11/pickle.py", line 1538, in load_stack_global
    self.append(self.find_class(module, name))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/pickle.py", line 1580, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'pandas.core.indexes.numeric'
```

### Installed Versions

<details>
pandas 2.2.0
pycaret 3.2.0
</details>

**Comment by celestinoxp** [comment]
@cee-mnitin check with the new version of pycaret 3.3.0... if the problem is resolved you can close this issue, otherwise you should provide more details...

**Comment by tomSimonet** [comment]
Hello
I have the same pb
pycaret ab788ba255defc82b4020188dd95188f3de5f1bb
Python 3.10.12
numpy 1.26.4
pandas 2.1.4
```
ml_model = load_model('Extreme_Gradient_Boosting_2024_06_19')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/pycaret/classification/functional.py", line 2442, in load_model
    return experiment.load_model(
  File "/usr/local/lib/python3.10/site-packages/pycaret/classification/oop.py", line 3090, in load_model
    return super().load_model(
  File "/usr/local/lib/python3.10/site-packages/pycaret/internal/pycaret_experiment/tabular_experiment.py", line 2433, in load_model
    model = pycaret.internal.persistence.load_model(
  File "/usr/local/lib/python3.10/site-packages/pycaret/internal/persistence.py", line 393, in load_model
    model = joblib.load(model_name)
  File "/usr/local/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/usr/local/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/usr/local/lib/python3.10/pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "/usr/local/lib/python3.10/pickle.py", line 1538, in load_stack_global
    self.append(self.find_class(module, name))
  File "/usr/local/lib/python3.10/pickle.py", line 1580, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'pandas.core.indexes.numeric'
```

**Comment by celestinoxp** [comment]
the error occurs in load_model, right?
If you updated pycaret after training and recording your model, you must retrain the model because the pandas version was updated.

**Comment by tomSimonet** [comment]
you are completely right
many thanks !
thomas

**Comment by celestinoxp** [comment]
> you are completely right many thanks ! thomas

If you are clear and have no further questions, you can close this issue.

**Comment by moezali1** [comment]
Closing as part of the 4.0 backlog cleanup — see #4177.

PyCaret 4.0 is a ground-up rewrite (OOP-only API, sklearn-native engine, Python 3.11+, sklearn ≥ 1.7) and almost all pre-4.0 issues either reference removed APIs (`setup()`, `plot_model`, `evaluate_model`, `interpret_model`, `automl`, the legacy time-series module, the Streamlit dashboard, …) or no longer reproduce on the new code path.

**If this still affects you in 4.0, please re-file as a new issue** with:

- the experiment constructor call (`Experiment(...)`),
- the operation that fails,
- the full traceback,
- your Python / sklearn / pycaret versions.

Resources for 4.0:

- Docs: https://pycaret.org/docs
- Migrate from 3.x: https://pycaret.org/docs/guides/migrating-from-3-x
- API reference: https://pycaret.org/reference
- FAQ: https://pycaret.org/docs/resources/faqs

Thanks for filing — and apologies for the long latency. The repo had drifted; we're starting clean.
