### ISSUE TITLE
[BUG]: Linux ubuntu file permission error

### ISSUE THREAD

**Issue by Beenjamming** [pycaret/pycaret#3969]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Running into import issue with:
from pycaret.classification import load_model, predict_model

Ubuntu server
Python 3.10
pycaret version 3.3.0 

Any help is appreciated....didn't see this issue in previous posts.  

![image](https://github.com/pycaret/pycaret/assets/58114119/70580010-2462-4aa9-a6e2-fcb854b3e070)

### Reproducible Example

```python
from pycaret.classification import load_model, predict_model
```

### Expected Behavior

expected standard import to be able to successfully load models

### Actual Results

```python-traceback
>>> from pycaret.classification import load_model, predict_model
/home/benjamin_michaels/fusionmlapi/lib/python3.10/site-packages/pycaret/internal/logging.py:146: UserWarning: Could not attach a FileHandler to the logger at path logs.log! No logs will be saved.
  warnings.warn(
Traceback (most recent call last):
  File "/home/benjamin_michaels/fusionmlapi/lib/python3.10/site-packages/pycaret/internal/logging.py", line 144, in create_logger
    ch = logging.FileHandler(path)
  File "/usr/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
PermissionError: [Errno 13] Permission denied: '/home/benjamin_michaels/logs.log'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/benjamin_michaels/fusionmlapi/lib/python3.10/site-packages/pycaret/classification/__init__.py", line 1, in <module>
    from pycaret.classification.functional import (
  File "/home/benjamin_michaels/fusionmlapi/lib/python3.10/site-packages/pycaret/classification/functional.py", line 8, in <module>
    from pycaret.classification.oop import ClassificationExperiment
  File "/home/benjamin_michaels/fusionmlapi/lib/python3.10/site-packages/pycaret/classification/oop.py", line 31, in <module>
    from pycaret.internal.pycaret_experiment.non_ts_supervised_experiment import (
  File "/home/benjamin_michaels/fusionmlapi/lib/python3.10/site-packages/pycaret/internal/pycaret_experiment/non_ts_supervised_experiment.py", line 3, in <module>
    from pycaret.internal.pycaret_experiment.supervised_experiment import (
  File "/home/benjamin_michaels/fusionmlapi/lib/python3.10/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py", line 57, in <module>
    from pycaret.internal.pycaret_experiment.tabular_experiment import _TabularExperiment
  File "/home/benjamin_michaels/fusionmlapi/lib/python3.10/site-packages/pycaret/internal/pycaret_experiment/tabular_experiment.py", line 29, in <module>
    from pycaret.internal.memory import get_memory
  File "/home/benjamin_michaels/fusionmlapi/lib/python3.10/site-packages/pycaret/internal/memory.py", line 25, in <module>
    from joblib.memory import (
>>> rtError: cannot import name '_format_load_msg' from 'joblib.memory' (/home/benjamin_michaels/fusionmlapi/lib/python3.10/site-packages/joblib/memory.>>>
```

### Installed Versions

<details>
pycaret version 3.3.0 
</details>

**Comment by Beenjamming** [comment]
Should have also added that this user is an admin and I am running with sudo.....

**Comment by moezali1** [comment]
Closing as part of the 4.0 backlog cleanup — see #4177.

PyCaret 4.0 is a ground-up rewrite (OOP-only API, sklearn-native engine, Python 3.11+, sklearn ≥ 1.7) and almost all pre-4.0 issues either reference removed APIs (`setup()`, `plot_model`, `evaluate_model`, `interpret_model`, `automl`, the legacy time-series module, the Streamlit dashboard, …) or no longer reproduce on the new code path.

**If this still affects you in 4.0, please re-file as a new issue** with:

- the experiment constructor call (`Experiment(...)`),
- the operation that fails,
- the full traceback,
- your Python / sklearn / pycaret versions.

Resources for 4.0:

- Docs: https://pycaret.org/docs
- Migrate from 3.x: https://pycaret.org/docs/guides/migrating-from-3-x
- API reference: https://pycaret.org/reference
- FAQ: https://pycaret.org/docs/resources/faqs

Thanks for filing — and apologies for the long latency. The repo had drifted; we're starting clean.
