### ISSUE TITLE
[BUG]: incorrect date columns transformations 

### ISSUE THREAD

**Issue by Blacksuan19** [pycaret/pycaret#3994]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

when columns with datetime dtype have nulls during training, pycaret does not create the features `column_day`, `column_month`, `column_year`, however during inference, if the used data does not have any nulls in those same date columns, then pycaret creates those columns leading to this error

```python
ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- policies_inception_date_day
- policies_inception_date_month
- policies_inception_date_year
- policies_sold_date_day
- policies_sold_date_month
```

the columns `policies_sold` and `policies_inception` have missing values in training data but not in inference data.

the model used is a random forest which as far as I know does not handle missing values but still training completes with no issues.

this error occurred in production, when attempting to reproduce with a synthetic dataset I get a different error during setup but it is basically the same, also about date features transformation

```python
KeyError: "['start_date_year', 'start_date_month', 'start_date_day'] not in index"
```

I set some of the values in `start_date` column to None on purpose to reproduce the ValueError but ran into this error instead, it seems like pycaret is expecting those features to exist when they were not created because there are missing values in that column

### Reproducible Example

```python
import pandas as pd
import random
import numpy as np
from pycaret.classification import ClassificationExperiment
from sklearn.model_selection import train_test_split

# create synthetic data with multiple columns including a datetime column
np.random.seed(0)
n = 1000
df = pd.DataFrame(
    {
        "start_date": pd.date_range(start="1/1/2020", periods=n, freq="H"),
        "end_date": pd.date_range(start="1/1/2020", periods=n, freq="H")
        + pd.Timedelta(hours=1),
        "cat1": np.random.choice(["A", "B", "C"], n),
        "A": np.random.rand(n),
        "B": np.random.rand(n),
        "C": np.random.rand(n),
        "D": np.random.rand(n),
        "E": np.random.rand(n),
        "F": np.random.rand(n),
        "G": np.random.rand(n),
        "target": np.random.randint(0, 2, n),
    }
)

train, test = train_test_split(df, test_size=0.2, random_state=0)
train.reset_index(drop=True, inplace=True)
test.reset_index(drop=True, inplace=True)


# set 10% of dates to be missing
n_missing = int(0.1 * len(train))
missing_idx = random.sample(range(len(train)), n_missing)
train.loc[missing_idx, "start_date"] = np.nan


exp = ClassificationExperiment()

attr_dict = {
    "target": "target",
    "verbose": True,
    "memory": False,
    "log_experiment": True,
    "remove_multicollinearity": True,
    "imputation_type": None,
    "remove_outliers": False,
    "multicollinearity_threshold": 0.6,
    "fold": 5,
}

exp.setup(data=train, **attr_dict) # this fails with KeyError
```

### Expected Behavior

- pycaret will not split date columns to individual components during inference if that was not done during training.
- pycaret will not raise a KeyError about date column components if they were not created.

### Actual Results

```python-traceback
stacktrace for ValueError:


    model_preds = predict_model(model, data)
  File "/usr/local/lib/python3.10/site-packages/pycaret/classification/functional.py", line 2174, in predict_model
    return experiment.predict_model(
  File "/usr/local/lib/python3.10/site-packages/pycaret/classification/oop.py", line 2812, in predict_model
    return super().predict_model(
  File "/usr/local/lib/python3.10/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py", line 4955, in predict_model
    pred = np.nan_to_num(estimator.predict(X_test_))
  File "/usr/local/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 820, in predict
    proba = self.predict_proba(X)
  File "/usr/local/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 862, in predict_proba
    X = self._validate_X_predict(X)
  File "/usr/local/lib/python3.10/site-packages/sklearn/ensemble/_forest.py", line 602, in _validate_X_predict
    X = self._validate_data(X, dtype=DTYPE, accept_sparse="csr", reset=False)
  File "/usr/local/lib/python3.10/site-packages/sklearn/base.py", line 548, in _validate_data
    self._check_feature_names(X, reset=reset)
  File "/usr/local/lib/python3.10/site-packages/sklearn/base.py", line 481, in _check_feature_names
    raise ValueError(message)
ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- policies_inception_date_day
- policies_inception_date_month
- policies_inception_date_year
- policies_sold_date_day
- policies_sold_date_month
- ...
"


stacktrace for KeyError

```python
{
	"name": "KeyError",
	"message": "\"['start_date_year', 'start_date_month', 'start_date_day'] not in index\"",
	"stack": "---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/tmp/ipykernel_426637/1611657324.py in <cell line: 15>()
     13 }
     14 
---> 15 exp.setup(data=train, **attr_dict)

~/.local/lib/python3.10/site-packages/pycaret/classification/oop.py in setup(self, data, data_func, target, index, train_size, test_data, ordinal_features, numeric_features, categorical_features, date_features, text_features, ignore_features, keep_features, preprocess, create_date_columns, imputation_type, numeric_imputation, categorical_imputation, iterative_imputation_iters, numeric_iterative_imputer, categorical_iterative_imputer, text_features_method, max_encoding_ohe, encoding_method, rare_to_value, rare_value, polynomial_features, polynomial_degree, low_variance_threshold, group_features, drop_groups, remove_multicollinearity, multicollinearity_threshold, bin_numeric_features, remove_outliers, outliers_method, outliers_threshold, fix_imbalance, fix_imbalance_method, transformation, transformation_method, normalize, normalize_method, pca, pca_method, pca_components, feature_selection, feature_selection_method, feature_selection_estimator, n_features_to_select, custom_pipeline, custom_pipeline_position, data_split_shuffle, data_split_stratify, fold_strategy, fold, fold_shuffle, fold_groups, n_jobs, use_gpu, html, session_id, system_log, log_experiment, experiment_name, experiment_custom_tags, log_plots, log_profile, log_data, engine, verbose, memory, profile, profile_kwargs)
    908             )
    909         container.append([\"Original data shape\", self.data.shape])
--> 910         container.append([\"Transformed data shape\", self.dataset_transformed.shape])
    911         container.append([\"Transformed train set shape\", self.train_transformed.shape])
    912         container.append([\"Transformed test set shape\", self.test_transformed.shape])

~/.local/lib/python3.10/site-packages/pycaret/internal/pycaret_experiment/non_ts_supervised_experiment.py in dataset_transformed(self)
     33     def dataset_transformed(self):
     34         \"\"\"Transformed dataset.\"\"\"
---> 35         return pd.concat([self.train_transformed, self.test_transformed])
     36 
     37     @property

~/.local/lib/python3.10/site-packages/pycaret/internal/pycaret_experiment/non_ts_supervised_experiment.py in test_transformed(self)
     54         return pd.concat(
     55             [
---> 56                 *self.pipeline.transform(
     57                     X=self.X_test,
     58                     y=self.y_test,

~/.local/lib/python3.10/site-packages/pycaret/internal/pipeline.py in transform(self, X, y, filter_train_only)
    287 
    288     def transform(self, X=None, y=None, filter_train_only=True):
--> 289         X, y = self._memory_full_transform(
    290             self,
    291             X,

~/.local/lib/python3.10/site-packages/joblib/memory.py in __call__(self, *args, **kwargs)
    347 
    348     def __call__(self, *args, **kwargs):
--> 349         return self.func(*args, **kwargs)
    350 
    351     def call_and_shelve(self, *args, **kwargs):

~/.local/lib/python3.10/site-packages/pycaret/internal/pipeline.py in _full_transform(pipeline, X, y, **kwargs)
    109 def _full_transform(pipeline: \"Pipeline\", X, y, **kwargs):
    110     for _, _, transformer in pipeline._iter(**kwargs):
--> 111         X, y = pipeline._memory_transform(transformer, X, y)
    112     return X, y
    113 

~/.local/lib/python3.10/site-packages/joblib/memory.py in __call__(self, *args, **kwargs)
    347 
    348     def __call__(self, *args, **kwargs):
--> 349         return self.func(*args, **kwargs)
    350 
    351     def call_and_shelve(self, *args, **kwargs):

~/.local/lib/python3.10/site-packages/pycaret/internal/pipeline.py in _transform_one(transformer, X, y)
     78     if \"y\" in signature(transformer.transform).parameters:
     79         args.append(y)
---> 80     output = transformer.transform(*args)
     81 
     82     if isinstance(output, tuple):

~/.local/lib/python3.10/site-packages/sklearn/utils/_set_output.py in wrapped(self, X, *args, **kwargs)
    293     @wraps(f)
    294     def wrapped(self, X, *args, **kwargs):
--> 295         data_to_wrap = f(self, X, *args, **kwargs)
    296         if isinstance(data_to_wrap, tuple):
    297             # only wrap the first output for cross decomposition

~/.local/lib/python3.10/site-packages/pycaret/internal/preprocess/transformers.py in transform(self, X, y)
    246             else:
    247                 return variable_return(X, y)
--> 248             args.append(X[self._include])
    249         if \"y\" in transform_params:
    250             if y is not None:

~/.local/lib/python3.10/site-packages/pandas/core/frame.py in __getitem__(self, key)
   3897             if is_iterator(key):
   3898                 key = list(key)
-> 3899             indexer = self.columns._get_indexer_strict(key, \"columns\")[1]
   3900 
   3901         # take() does not accept boolean indexers

~/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py in _get_indexer_strict(self, key, axis_name)
   6113             keyarr, indexer, new_indexer = self._reindex_non_unique(keyarr)
   6114 
-> 6115         self._raise_if_missing(keyarr, indexer, axis_name)
   6116 
   6117         keyarr = self.take(indexer)

~/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py in _raise_if_missing(self, key, indexer, axis_name)
   6177 
   6178             not_found = list(ensure_index(key)[missing_mask.nonzero()[0]].unique())
-> 6179             raise KeyError(f\"{not_found} not in index\")
   6180 
   6181     @overload

KeyError: \"['start_date_year', 'start_date_month', 'start_date_day'] not in index\""
}
```
```


### Installed Versions

<details>
3.3.2
</details>

**Comment by moezali1** [comment]
Closing as part of the 4.0 backlog cleanup — see #4177.

PyCaret 4.0 is a ground-up rewrite (OOP-only API, sklearn-native engine, Python 3.11+, sklearn ≥ 1.7) and almost all pre-4.0 issues either reference removed APIs (`setup()`, `plot_model`, `evaluate_model`, `interpret_model`, `automl`, the legacy time-series module, the Streamlit dashboard, …) or no longer reproduce on the new code path.

**If this still affects you in 4.0, please re-file as a new issue** with:

- the experiment constructor call (`Experiment(...)`),
- the operation that fails,
- the full traceback,
- your Python / sklearn / pycaret versions.

Resources for 4.0:

- Docs: https://pycaret.org/docs
- Migrate from 3.x: https://pycaret.org/docs/guides/migrating-from-3-x
- API reference: https://pycaret.org/reference
- FAQ: https://pycaret.org/docs/resources/faqs

Thanks for filing — and apologies for the long latency. The repo had drifted; we're starting clean.
