### ISSUE TITLE
[BUG]: cannot import name '_print_elapsed_time' from 'sklearn.utils' 

### ISSUE THREAD

**Issue by newne** [pycaret/pycaret#4017]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

import pycaret clustering  module reslut in sklearn errors in prod. but  it works in dev.  Here is my device info :
```
root@leap-Lenovo-EPC-600:/home/algorithm/cloud_edge_collaboration# cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.4 LTS"
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
root@leap-Lenovo-EPC-600:/home/algorithm/cloud_edge_collaboration# uname -a
Linux leap-Lenovo-EPC-600 6.2.0-26-generic #26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Jul 13 16:27:29 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
r
```

### Reproducible Example

```python
from pycaret.clustering import assign_model, create_model, setup
```

### Expected Behavior

import pycaret have an error.

### Actual Results

```python-traceback
Traceback (most recent call last):
  File "/root/bin/main.py", line 2, in <module>
    from scheduling.add_scheduler_job import start_jobs
  File "/root/bin/scheduling/add_scheduler_job.py", line 10, in <module>
    from logic.start_time_prediction import predict_start_time_type
  File "/root/bin/logic/start_time_prediction.py", line 5, in <module>
    from pycaret.clustering import assign_model, create_model, setup
  File "/opt/venv/lib/python3.9/site-packages/pycaret/clustering/__init__.py", line 1, in <module>
    from pycaret.clustering.functional import (
  File "/opt/venv/lib/python3.9/site-packages/pycaret/clustering/functional.py", line 8, in <module>
    from pycaret.clustering.oop import ClusteringExperiment
  File "/opt/venv/lib/python3.9/site-packages/pycaret/clustering/oop.py", line 6, in <module>
    import pycaret.internal.patches.sklearn
  File "/opt/venv/lib/python3.9/site-packages/pycaret/internal/patches/sklearn.py", line 9, in <module>
    from pycaret.internal.pipeline import pipeline_predict_inverse_only
  File "/opt/venv/lib/python3.9/site-packages/pycaret/internal/pipeline.py", line 19, in <module>
    from sklearn.utils import _print_elapsed_time
ImportError: cannot import name '_print_elapsed_time' from 'sklearn.utils' (/opt/venv/lib/python3.9/site-packages/sklearn/utils/__init__.py)
```

### Installed Versions

APScheduler==3.10.4
chinese_calendar==1.9.1
dynaconf==3.2.5
loguru==0.7.2
numpy==1.24.4
pandas==1.5.3
plotly==5.18.0
pycaret==3.3.0
python_dateutil==2.9.0.post0
Requests==2.32.3
SQLAlchemy==1.4.44
streamlit==1.36.0
tenacity==8.1.0
joblib==1.3.2

**Comment by celestinoxp** [comment]
I have already fixed this error and it will be merged into the code once the pull-request (https://github.com/pycaret/pycaret/pull/4009) is ready and approved.

This error is due to the change of function in the scikit-learn 1.5 directory... Pycaret only supports scikit-learn 1.4.

If you want to contribute: https://github.com/pycaret/pycaret/pull/4009
