### ISSUE TITLE
[BUG]: AttributeError for `log_profile=True`

### ISSUE THREAD

**Issue by dsmarda-ai-10** [pycaret/pycaret#4023]
### pycaret version checks

- [X] I have checked that this issue has not already been reported [here](https://github.com/pycaret/pycaret/issues).

- [X] I have confirmed this bug exists on the [latest version](https://github.com/pycaret/pycaret/releases) of pycaret.

- [X] I have confirmed this bug exists on the master branch of pycaret (pip install -U git+https://github.com/pycaret/pycaret.git@master).

### Issue Description

Code throws AttributeError when `log_profile` parameter in `setup` is set to `True`. This error does not appear when other logging parameters are set to `True` (i.e., `log_plots`, only when `log_profile` is `True`).
Installation note: using all packages included with `pip install pycaret[full]`.

### Reproducible Example

```python
from pycaret.classification import ClassificationExperiment
from pycaret.datasets import get_data
data = get_data('diabetes')
print(data.columns)
exp = ClassificationExperiment()
exp.setup(data, target='Class variable', session_id=1, log_experiment=True, log_profile=True)
```

### Expected Behavior

Expect `setup()` function to run to completion and output `setup` DataFrame.

### Actual Results

```python-traceback
Traceback (most recent call last):
  File "/home/dsmarda/demo/usp_experiments/src/models/pycaret_bug.py", line 6, in <module>
    exp.setup(data, target='Class variable', session_id=1, log_experiment=True, log_profile=True)
  File "/home/dsmarda/demo/.venv/lib/python3.10/site-packages/pycaret/classification/oop.py", line 1014, in setup
    self._set_up_logging(
  File "/home/dsmarda/demo/.venv/lib/python3.10/site-packages/pycaret/internal/pycaret_experiment/supervised_experiment.py", line 268, in _set_up_logging
    self.logging_param.log_experiment(
  File "/home/dsmarda/demo/.venv/lib/python3.10/site-packages/pycaret/loggers/dashboard_logger.py", line 240, in log_experiment
    experiment.report.to_file(profile_path)
AttributeError: 'ClassificationExperiment' object has no attribute 'report'
```

### Installed Versions

<details>
System:
    python: 3.10.12 (main, Mar 22 2024, 16:50:05) [GCC 11.4.0]
executable: /home/dsmarda/demo/.venv/bin/python
   machine: Linux-5.15.0-113-generic-x86_64-with-glibc2.35

PyCaret required dependencies:
                 pip: 22.0.2
          setuptools: 59.6.0
             pycaret: 3.4.0
             IPython: 8.24.0
          ipywidgets: 8.1.2
                tqdm: 4.66.4
               numpy: 1.26.4
              pandas: 2.2.2
              jinja2: 3.1.4
               scipy: 1.11.4
              joblib: 1.3.2
             sklearn: 1.4.2
                pyod: 1.1.3
            imblearn: 0.12.2
   category_encoders: 2.6.3
            lightgbm: 4.3.0
               numba: 0.59.1
            requests: 2.32.1
          matplotlib: 3.7.5
          scikitplot: 0.3.7
         yellowbrick: 1.5
              plotly: 5.22.0
    plotly-resampler: Not installed
             kaleido: 0.2.1
           schemdraw: 0.15
         statsmodels: 0.14.2
              sktime: 0.31.0
               tbats: 1.1.3
            pmdarima: 2.0.4
              psutil: 5.9.8
          markupsafe: 2.1.5
             pickle5: Not installed
         cloudpickle: 3.0.0
         deprecation: 2.1.0
              xxhash: 3.4.1
           wurlitzer: 3.1.0

PyCaret optional dependencies:
                shap: 0.44.1
           interpret: 0.6.2
                umap: 0.5.6
     ydata_profiling: 4.8.3
  explainerdashboard: 0.4.7
             autoviz: Not installed
           fairlearn: 0.7.0
          deepchecks: Not installed
             xgboost: 2.1.0
            catboost: 1.2.5
              kmodes: 0.12.2
             mlxtend: 0.23.1
       statsforecast: 1.5.0
        tune_sklearn: 0.5.0
                 ray: 2.32.0
            hyperopt: 0.2.7
              optuna: 3.6.1
               skopt: 0.10.2
              mlflow: 2.13.0
              gradio: 4.31.4
             fastapi: 0.111.0
             uvicorn: 0.29.0
              m2cgen: 0.10.0
           evidently: 0.4.23
               fugue: 0.8.7
           streamlit: Not installed
             prophet: Not installed
</details>

**Comment by moezali1** [comment]
Closing as part of the 4.0 backlog cleanup — see #4177.

PyCaret 4.0 is a ground-up rewrite (OOP-only API, sklearn-native engine, Python 3.11+, sklearn ≥ 1.7) and almost all pre-4.0 issues either reference removed APIs (`setup()`, `plot_model`, `evaluate_model`, `interpret_model`, `automl`, the legacy time-series module, the Streamlit dashboard, …) or no longer reproduce on the new code path.

**If this still affects you in 4.0, please re-file as a new issue** with:

- the experiment constructor call (`Experiment(...)`),
- the operation that fails,
- the full traceback,
- your Python / sklearn / pycaret versions.

Resources for 4.0:

- Docs: https://pycaret.org/docs
- Migrate from 3.x: https://pycaret.org/docs/guides/migrating-from-3-x
- API reference: https://pycaret.org/reference
- FAQ: https://pycaret.org/docs/resources/faqs

Thanks for filing — and apologies for the long latency. The repo had drifted; we're starting clean.
