### ISSUE TITLE
Tune model  method in ligthgbm fails

### ISSUE THREAD

**Issue by DXcarlos** [pycaret/pycaret#684]
I'm trying to tune a ligthgbm model  but it fails.
Here is my code :

```python
lgb = create_model('lightgbm', fold=10)
tuned_lgb = tune_model(lgb)
```

I get this error

```python
Traceback (most recent call last):
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-30-d02aa8244dd2>", line 1, in <module>
    tuned_lgb = tune_model(lgb)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\pycaret\classification.py", line 4649, in tune_model
    mcc = metrics.matthews_corrcoef(ytest,pred_)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    return f(**kwargs)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\sklearn\metrics\_classification.py", line 846, in matthews_corrcoef
    mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
FloatingPointError: invalid value encountered in double_scalars
```

When I use catboost as estimator it doesn't throw a error unless I use the parameter optimize='AUC' I don't know why

**Comment by pycaret** [comment]
@DXcarlos Can you try updating your `lightgbm` version by `pip install --upgrade lightgbm`.

Let me know how it goes.
