### ISSUE TITLE
pip installation error

### ISSUE THREAD

**Issue by kevin7lou** [pycaret/pycaret#69]
Would you pls help to check `pip` installation error? Thanks!
```
abc@jackloumbp  ~  pip install pycaret                                           ✔  12:43:02

Collecting pycaret
  Downloading pycaret-1.0.0-py3-none-any.whl (188 kB)
     |████████████████████████████████| 188 kB 640 kB/s
Collecting cufflinks==0.17.0
  Downloading cufflinks-0.17.0.tar.gz (81 kB)
     |████████████████████████████████| 81 kB 3.1 MB/s
Collecting catboost==0.20.2
  Downloading catboost-0.20.2-cp37-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (10.6 MB)
     |████████████████████████████████| 10.6 MB 902 kB/s
Collecting plotly==4.4.1
  Downloading plotly-4.4.1-py2.py3-none-any.whl (7.3 MB)
     |████████████████████████████████| 7.3 MB 7.0 MB/s
Requirement already satisfied: IPython in ./anaconda3/lib/python3.7/site-packages (from pycaret) (7.13.0)
Collecting yellowbrick==1.0.1
  Downloading yellowbrick-1.0.1-py3-none-any.whl (378 kB)
     |████████████████████████████████| 378 kB 5.5 MB/s
Collecting pyod
  Downloading pyod-0.7.8.2.tar.gz (92 kB)
     |████████████████████████████████| 92 kB 588 kB/s
Collecting scikit-learn==0.22
  Downloading scikit_learn-0.22-cp37-cp37m-macosx_10_6_intel.whl (10.9 MB)
     |████████████████████████████████| 10.9 MB 3.8 MB/s
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from pycaret) (1.18.1)
Collecting lightgbm==2.3.1
  Downloading lightgbm-2.3.1-py2.py3-none-macosx_10_9_x86_64.macosx_10_10_x86_64.macosx_10_11_x86_64.macosx_10_12_x86_64.macosx_10_13_x86_64.macosx_10_14_x86_64.macosx_10_15_x86_64.whl (679 kB)
     |████████████████████████████████| 679 kB 4.0 MB/s
Collecting spacy
  Downloading spacy-2.2.4-cp37-cp37m-macosx_10_9_x86_64.whl (10.5 MB)
     |████████████████████████████████| 10.5 MB 587 kB/s
Collecting xgboost==0.90
  Downloading xgboost-0.90.tar.gz (676 kB)
     |████████████████████████████████| 676 kB 4.7 MB/s
    ERROR: Command errored out with exit status 1:
     command: /Users/abc/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/cw/l7p44klx78d56bz5mxxn3yjr0000gn/T/pip-install-li62go4h/xgboost/setup.py'"'"'; __file__='"'"'/private/var/folders/cw/l7p44klx78d56bz5mxxn3yjr0000gn/T/pip-install-li62go4h/xgboost/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/cw/l7p44klx78d56bz5mxxn3yjr0000gn/T/pip-install-li62go4h/xgboost/pip-egg-info
         cwd: /private/var/folders/cw/l7p44klx78d56bz5mxxn3yjr0000gn/T/pip-install-li62go4h/xgboost/
    Complete output (147 lines):
    ++ pwd
    + oldpath=/private/var/folders/cw/l7p44klx78d56bz5mxxn3yjr0000gn/T/pip-install-li62go4h/xgboost
    + cd ./xgboost/
    + grep -q darwin
    + echo darwin19
    + LIB_XGBOOST=libxgboost.dylib
    + which g++-5
    + which g++-7
    + which g++-8
    + which clang++
    /Users/abc/anaconda3/bin/clang++
    + export CC=clang
    + CC=clang
    + export CXX=clang++
    + CXX=clang++
    + make clean
    Makefile:31: MAKE [make] - checked OK
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o #xgboost
    rm -f -rf build_tests *.gcov tests/cpp/xgboost_test
    if [ -d "R-package/src" ]; then \
    	cd R-package/src; \
    	rm -f -rf rabit src include dmlc-core amalgamation *.so *.dll; \
    	cd /private/var/folders/cw/l7p44klx78d56bz5mxxn3yjr0000gn/T/pip-install-li62go4h/xgboost/xgboost; \
    fi
    + make lib/libxgboost.dylib -j4
    Makefile:31: MAKE [make] - checked OK
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/learner.o src/learner.cc >build/learner.d
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/logging.o src/logging.cc >build/logging.d
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/tree/tree_model.o src/tree/tree_model.cc >build/tree/tree_model.d
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -fopenmp -MM -MT build/tree/updater_histmaker.o src/tree/updater_histmaker.cc >build/tree/updater_histmaker.d
    In file included from src/learner.cc:7:
    In file included from dmlc-core/include/dmlc/io.h:8:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/cstdio:100:
    /Users/abc/anaconda3/bin/../include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
    In file included from src/tree/tree_model.cc:6:
    In file included from include/xgboost/tree_model.h:10:
    In file included from dmlc-core/include/dmlc/io.h:8:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/cstdio:100:
    /Users/abc/anaconda3/bin/../include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
    #include_next <stdio.h>
                  ^~~~~~~~~
    #include_next <stdio.h>
                  ^~~~~~~~~
    In file included from src/logging.cc:7:
    In file included from rabit/include/rabit/rabit.h:13:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/string:470:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/string_view:171:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/__string:56:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/algorithm:638:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/cstring:61:
    /Users/abc/anaconda3/bin/../include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
    #include_next <string.h>
                  ^~~~~~~~~~
    In file included from src/tree/updater_histmaker.cc:7:
    In file included from rabit/include/rabit/rabit.h:13:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/string:470:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/string_view:171:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/__string:56:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/algorithm:638:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/cstring:61:
    /Users/abc/anaconda3/bin/../include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
    #include_next <string.h>
                  ^~~~~~~~~~
    1 error generated.
    1 error generated.
    make: *** [Makefile:141: build/logging.o] Error 1
    make: *** Waiting for unfinished jobs....
    make: *** [Makefile:141: build/tree/tree_model.o] Error 1
    1 error generated.
    1 error generated.
    make: *** [Makefile:141: build/tree/updater_histmaker.o] Error 1
    make: *** [Makefile:141: build/learner.o] Error 1
    + echo -----------------------------
    -----------------------------
    + echo 'Building multi-thread xgboost failed'
    Building multi-thread xgboost failed
    + echo 'Start to build single-thread xgboost'
    Start to build single-thread xgboost
    + make clean
    Makefile:31: MAKE [make] - checked OK
    rm -f -rf build build_plugin lib bin *~ */*~ */*/*~ */*/*/*~ */*.o */*/*.o */*/*/*.o #xgboost
    rm -f -rf build_tests *.gcov tests/cpp/xgboost_test
    if [ -d "R-package/src" ]; then \
    	cd R-package/src; \
    	rm -f -rf rabit src include dmlc-core amalgamation *.so *.dll; \
    	cd /private/var/folders/cw/l7p44klx78d56bz5mxxn3yjr0000gn/T/pip-install-li62go4h/xgboost/xgboost; \
    fi
    + make lib/libxgboost.dylib -j4 USE_OPENMP=0
    Makefile:31: MAKE [make] - checked OK
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/logging.o src/logging.cc >build/logging.d
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/tree/tree_model.o src/tree/tree_model.cc >build/tree/tree_model.d
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/learner.o src/learner.cc >build/learner.d
    clang++ -DDMLC_LOG_CUSTOMIZE=1 -std=c++11 -Wall -Wno-unknown-pragmas -Iinclude   -Idmlc-core/include -Irabit/include -I/include -O3 -funroll-loops -msse2 -fPIC -DDISABLE_OPENMP -MM -MT build/tree/updater_histmaker.o src/tree/updater_histmaker.cc >build/tree/updater_histmaker.d
    In file included from src/tree/tree_model.cc:6:
    In file included from include/xgboost/tree_model.h:10:
    In file included from dmlc-core/include/dmlc/io.h:8:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/cstdio:100:
    /Users/abc/anaconda3/bin/../include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
    #include_next <stdio.h>
                  ^~~~~~~~~
    In file included from src/learner.cc:7:
    In file included from dmlc-core/include/dmlc/io.h:8:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/cstdio:100:
    /Users/abc/anaconda3/bin/../include/c++/v1/stdio.h:108:15: fatal error: 'stdio.h' file not found
    #include_next <stdio.h>
                  ^~~~~~~~~
    In file included from src/logging.cc:7:
    In file included from rabit/include/rabit/rabit.h:13:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/string:470:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/string_view:171:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/__string:56:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/algorithm:638:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/cstring:61:
    /Users/abc/anaconda3/bin/../include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
    #include_next <string.h>
                  ^~~~~~~~~~
    In file included from src/tree/updater_histmaker.cc:7:
    In file included from rabit/include/rabit/rabit.h:13:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/string:470:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/string_view:171:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/__string:56:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/algorithm:638:
    In file included from /Users/abc/anaconda3/bin/../include/c++/v1/cstring:61:
    /Users/abc/anaconda3/bin/../include/c++/v1/string.h:61:15: fatal error: 'string.h' file not found
    #include_next <string.h>
                  ^~~~~~~~~~
    1 error generated.
    make: *** [Makefile:141: build/logging.o] Error 1
    make: *** Waiting for unfinished jobs....
    1 error generated.
    make: *** [Makefile:141: build/tree/tree_model.o] Error 1
    1 error generated.
    make: *** [Makefile:141: build/tree/updater_histmaker.o] Error 1
    1 error generated.
    make: *** [Makefile:141: build/learner.o] Error 1
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cw/l7p44klx78d56bz5mxxn3yjr0000gn/T/pip-install-li62go4h/xgboost/setup.py", line 42, in <module>
        LIB_PATH = libpath['find_lib_path']()
      File "/private/var/folders/cw/l7p44klx78d56bz5mxxn3yjr0000gn/T/pip-install-li62go4h/xgboost/xgboost/libpath.py", line 48, in find_lib_path
        'List of candidates:\n' + ('\n'.join(dll_path)))
    XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
    List of candidates:
    /private/var/folders/cw/l7p44klx78d56bz5mxxn3yjr0000gn/T/pip-install-li62go4h/xgboost/xgboost/libxgboost.dylib
    /private/var/folders/cw/l7p44klx78d56bz5mxxn3yjr0000gn/T/pip-install-li62go4h/xgboost/xgboost/../../lib/libxgboost.dylib
    /private/var/folders/cw/l7p44klx78d56bz5mxxn3yjr0000gn/T/pip-install-li62go4h/xgboost/xgboost/./lib/libxgboost.dylib
    /Users/abc/anaconda3/xgboost/libxgboost.dylib
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by DaGuT** [comment]
@pycaret  this can easily be solved by letting people install more recent version of xgboost (older versions can not be compiled on recent mac machines, I had the same problem).

To author:
Just install it with 
`pip install xgboost pycaret`

This will force install the latest version of xgboost and ignore requirements from pycaret (and it's okay, since they are compatible)

**Comment by kevin7lou** [comment]
> @pycaret this can easily be solved by letting people install more recent version of xgboost (older versions can not be compiled on recent mac machines, I had the same problem).
> 
> To author:
> Just install it with
> `pip install xgboost==1.0.2 pycaret`
> 
> This will force install the latest version (atm) of xgboost and ignore requirements from pycaret (and it's okay, since they are compatible). And then just ignore erros saying xgboost should be downgraded

Hi @DaGuT , your method is working! Thank you a lot! 👍 
Before installing pycaret, I tried to install xgboost alone with `pip install xgboost`, but the system showed the long error message with "cmake not found". In this case, I installed cmake firstly.
`pip install cmake`
Then I installed pycarent with 
`pip install xgboost==1.0.2 pycaret` and ignore erros saying xgboost should be downgraded.

Thank you a lot!
