### ISSUE TITLE
ML Flow integration throws an error

### ISSUE THREAD

**Issue by DXcarlos** [pycaret/pycaret#755]
I'm creating this experiment it seems that there is no problems

``` python

clf1 = setup(train_df,
             target=columns_metadata['label'][0],
             ignore_features=columns_metadata['keys'] + columns_metadata['ignore'],
             session_id=499,
             categorical_features=columns_metadata['categorical'],
             numeric_features=columns_metadata['numeric'] + columns_metadata['flags'],
             numeric_imputation='zero',
             high_cardinality_features=columns_metadata['high_cardinality'],
             high_cardinality_method='clustering',
             experiment_name='MT online',
             feature_selection=True,
             feature_selection_method='boruta',
             feature_selection_threshold=0.8,
             log_experiment=True,
             remove_multicollinearity=True,
             multicollinearity_threshold=0.80,
             use_gpu=True,
             profile=True,
             silent=True,
             html=False)
```
```
2020-10-23 14:44:40 :: logs :: INFO :: Checking libraries
2020-10-23 14:44:40 :: logs :: INFO :: pd==1.1.1
2020-10-23 14:44:40 :: logs :: INFO :: numpy==1.19.1
2020-10-23 14:44:40 :: logs :: INFO :: sklearn==0.23.2
2020-10-23 14:44:40 :: logs :: INFO :: xgboost==1.2.0
2020-10-23 14:44:41 :: logs :: INFO :: lightgbm==3.0.0
2020-10-23 14:44:43 :: logs :: INFO :: catboost==0.24.1
2020-10-23 14:44:49 :: logs :: INFO :: mlflow==1.11.0
```
My mlflow version is mlflow==1.11.0

But when I compare models I got this error

``` python
best_specific = compare_models(include=['catboost', 'lightgbm', 'xgboost'], sort='AUC')
```

When I create the log 

```
2020-10-23 14:49:37 :: logs :: INFO :: Creating metrics dataframe
2020-10-23 14:49:37 :: logs :: INFO :: Creating MLFlow logs
Traceback (most recent call last):
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\IPython\core\interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-3c0a6c937dff>", line 1, in <module>
    best_specific = compare_models(include=['catboost', 'lightgbm', 'xgboost'], sort='AUC')
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\pycaret\classification.py", line 2650, in compare_models
    mlflow.sklearn.log_model(prep_pipe_temp, "model", conda_env = default_conda_env, signature = signature, input_example = input_example)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\mlflow\sklearn\__init__.py", line 290, in log_model
    return Model.log(
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\mlflow\models\model.py", line 160, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\mlflow\sklearn\__init__.py", line 171, in save_model
    _save_example(mlflow_model, input_example, path)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\mlflow\models\utils.py", line 131, in _save_example
    example = _Example(input_example)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\mlflow\models\utils.py", line 67, in __init__
    input_example = pd.DataFrame.from_dict(input_example)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\pandas\core\frame.py", line 1309, in from_dict
    return cls(data, index=index, columns=columns, dtype=dtype)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\pandas\core\frame.py", line 468, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\pandas\core\internals\construction.py", line 283, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\pandas\core\internals\construction.py", line 78, in arrays_to_mgr
    index = extract_index(arrays)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\pandas\core\internals\construction.py", line 387, in extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index
```

**Comment by pycaret** [comment]
@DXcarlos What is the version of pycaret? Can you please upload `logs.log` file here?

**Comment by eccodolf** [comment]
Same error ater trying to log to mlflow. 
Appears after trying to finish any model (compare_model, create_model). 
With log_experiment=False in setup everything goes normal. Except there are no logs in mlflow to track experiments..
Pycaret==2.1.2 mlflow=1.2.0 pandas = 1.1.4
