### ISSUE TITLE
Unable to load model in pycaret 2.2.0

### ISSUE THREAD

**Issue by sagarnildass** [pycaret/pycaret#825]
Hi 

I am unable to load a model. I tried loading both from aws and local via:

1. load_model(model_name='titanic_model_sagarnil', platform='aws', authentication={'bucket': 'bucket_name'}, verbose=False)
2. load_model('titanic_model_sagarnil')

In both cases, the following error is thrown: ModuleNotFoundError: No module named 'pycaret.preprocess'

Here's the full stack trace:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/site-packages/pycaret/classification.py", line 2111, in load_model
    verbose=verbose,
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/site-packages/pycaret/internal/tabular.py", line 8891, in load_model
    model_name, platform, authentication, verbose
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/site-packages/pycaret/internal/persistence.py", line 370, in load_model
    return joblib.load(model_name)
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/pickle.py", line 1088, in load
    dispatch[key[0]](self)
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/pickle.py", line 1376, in load_global
    klass = self.find_class(module, name)
  File "/home/sagarnildass/anaconda3/envs/cyberdeck/lib/python3.7/pickle.py", line 1426, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'pycaret.preprocess'

**Comment by Yard1** [comment]
If those models were created with an earlier version of pycaret, they may not work correctly.

**Comment by sagarnildass** [comment]
Got it! Thanks a lot.
