### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64'). 

### ISSUE THREAD

**Issue by weishunc5** [pycaret/pycaret#844]
I am running the following code.

from pycaret.regression import *

pipeline = setup(data = train, target = 'SalePrice', 
                 categorical_features = cat_feat, 
                 ordinal_features = ordinal_dict, 
                 high_cardinality_features = high_cardinal_feat,   
                 ignore_features = ignore_feat, 
                 numeric_imputation = 'median',
                 normalize = True,
                 ignore_low_variance = True,
                 combine_rare_levels = True,
                 remove_outliers = True,
                 transform_target = True,
                 session_id = 1)

compare_models(include = ['lr', 'ridge', 'lasso', 'rf', 'xgboost', 'lightgbm'], fold = 5, sort = 'RMSE', errors = 'raise')

and the error exists. I have checked each column, there is no infinity value. Hence I have no idea how there is missing value with missing value imputers.

Here is the error traceback:
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/opt/conda/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 608, in __call__
    return self.func(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/joblib/parallel.py", line 256, in __call__
    for func, args, kwargs in self.items]
  File "/opt/conda/lib/python3.7/site-packages/joblib/parallel.py", line 256, in <listcomp>
    for func, args, kwargs in self.items]
  File "/opt/conda/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 560, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 607, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_scorer.py", line 88, in __call__
    *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_scorer.py", line 213, in _score
    **self._kwargs)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_regression.py", line 179, in mean_absolute_error
    y_true, y_pred, multioutput)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/metrics/_regression.py", line 86, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py", line 645, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py", line 99, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-174-451e9b4a8e48> in <module>
----> 1 compare_models(include = ['lr', 'ridge', 'lasso', 'rf', 'xgboost', 'lightgbm'], fold = 5, sort = 'RMSE', errors = 'raise')

/opt/conda/lib/python3.7/site-packages/pycaret/regression.py in compare_models(include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, verbose)
    774         fit_kwargs=fit_kwargs,
    775         groups=groups,
--> 776         verbose=verbose,
    777     )
    778 

/opt/conda/lib/python3.7/site-packages/pycaret/internal/tabular.py in compare_models(include, exclude, fold, round, cross_validation, sort, n_select, budget_time, turbo, errors, fit_kwargs, groups, verbose, display)
   2129                 fit_kwargs=fit_kwargs,
   2130                 groups=groups,
-> 2131                 refit=False,
   2132             )
   2133             model_results = pull(pop=True)

/opt/conda/lib/python3.7/site-packages/pycaret/internal/tabular.py in create_model_supervised(estimator, fold, round, cross_validation, predict, fit_kwargs, groups, refit, verbose, system, X_train_data, y_train_data, metrics, display, **kwargs)
   3087             n_jobs=n_jobs,
   3088             return_train_score=False,
-> 3089             error_score=0,
   3090         )
   3091         model_fit_end = time.time()

/opt/conda/lib/python3.7/site-packages/sklearn/utils/validation.py in inner_f(*args, **kwargs)
     70                           FutureWarning)
     71         kwargs.update({k: arg for k, arg in zip(sig.parameters, args)})
---> 72         return f(**kwargs)
     73     return inner_f
     74 

/opt/conda/lib/python3.7/site-packages/sklearn/model_selection/_validation.py in cross_validate(estimator, X, y, groups, scoring, cv, n_jobs, verbose, fit_params, pre_dispatch, return_train_score, return_estimator, error_score)
    246             return_times=True, return_estimator=return_estimator,
    247             error_score=error_score)
--> 248         for train, test in cv.split(X, y, groups))
    249 
    250     zipped_scores = list(zip(*scores))

/opt/conda/lib/python3.7/site-packages/joblib/parallel.py in __call__(self, iterable)
   1015 
   1016             with self._backend.retrieval_context():
-> 1017                 self.retrieve()
   1018             # Make sure that we get a last message telling us we are done
   1019             elapsed_time = time.time() - self._start_time

/opt/conda/lib/python3.7/site-packages/joblib/parallel.py in retrieve(self)
    907             try:
    908                 if getattr(self._backend, 'supports_timeout', False):
--> 909                     self._output.extend(job.get(timeout=self.timeout))
    910                 else:
    911                     self._output.extend(job.get())

/opt/conda/lib/python3.7/site-packages/joblib/_parallel_backends.py in wrap_future_result(future, timeout)
    560         AsyncResults.get from multiprocessing."""
    561         try:
--> 562             return future.result(timeout=timeout)
    563         except LokyTimeoutError:
    564             raise TimeoutError()

/opt/conda/lib/python3.7/concurrent/futures/_base.py in result(self, timeout)
    433                 raise CancelledError()
    434             elif self._state == FINISHED:
--> 435                 return self.__get_result()
    436             else:
    437                 raise TimeoutError()

/opt/conda/lib/python3.7/concurrent/futures/_base.py in __get_result(self)
    382     def __get_result(self):
    383         if self._exception:
--> 384             raise self._exception
    385         else:
    386             return self._result

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by Yard1** [comment]
Would it be possible for you to share the notebook and dataset?

**Comment by weishunc5** [comment]
> Would it be possible for you to share the notebook and dataset?

https://www.kaggle.com/damnguychen/houseprice-pycaret

Here is the link. Thanks in advance!

**Comment by pycaret** [comment]
@weishunc5 This is the link to the competition, not the Notebook itself. If you still need help on this, please upload a reproducible Notebook that generates this error along with the data.

**Comment by Arun-Chhikara** [comment]
I have also faced the same issue but with different dataset. The issue seems to be generated by setting transform_target = True. The error disappeared with transform_target = Fslse.
Could you also try setting transform_target = False?

**Comment by weishunc5** [comment]
> I have also faced the same issue but with different dataset. The issue seems to be generated by setting transform_target = True. The error disappeared with transform_target = Fslse.
> Could you also try setting transform_target = False?

Thanks mate, you are right. Once I turn off the transform_target option, there is no such error.

**Comment by Arun-Chhikara** [comment]
> > I have also faced the same issue but with different dataset. The issue seems to be generated by setting transform_target = True. The error disappeared with transform_target = Fslse.
> > Could you also try setting transform_target = False?
> 
> Thanks mate, you are right. Once I turn off the transform_target option, there is no such error.

So it appears that applying transformations to target variable is introducing some unacceptable values. This might also happen with independent variables.
@pycaret Is there any way to peek into the resulting dataset once all the preprocessing steps defined in setup() are applied? Also, how we can access the objects and their attributes in the pipeline created by setup()?

**Comment by Yard1** [comment]
@Arun-Chhikara Can you share your dataset?

**Comment by Arun-Chhikara** [comment]
> @Arun-Chhikara Can you share your dataset?

Hello @Yard1 You can use diamond data set to reproduce this. Below are the line from PyCaret Tutorial

from pycaret.datasets import get_data
dataset = get_data('diamond')
data = dataset.sample(frac=0.9, random_state=786)
data_unseen = dataset.drop(data.index)
data.reset_index(drop=True, inplace=True)
data_unseen.reset_index(drop=True, inplace=True)

exp_reg102 = setup(data = data, target = 'Price', session_id=133, numeric_imputation = 'mean', categorical_imputation = 'mode', normalize = True, transformation = True, transform_target = True, combine_rare_levels = True, rare_level_threshold = 0.05, remove_multicollinearity = True, multicollinearity_threshold = 0.95, bin_numeric_features = ['Carat Weight'], log_experiment = False)

create_model('ada')

**Comment by Yard1** [comment]
Thanks, I'll take a look.

**Comment by Arun-Chhikara** [comment]
Hello @Yard1 Is there any way that I can access/get the transformed train and test data sets the model/pipeline/stack is trained on?

**Comment by Yard1** [comment]
`get_config('X')`, `get_config('X_train')`, `get_config('X_test')`. Same goes for `y`. Please note that target transformation is applied during model fitting and thus will not be shown.

**Comment by Yard1** [comment]
@Arun-Chhikara @weishunc5 I just pushed commit a17051a842186e31fdb53f833f1af93d4772908e that should fix this issue. Could you run
`pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` to install PyCaret's development version and try again?

**Comment by Arun-Chhikara** [comment]
> @Arun-Chhikara @weishunc5 I just pushed commit [a17051a](https://github.com/pycaret/pycaret/commit/a17051a842186e31fdb53f833f1af93d4772908e) that should fix this issue. Could you run
> `pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` to install PyCaret's development version and try again?

@Yard1 Thank you so much! I will check and let you know.

**Comment by pycaret** [comment]
@Arun-Chhikara @weishunc5 This issue has been fixed. Please update your version to `pycaret==2.2.2`.

If the issue persists, please feel free to open another issue.

Thanks for reporting.

**Comment by sharathchandra04** [comment]
Traceback (most recent call last):
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
    r = call_item()
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 560, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 607, in _score
    scores = scorer(estimator, X_test, y_test)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 87, in __call__
    score = scorer._score(cached_call, estimator,
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 212, in _score
    return self._sign * self._score_func(y_true, y_pred,
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 178, in mean_absolute_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 86, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 644, in check_array
    _assert_all_finite(array,
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 96, in _assert_all_finite
    raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/logiq/work/logiq/logiq-backend/logiqdemo/pycaretapp/views.py", line 795, in get
    best = reg.compare_models(sort = 'MAE', errors="raise",)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/pycaret/regression.py", line 765, in compare_models
    return pycaret.internal.tabular.compare_models(
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2198, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3167, in create_model_supervised
    scores = cross_validate(
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
    scores = parallel(
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/parallel.py", line 1054, in __call__
    self.retrieve()
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/parallel.py", line 933, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').



trying to do regression on the data from this csv ----> https://raw.githubusercontent.com/sharathchandra04/logiq-backend/master/logiqQueryCsv.csv
compare_models gives the error.

url = 'https://raw.githubusercontent.com/sharathchandra04/logiq-backend/master/logiqQueryCsv.csv'
    df = pd.read_csv(url, index_col=False)
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    df['MA12'] = df['value'].rolling(12).mean()
    df['Year'] = [i.year for i in df['timestamp']]
    df['Month'] = [i.month for i in df['timestamp']]

    df['Series'] = np.arange(1,len(df)+1)
    df.head()
    df['Series'] = np.arange(1,len(df)+1)
    df.drop(['timestamp', 'MA12'], axis=1, inplace=True)
    df = df[['Series', 'Year', 'Month', 'value']]
    partition = int(4*len(df)/5)
    df1 = df.iloc[0:partition]
    df2 = df.iloc[partition:]
    train = df1
    test = df2
    s = reg.setup(
        data = train,
        test_data = test, 
        target = 'value', 
        fold_strategy = 'timeseries',
        numeric_features = ['Year', 'Series'],
        transform_target = True, 
        session_id = 123, 
        silent=True,
        log_experiment = True,
      )

    best = reg.compare_models(sort = 'MAE', errors="raise",)

**Comment by sharathchandra04** [comment]
> @Arun-Chhikara @weishunc5 This issue has been fixed. Please update your version to `pycaret==2.2.2`.
> 
> If the issue persists, please feel free to open another issue.
> 
> Thanks for reporting.


Traceback (most recent call last):
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
r = call_item()
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 285, in call
return self.fn(*self.args, **self.kwargs)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in call
return self.func(*args, **kwargs)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/parallel.py", line 262, in call
return [func(*args, **kwargs)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/parallel.py", line 262, in
return [func(*args, **kwargs)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 560, in _fit_and_score
test_scores = _score(estimator, X_test, y_test, scorer)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 607, in _score
scores = scorer(estimator, X_test, y_test)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 87, in call
score = scorer._score(cached_call, estimator,
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/metrics/_scorer.py", line 212, in _score
return self._sign * self._score_func(y_true, y_pred,
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
return f(**kwargs)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 178, in mean_absolute_error
y_type, y_true, y_pred, multioutput = _check_reg_targets(
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/metrics/_regression.py", line 86, in _check_reg_targets
y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
return f(**kwargs)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 644, in check_array
_assert_all_finite(array,
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 96, in _assert_all_finite
raise ValueError(
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
return view_func(*args, **kwargs)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/django/views/generic/base.py", line 70, in view
return self.dispatch(request, *args, **kwargs)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/rest_framework/views.py", line 509, in dispatch
response = self.handle_exception(exc)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/rest_framework/views.py", line 469, in handle_exception
self.raise_uncaught_exception(exc)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
raise exc
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
response = handler(request, *args, **kwargs)
File "/home/logiq/work/logiq/logiq-backend/logiqdemo/pycaretapp/views.py", line 795, in get
best = reg.compare_models(sort = 'MAE', errors="raise",)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/pycaret/regression.py", line 765, in compare_models
return pycaret.internal.tabular.compare_models(
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 2198, in compare_models
model, model_fit_time = create_model_supervised(**create_model_args)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/pycaret/internal/tabular.py", line 3167, in create_model_supervised
scores = cross_validate(
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/utils/validation.py", line 72, in inner_f
return f(**kwargs)
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 242, in cross_validate
scores = parallel(
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/parallel.py", line 1054, in call
self.retrieve()
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/parallel.py", line 933, in retrieve
self._output.extend(job.get(timeout=self.timeout))
File "/home/logiq/work/logiq/logiq-backend/venv/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
return future.result(timeout=timeout)
File "/usr/lib/python3.9/concurrent/futures/_base.py", line 445, in result
return self.__get_result()
File "/usr/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
raise self._exception
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').

trying to do regression on the data from this csv ----> https://raw.githubusercontent.com/sharathchandra04/logiq-backend/master/logiqQueryCsv.csv
compare_models gives the error.

url = 'https://raw.githubusercontent.com/sharathchandra04/logiq-backend/master/logiqQueryCsv.csv'
df = pd.read_csv(url, index_col=False)
df['timestamp'] = pd.to_datetime(df['timestamp'])
df['MA12'] = df['value'].rolling(12).mean()
df['Year'] = [i.year for i in df['timestamp']]
df['Month'] = [i.month for i in df['timestamp']]

df['Series'] = np.arange(1,len(df)+1)
df.head()
df['Series'] = np.arange(1,len(df)+1)
df.drop(['timestamp', 'MA12'], axis=1, inplace=True)
df = df[['Series', 'Year', 'Month', 'value']]
partition = int(4*len(df)/5)
df1 = df.iloc[0:partition]
df2 = df.iloc[partition:]
train = df1
test = df2
s = reg.setup(
    data = train,
    test_data = test, 
    target = 'value', 
    fold_strategy = 'timeseries',
    numeric_features = ['Year', 'Series'],
    transform_target = True, 
    session_id = 123, 
    silent=True,
    log_experiment = True,
  )

best = reg.compare_models(sort = 'MAE', errors="raise",)
