### ISSUE TITLE
classification.load_model is not compatible in different version

### ISSUE THREAD

**Issue by OnceUponATime-Syd** [pycaret/pycaret#891]
**Is your feature request related to a problem? Please describe.**
I have a classification model saved with pycaret 2.1, and lately I upgraded to pycaret 2.2, then I got an error message "ModuleNotFoundError: No module named 'pycaret.preprocess'" when I tried to load the model. After freshly re-installed the whole environment several times, I eventually found that the load_model function from pycaret 2.2 won't load the model saved with pycaret 2.1. And likewise, the model saved with pycaret 2.2 won't be load using pycaret2.1.

**Describe the solution you'd like**
It would be good the model saved with old versions still can be loaded by the newer version, otherwise, lots of work will be wasted after upgraded to the latest version for the improved features.

**Comment by Yard1** [comment]
We are sorry for any inconvenience this has caused. Maintaining compatibility with previous versions is something we always try to take into account, but large scale refactors as in 2.2 sometimes make it impossible.

**Comment by pycaret** [comment]
@OnceUponATime-Syd Unfortunately nothing can be done at the moment. We will improve our processes in the future to ensure the compatibility of certain functions like `save_model`, `load_model`, `predict_model` is not impacted.

**Comment by akramIOT** [comment]
same issue here  and  NOT able to load a Model with load  API  which was previously  trained in older pycaret versions.

(python ) (base) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % conda env list
# conda environments:
#
AKRAM_CODE_FOLDER        /Users/akram/.conda/envs/AKRAM_CODE_FOLDER
base                  *  /Users/akram/opt/anaconda3
pycaret_akram            /Users/akram/opt/anaconda3/envs/pycaret_akram

(python ) (base) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % conda activate pycaret_akram 
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % 
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % ls
FreeWifi                        Tutorials                       pycaret-streamlit-google        streamlit-sales-dashboard
Juice.py                        logs.log                        st_1.py                         test_st.py
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % 
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % ls
FreeWifi                        Tutorials                       logs.log                        st_1.py                         test_st.py
Juice.py                        deployment_28042020.pkl         pycaret-streamlit-google        streamlit-sales-dashboard
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % 
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % 
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % 
(pycaret_akram) (python ) akram@ISHERIFF-M-RBNA STREAMLIT_APPS % streamlit run test_st.py     
2022-03-09 17:30:43.866 INFO    numexpr.utils: Note: NumExpr detected 12 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2022-03-09 17:30:43.866 INFO    numexpr.utils: NumExpr defaulting to 8 threads.

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.24.21.99:8501

2022-03-09 17:30:48.440 Initializing load_model()
2022-03-09 17:30:48.440 Initializing load_model()
2022-03-09 17:30:48.440 Initializing load_model()
2022-03-09 17:30:48.441 load_model(model_name=deployment_28042020, platform=None, authentication=None, verbose=True)
Transformation Pipeline and Model Successfully Loaded
2022-03-09 17:30:48.441 load_model(model_name=deployment_28042020, platform=None, authentication=None, verbose=True)
Transformation Pipeline and Model Successfully Loaded
2022-03-09 17:30:48.441 load_model(model_name=deployment_28042020, platform=None, authentication=None, verbose=True)
Transformation Pipeline and Model Successfully Loaded
2022-03-09 17:30:48.454 Traceback (most recent call last):
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/streamlit/script_runner.py", line 430, in _run_script
    exec(code, module.__dict__)
  File "/Users/akram/AKRAM_CODE_FOLDER/ML/Washington_ML/STREAMLIT_APPS/test_st.py", line 7, in <module>
    model = load_model('deployment_28042020')
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/pycaret/regression.py", line 1930, in load_model
    return pycaret.internal.tabular.load_model(
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/pycaret/internal/tabular.py", line 8939, in load_model
    return pycaret.internal.persistence.load_model(
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/pycaret/internal/persistence.py", line 373, in load_model
    return joblib.load(model_name)
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1579, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'pycaret.preprocess'

2022-03-09 17:30:48.454 Traceback (most recent call last):
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/streamlit/script_runner.py", line 430, in _run_script
    exec(code, module.__dict__)
  File "/Users/akram/AKRAM_CODE_FOLDER/ML/Washington_ML/STREAMLIT_APPS/test_st.py", line 7, in <module>
    model = load_model('deployment_28042020')
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/pycaret/regression.py", line 1930, in load_model
    return pycaret.internal.tabular.load_model(
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/pycaret/internal/tabular.py", line 8939, in load_model
    return pycaret.internal.persistence.load_model(
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/pycaret/internal/persistence.py", line 373, in load_model
    return joblib.load(model_name)
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/Users/akram/opt/anaconda3/envs/pycaret_akram/bin/python /lib/python3.9/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1528, in load_global
    klass = self.find_class(module, name)
  File "/usr/local/Cellar/python@3.9/3.9.7_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pickle.py", line 1579, in find_class
    __import__(module, level=0)
ModuleNotFoundError: No module named 'pycaret.preprocess'

2022-03-09 17:30:48.454 Traceback (most recent call last):
