### ISSUE TITLE
AttributeError: 'Remove_100' object has no attribute 'columns_to_drop'

### ISSUE THREAD

**Issue by Mads-hg** [pycaret/pycaret#896]
Hi,

While trying to use Pycaret with data from the attached file (had to rename it to .txt, to upload it). I get the following error:

```
(ML) Mads@madsbook-pro ML % python ML.py
       RRMS  Percent
0    1.0000   0.0000
1    1.0008   0.1016
2    1.0017   0.2033
3    1.0025   0.3049
4    1.0033   0.4065
..      ...      ...
979  4.8814  99.4919
980  4.9455  99.5935
981  5.0112  99.6951
982  5.0501  99.7967
983  5.0874  99.8984

[984 rows x 2 columns]
IntProgress(value=0, description='Processing: ', max=3)
                                                                    
                                                                    
Initiated  . . . . . . . . . . . . . . . . . .              20:06:25
Status     . . . . . . . . . . . . . . . . . .  Loading Dependencies
                                                                           
                                                                           
Initiated  . . . . . . . . . . . . . . . . . .                     20:06:25
Status     . . . . . . . . . . . . . . . . . .  Preparing Data for Modeling
                                                                           
                                                                           
Initiated  . . . . . . . . . . . . . . . . . .                     20:06:25
Status     . . . . . . . . . . . . . . . . . .  Preparing Data for Modeling
                                                                  
                                                                  
Initiated  . . . . . . . . . . . . . . . . . .            20:06:25
Status     . . . . . . . . . . . . . . . . . .  Preprocessing Data
                                                                  
                                                                  
Initiated  . . . . . . . . . . . . . . . . . .            20:06:25
Status     . . . . . . . . . . . . . . . . . .  Preprocessing Data
Text(value="Following data types have been inferred automatically, if they are correct press enter to continue or type 'quit' otherwise.", layout=Layout(width='100%'))
        Data Type
RRMS      Numeric
Percent     Label

Traceback (most recent call last):
  File "ML.py", line 8, in <module>
    reg = setup(df, target='Percent')
  File "/Users/Mads/opt/anaconda3/envs/ML/lib/python3.6/site-packages/pycaret/regression.py", line 645, in setup
    profile_kwargs=profile_kwargs,
  File "/Users/Mads/opt/anaconda3/envs/ML/lib/python3.6/site-packages/pycaret/internal/tabular.py", line 1308, in setup
    test_data = prep_pipe.transform(test_data)
  File "/Users/Mads/opt/anaconda3/envs/ML/lib/python3.6/site-packages/sklearn/pipeline.py", line 549, in _transform
    Xt = transform.transform(Xt)
  File "/Users/Mads/opt/anaconda3/envs/ML/lib/python3.6/site-packages/pycaret/internal/preprocess.py", line 2787, in transform
    return dataset.drop(self.columns_to_drop, axis=1)
AttributeError: 'Remove_100' object has no attribute 'columns_to_drop'
```

This is my code:
```
from pycaret.regression import *
import pandas

df = pd.read_csv('/Users/Mads/GitHub/TS1/LRT_RRMS.csv', index_col = 0)  

print(df)

reg = setup(df, target='Percent')

compare_models()
```

Important: If I reduce the data file to only include 4 rows of data, the problem doesn't occur.

Thanks for your help!

[LRT_RRMS.txt](https://github.com/pycaret/pycaret/files/5609302/LRT_RRMS.txt)

**Comment by Yard1** [comment]
I just pushed commit b2833e6a4daa1c6286f3c5a3c17fb8404a01d23e that should fix this issue. Could you run
`pip install --upgrade --user git+git://github.com/pycaret/pycaret.git` to install PyCaret's development version and try again?

**Comment by Mads-hg** [comment]
That fixed the issue! Thanks.

**Comment by gitJoachim** [comment]
yeah! this also worked for me I had the same problem...
