### ISSUE TITLE
MLFlow doesn't save model artifact and some plots - Clustering

### ISSUE THREAD

**Issue by DXcarlos** [pycaret/pycaret#931]
I'm using clustering module of pycaret and the integration with mlflow but I have problems because I think it doesn't save all artifacs and the status is always failed.
![image](https://user-images.githubusercontent.com/12554263/101971863-66f70d00-3c02-11eb-9710-01cf228fca1b.png)

This is my code:

```python
from pycaret.clustering import *

postpaid_exp = setup(postpaid_sample,
                     ignore_features=ignore_features,
                     numeric_features=numeric_features,
                     normalize=True,
                     normalize_method='robust',
                     remove_multicollinearity=True,
                     multicollinearity_threshold=0.7,
                     log_experiment=True,
                     log_plots=True,
                     log_profile=True,
                     log_data=True,
                     profile=False,
                     experiment_name='pospatid_segmentation',
                     session_id=123)

# Create model with six clusters
model_kmeans =  create_model(model='kmeans', num_clusters=6)
```
My logs are the following

```
2020-12-11 22:39:07,118:INFO:PyCaret Supervised Module
2020-12-11 22:39:07,118:INFO:ML Usecase: clustering
2020-12-11 22:39:07,118:INFO:version 2.2.0
2020-12-11 22:39:07,118:INFO:Initializing setup()
2020-12-11 22:39:07,119:INFO:setup(target=None, ml_usecase=clustering, available_plots={'cluster': 'Cluster PCA Plot (2d)', 'tsne': 'Cluster TSnE (3d)', 'elbow': 'Elbow', 'silhouette': 'Silhouette', 'distance': 'Distance', 'distribution': 'Distribution'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=mode, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=['avg_dias_bancos_3m', 'avg_dias_app_pagos_3m', 'avg_dias_viajes_3m', 'avg_dias_compras_3m', 'avg_dias_mb_total_3m', 'avg_mb_total_3m', 'avg_q_apps_3m', 'ate_wh_sum_dias_3m', 'LEADs_tot_3m', 'tot_dias_appmov_movil_3m', 'avg_days_out_voice_tot_3m', 'meses_pagodig_3m'], numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=['periodo', 'telefono', 'anexo', 'tot_dias_appmov_fija_3m', 'avg_dias_vid_mus_3m'], normalize=True, normalize_method=robust, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=True, multicollinearity_threshold=0.7, remove_perfect_collinearity=False, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=False, data_split_stratify=False, fold_strategy=kfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=123, log_experiment=True, experiment_name=pospatid_segmentation, log_plots=['cluster', 'distribution', 'elbow'], log_profile=True, log_data=True, silent=False, verbose=True, profile=False, display=None)
2020-12-11 22:39:07,119:INFO:Checking environment
2020-12-11 22:39:07,119:INFO:python_version: 3.8.5
2020-12-11 22:39:07,119:INFO:python_build: ('default', 'Aug  5 2020 09:44:06')
2020-12-11 22:39:07,119:INFO:machine: AMD64
2020-12-11 22:39:07,120:INFO:platform: Windows-10-10.0.18362-SP0
2020-12-11 22:39:07,121:WARNING:cannot find psutil installation. memory not traceable. Install psutil using pip to enable memory logging.
2020-12-11 22:39:07,122:INFO:Checking libraries
2020-12-11 22:39:07,122:INFO:pd==1.1.4
2020-12-11 22:39:07,122:INFO:numpy==1.19.4
2020-12-11 22:39:07,122:INFO:sklearn==0.23.2
2020-12-11 22:39:07,156:INFO:xgboost==1.2.0
2020-12-11 22:39:07,156:INFO:lightgbm==3.0.0
2020-12-11 22:39:07,170:INFO:catboost==0.24.1
2020-12-11 22:39:07,901:INFO:mlflow==1.11.0
2020-12-11 22:39:07,901:INFO:Checking Exceptions
2020-12-11 22:39:07,901:INFO:Declaring global variables
2020-12-11 22:39:07,901:INFO:USI: cd5c
2020-12-11 22:39:07,901:INFO:pycaret_globals: {'_available_plots', 'master_model_container', 'display_container', 'imputation_classifier', 'logging_param', 'seed', 'transform_target_param', 'experiment__', 'transform_target_method_param', 'iterative_imputation_iters_param', 'fold_groups_param', 'fix_imbalance_param', 'prep_pipe', 'exp_name_log', '_all_metrics', 'html_param', '_ml_usecase', 'USI', 'imputation_regressor', 'stratify_param', 'fold_generator', 'fix_imbalance_method_param', '_all_models', 'gpu_param', 'target_param', '_gpu_n_jobs_param', 'log_plots_param', 'pycaret_globals', 'fold_shuffle_param', '_all_models_internal', 'fold_param', 'create_model_container', 'data_before_preprocess', '_internal_pipeline', 'X', 'n_jobs_param'}
2020-12-11 22:39:07,901:INFO:Preparing display monitor
2020-12-11 22:39:07,901:INFO:Preparing display monitor
2020-12-11 22:39:07,914:INFO:Importing libraries
2020-12-11 22:39:07,914:INFO:Copying data for preprocessing
2020-12-11 22:39:07,927:INFO:Declaring preprocessing parameters
2020-12-11 22:39:07,940:INFO:Creating preprocessing pipeline
2020-12-11 22:39:08,059:INFO:Preprocessing pipeline created successfully
2020-12-11 22:39:08,060:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2020-12-11 22:39:08,060:INFO:Creating global containers
2020-12-11 22:39:08,061:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2020-12-11 22:39:10,064:INFO:Creating grid variables
2020-12-11 22:39:10,101:INFO:Logging experiment in MLFlow
2020-12-11 22:39:10,108:WARNING:Couldn't create mlflow experiment. Exception:
2020-12-11 22:39:10,185:WARNING:Traceback (most recent call last):
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\pycaret\internal\tabular.py", line 1668, in setup
    mlflow.create_experiment(exp_name_log)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\mlflow\tracking\fluent.py", line 365, in create_experiment
    return MlflowClient().create_experiment(name, artifact_location)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\mlflow\tracking\client.py", line 184, in create_experiment
    return self._tracking_client.create_experiment(name, artifact_location)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 142, in create_experiment
    return self.store.create_experiment(name=name, artifact_location=artifact_location,)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\mlflow\store\tracking\file_store.py", line 288, in create_experiment
    self._validate_experiment_name(name)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\mlflow\store\tracking\file_store.py", line 281, in _validate_experiment_name
    raise MlflowException(
mlflow.exceptions.MlflowException: Experiment 'pospatid_segmentation' already exists.

2020-12-11 22:39:10,490:INFO:SubProcess save_model() called ==================================
2020-12-11 22:39:10,501:INFO:Initializing save_model()
2020-12-11 22:39:10,501:INFO:save_model(model=Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True,
                                      features_todrop=['periodo', 'telefono',
                                                       'anexo',
                                                       'tot_dias_appmov_fija_3m',
                                                       'avg_dias_vid_mus_3m'],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=['avg_dias_bancos_3m',
                                                          'avg_dias_app_pagos_3m',
                                                          'avg_dias_viajes_3m',
                                                          'avg_dias_compras_3m',
                                                          'av...
                ('dummy', Dummify(target='UNSUPERVISED_DUMMY_TARGET')),
                ('fix_perfect', 'passthrough'),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'),
                ('fix_multi',
                 Fix_multicollinearity(correlation_with_target_preference=None,
                                       correlation_with_target_threshold=0.0,
                                       target_variable='UNSUPERVISED_DUMMY_TARGET',
                                       threshold=0.7)),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False), model_name=Transformation Pipeline, prep_pipe_=Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True,
                                      features_todrop=['periodo', 'telefono',
                                                       'anexo',
                                                       'tot_dias_appmov_fija_3m',
                                                       'avg_dias_vid_mus_3m'],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=['avg_dias_bancos_3m',
                                                          'avg_dias_app_pagos_3m',
                                                          'avg_dias_viajes_3m',
                                                          'avg_dias_compras_3m',
                                                          'av...
                ('dummy', Dummify(target='UNSUPERVISED_DUMMY_TARGET')),
                ('fix_perfect', 'passthrough'),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'),
                ('fix_multi',
                 Fix_multicollinearity(correlation_with_target_preference=None,
                                       correlation_with_target_threshold=0.0,
                                       target_variable='UNSUPERVISED_DUMMY_TARGET',
                                       threshold=0.7)),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False), verbose=False)
2020-12-11 22:39:10,501:INFO:Adding model into prep_pipe
2020-12-11 22:39:10,506:WARNING:Only Model saved as it was a pipeline.
2020-12-11 22:39:10,530:INFO:Transformation Pipeline.pkl saved in current working directory
2020-12-11 22:39:10,535:INFO:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True,
                                      features_todrop=['periodo', 'telefono',
                                                       'anexo',
                                                       'tot_dias_appmov_fija_3m',
                                                       'avg_dias_vid_mus_3m'],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=['avg_dias_bancos_3m',
                                                          'avg_dias_app_pagos_3m',
                                                          'avg_dias_viajes_3m',
                                                          'avg_dias_compras_3m',
                                                          'av...
                ('dummy', Dummify(target='UNSUPERVISED_DUMMY_TARGET')),
                ('fix_perfect', 'passthrough'),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'),
                ('fix_multi',
                 Fix_multicollinearity(correlation_with_target_preference=None,
                                       correlation_with_target_threshold=0.0,
                                       target_variable='UNSUPERVISED_DUMMY_TARGET',
                                       threshold=0.7)),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
2020-12-11 22:39:10,535:INFO:save_model() succesfully completed......................................
2020-12-11 22:39:10,536:INFO:SubProcess save_model() end ==================================
2020-12-11 22:40:03,332:INFO:create_model_container: 0
2020-12-11 22:40:03,332:INFO:master_model_container: 0
2020-12-11 22:40:03,332:INFO:display_container: 0
2020-12-11 22:40:03,336:INFO:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True,
                                      features_todrop=['periodo', 'telefono',
                                                       'anexo',
                                                       'tot_dias_appmov_fija_3m',
                                                       'avg_dias_vid_mus_3m'],
                                      id_columns=[],
                                      ml_usecase='classification',
                                      numerical_features=['avg_dias_bancos_3m',
                                                          'avg_dias_app_pagos_3m',
                                                          'avg_dias_viajes_3m',
                                                          'avg_dias_compras_3m',
                                                          'av...
                ('dummy', Dummify(target='UNSUPERVISED_DUMMY_TARGET')),
                ('fix_perfect', 'passthrough'),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'),
                ('fix_multi',
                 Fix_multicollinearity(correlation_with_target_preference=None,
                                       correlation_with_target_threshold=0.0,
                                       target_variable='UNSUPERVISED_DUMMY_TARGET',
                                       threshold=0.7)),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
2020-12-11 22:40:03,336:INFO:setup() succesfully completed......................................
2020-12-11 22:40:07,628:INFO:Initializing create_model()
2020-12-11 22:40:07,628:INFO:create_model(estimator=kmeans, num_clusters=6, fraction=0.05, ground_truth=None, round=4, fit_kwargs=None, verbose=True, system=True, raise_num_clusters=False, display=None, kwargs={})
2020-12-11 22:40:07,628:INFO:Checking exceptions
2020-12-11 22:40:07,629:INFO:Preparing display monitor
2020-12-11 22:40:07,645:INFO:Importing libraries
2020-12-11 22:40:07,652:INFO:Importing untrained model
2020-12-11 22:40:07,662:INFO:K-Means Clustering Imported succesfully
2020-12-11 22:40:07,670:INFO:Fitting Model
2020-12-11 22:42:30,467:INFO:KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=6, n_init=10, n_jobs=-1, precompute_distances='deprecated',
       random_state=123, tol=0.0001, verbose=0)
2020-12-11 22:42:30,467:INFO:create_models() succesfully completed......................................
2020-12-11 22:42:30,467:INFO:Creating MLFlow logs
2020-12-11 22:42:30,481:INFO:Model: K-Means Clustering
2020-12-11 22:42:30,518:INFO:logged params: {'algorithm': 'auto', 'copy_x': True, 'init': 'k-means++', 'max_iter': 300, 'n_clusters': 6, 'n_init': 10, 'n_jobs': -1, 'precompute_distances': 'deprecated', 'random_state': 123, 'tol': 0.0001, 'verbose': 0}
2020-12-11 22:42:30,557:INFO:SubProcess plot_model() called ==================================
2020-12-11 22:42:30,557:INFO:Initializing plot_model()
2020-12-11 22:42:30,557:INFO:plot_model(plot=cluster, fold=None, verbose=False, display=None, estimator=KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=6, n_init=10, n_jobs=-1, precompute_distances='deprecated',
       random_state=123, tol=0.0001, verbose=0), feature_name=None, fit_kwargs=None, groups=None, label=False, save=True, scale=1, system=False)
2020-12-11 22:42:30,557:INFO:Checking exceptions
2020-12-11 22:42:30,558:INFO:Preloading libraries
2020-12-11 22:42:30,558:INFO:Copying training dataset
2020-12-11 22:42:30,560:INFO:Plot type: cluster
2020-12-11 22:42:31,493:INFO:SubProcess assign_model() called ==================================
2020-12-11 22:42:31,494:INFO:Initializing assign_model()
2020-12-11 22:42:31,494:INFO:assign_model(model=Pipeline(memory=None,
         steps=[('empty_step', 'passthrough'),
                ('actual_estimator',
                 KMeans(algorithm='auto', copy_x=True, init='k-means++',
                        max_iter=300, n_clusters=6, n_init=10, n_jobs=-1,
                        precompute_distances='deprecated', random_state=123,
                        tol=0.0001, verbose=0))],
         verbose=False), transformation=True, score=True, verbose=False)
2020-12-11 22:42:31,494:INFO:Checking exceptions
2020-12-11 22:42:31,495:INFO:Determining Trained Model
2020-12-11 22:42:31,495:INFO:Trained Model : K-Means Clustering
2020-12-11 22:42:31,495:INFO:Copying data
2020-12-11 22:42:31,496:INFO:Transformation param set to True. Assigned clusters are attached on transformed dataset.
2020-12-11 22:42:31,529:INFO:(90000, 12)
2020-12-11 22:42:31,529:INFO:assign_model() succesfully completed......................................
2020-12-11 22:42:31,530:INFO:SubProcess assign_model() end ==================================
2020-12-11 22:42:31,541:INFO:Fitting PCA()
2020-12-11 22:42:31,908:INFO:Sorting dataframe
2020-12-11 22:42:31,974:INFO:Rendering Visual
2020-12-11 22:42:41,765:INFO:Saving 'Cluster PCA Plot (2d).html' in current active directory
2020-12-11 22:42:41,765:INFO:Visual Rendered Successfully
2020-12-11 22:42:42,286:INFO:plot_model() succesfully completed......................................
2020-12-11 22:42:42,739:INFO:Initializing plot_model()
2020-12-11 22:42:42,739:INFO:plot_model(plot=distribution, fold=None, verbose=False, display=None, estimator=KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=6, n_init=10, n_jobs=-1, precompute_distances='deprecated',
       random_state=123, tol=0.0001, verbose=0), feature_name=None, fit_kwargs=None, groups=None, label=False, save=True, scale=1, system=False)
2020-12-11 22:42:42,739:INFO:Checking exceptions
2020-12-11 22:42:42,739:INFO:Preloading libraries
2020-12-11 22:42:42,739:INFO:Copying training dataset
2020-12-11 22:42:42,741:INFO:Plot type: distribution
2020-12-11 22:42:42,741:INFO:SubProcess assign_model() called ==================================
2020-12-11 22:42:42,742:INFO:Initializing assign_model()
2020-12-11 22:42:42,742:INFO:assign_model(model=Pipeline(memory=None,
         steps=[('empty_step', 'passthrough'),
                ('actual_estimator',
                 KMeans(algorithm='auto', copy_x=True, init='k-means++',
                        max_iter=300, n_clusters=6, n_init=10, n_jobs=-1,
                        precompute_distances='deprecated', random_state=123,
                        tol=0.0001, verbose=0))],
         verbose=False), transformation=False, score=True, verbose=False)
2020-12-11 22:42:42,742:INFO:Checking exceptions
2020-12-11 22:42:42,742:INFO:Determining Trained Model
2020-12-11 22:42:42,742:INFO:Trained Model : K-Means Clustering
2020-12-11 22:42:42,742:INFO:Copying data
2020-12-11 22:42:42,793:INFO:(90000, 18)
2020-12-11 22:42:42,793:INFO:assign_model() succesfully completed......................................
2020-12-11 22:42:42,794:INFO:SubProcess assign_model() end ==================================
2020-12-11 22:42:42,794:INFO:Sorting dataframe
2020-12-11 22:42:42,925:INFO:Rendering Visual
2020-12-11 22:42:48,837:INFO:Saving 'Distribution.html' in current active directory
2020-12-11 22:42:48,837:INFO:Visual Rendered Successfully
2020-12-11 22:42:48,979:INFO:plot_model() succesfully completed......................................
2020-12-11 22:42:49,583:INFO:Initializing plot_model()
2020-12-11 22:42:49,584:INFO:plot_model(plot=elbow, fold=None, verbose=False, display=None, estimator=KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=6, n_init=10, n_jobs=-1, precompute_distances='deprecated',
       random_state=123, tol=0.0001, verbose=0), feature_name=None, fit_kwargs=None, groups=None, label=False, save=True, scale=1, system=False)
2020-12-11 22:42:49,584:INFO:Checking exceptions
2020-12-11 22:42:49,584:INFO:Preloading libraries
2020-12-11 22:42:49,584:INFO:Copying training dataset
2020-12-11 22:42:49,586:INFO:Plot type: elbow
2020-12-11 22:42:49,690:INFO:Fitting Model
2020-12-11 22:43:12,604:INFO:Saving 'Elbow.png' in current active directory
2020-12-11 22:43:13,207:INFO:Visual Rendered Successfully
2020-12-11 22:43:13,325:INFO:plot_model() succesfully completed......................................
2020-12-11 22:43:13,340:INFO:SubProcess plot_model() end ==================================
2020-12-11 22:43:13,341:WARNING:Couldn't infer MLFlow signature.
2020-12-11 22:43:13,352:ERROR:_mlflow_log_model() for KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=6, n_init=10, n_jobs=-1, precompute_distances='deprecated',
       random_state=123, tol=0.0001, verbose=0) raised an exception:
2020-12-11 22:43:13,431:ERROR:Traceback (most recent call last):
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\pycaret\internal\tabular.py", line 2631, in create_model_unsupervised
    _mlflow_log_model(
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\pycaret\internal\tabular.py", line 9942, in _mlflow_log_model
    mlflow.sklearn.log_model(
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\mlflow\sklearn\__init__.py", line 290, in log_model
    return Model.log(
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\mlflow\models\model.py", line 160, in log
    flavor.save_model(path=local_path, mlflow_model=mlflow_model, **kwargs)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\mlflow\sklearn\__init__.py", line 171, in save_model
    _save_example(mlflow_model, input_example, path)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\mlflow\models\utils.py", line 131, in _save_example
    example = _Example(input_example)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\mlflow\models\utils.py", line 67, in __init__
    input_example = pd.DataFrame.from_dict(input_example)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\pandas\core\frame.py", line 1309, in from_dict
    return cls(data, index=index, columns=columns, dtype=dtype)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\pandas\core\frame.py", line 468, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\pandas\core\internals\construction.py", line 283, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\pandas\core\internals\construction.py", line 78, in arrays_to_mgr
    index = extract_index(arrays)
  File "C:\Users\CARLOS\Anaconda3\envs\dev_models\lib\site-packages\pandas\core\internals\construction.py", line 387, in extract_index
    raise ValueError("If using all scalar values, you must pass an index")
ValueError: If using all scalar values, you must pass an index

2020-12-11 22:43:13,432:INFO:Uploading results into container
2020-12-11 22:43:13,435:INFO:Uploading model into container now
2020-12-11 22:43:13,440:INFO:create_model_container: 1
2020-12-11 22:43:13,440:INFO:master_model_container: 1
2020-12-11 22:43:13,440:INFO:display_container: 1
2020-12-11 22:43:13,440:INFO:KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
       n_clusters=6, n_init=10, n_jobs=-1, precompute_distances='deprecated',
       random_state=123, tol=0.0001, verbose=0)
2020-12-11 22:43:13,440:INFO:create_model() succesfully completed......................................

```

I'm using Pycaret version : 2.2.0

**Comment by pycaret** [comment]
@DXcarlos I have tried to reproduce the error on `jewellery` dataset available on our GitHub repository and I couldn't reproduce this error.

Is it possible for you to share the Notebook along with the dataset so we can reproduce the error and troubleshoot what is causing this?

I am including @Yard1 in this thread to see if he can understand what's going on with the log file you shared above. Antoni, maybe something specific to the dataset.

**Comment by DXcarlos** [comment]
@pycaret @Yard1 How can I share you privately?

**Comment by pycaret** [comment]
@DXcarlos You can private message on our Slack channel. If you are still not there, you can join using the following link:

https://join.slack.com/t/pycaret/shared_invite/zt-kdoe7hee-yvNANPHXPM9VtK7R6Npx4Q

**Comment by ngupta23** [comment]
@DXcarlos , we will close out this issue for now. Please feel free to reopen if you want.
